// Code generated by analysis/schema/rule/emitlaw; DO NOT EDIT.
//
// These are the laws every rule declaration owes by construction. They are
// derived from the declaration itself, so a family authors beside them only
// the laws that state what its fold means.

package program

import (
	"testing"

	schemaapi "github.com/wippyai/go-lua/analysis/schema"
	axismember "github.com/wippyai/go-lua/analysis/schema/axis/member"
	emitlaw "github.com/wippyai/go-lua/analysis/schema/rule/emitlaw"
	ruleprogram "github.com/wippyai/go-lua/analysis/schema/rule/program"
	axiscatalog "github.com/wippyai/go-lua/domain/value"
)

// allocationResultGeometry is the whole geometry the declaration carries, in the one
// canonical form every emitted law suite states a declaration in. It is total
// over the cold ABI: every join clause, contract term, fold argument, output
// clause, carry, and transport row appears on exactly one line.
const allocationResultGeometry = `operand              semantic/operand/value/allocation
candidate            relation=axis/value:value/allocation/candidates issued-row=-
observation          points=1 reads=0
observation.carry    point=0
carry                mode=transform input=0 transform=axis/value:transform/value/allocation output=scalar(0,0)
fold.reducer         axis/value:value/allocation/reducer
fold.inputs          none
output[0]            mode=exact value-slot=0 route=- column=axis/value:value/facts destination=axis/value:value/allocation/coordinate
transport            none
`

// TestAllocationResultGeometryIsTheOneItsLawSuiteWasEmittedFrom holds the declaration to the
// geometry above. The rendering is checked in beside the declaration and the
// freshness law re-derives it, so a declaration that moves without
// regeneration fails the build and one that moves with it is a reviewable
// diff of exactly what changed.
func TestAllocationResultGeometryIsTheOneItsLawSuiteWasEmittedFrom(t *testing.T) {
	if got := emitlaw.Canonical(AllocationResult()); got != allocationResultGeometry {
		t.Fatalf("declared geometry has moved away from its law suite:\ngot:\n%s\nwant:\n%s", got, allocationResultGeometry)
	}
}

// TestAllocationResultAgreesWithTheCallShapeOfTheReducerItNames is the one structural law a
// Program cannot settle alone. Check sees only the declaration, so a fold that
// hands its reducer a join the owner does not take is well formed in isolation
// and wrong against the row it names. The reducer's call shape is the owner
// axis's statement, and this law is where the two are held together.
func TestAllocationResultAgreesWithTheCallShapeOfTheReducerItNames(t *testing.T) {
	declaration := AllocationResult()
	if problem, valid := declaration.Check(); !valid {
		t.Fatalf("declaration is malformed: %+v", problem)
	}
	reducer, reducerOK := axiscatalog.AxisMemberCatalog().Reducer(schemaapi.Key("value/allocation/reducer"))
	if !reducerOK {
		t.Fatal("the reducer axis publishes no reducer named value/allocation/reducer")
	}
	if problem, valid := declaration.CheckAgainst(reducer); !valid {
		t.Fatalf("declaration disagrees with its reducer's call shape: %+v", problem)
	}
}

// TestAllocationResultIsHandedOutFresh states that the accessor yields a declaration a caller
// owns. Every law that probes a malformed edit mutates what it is handed, and a
// declaration backed by shared storage would carry one law's edit into the next
// reader - including the composition that seals it.
func TestAllocationResultIsHandedOutFresh(t *testing.T) {
	first := AllocationResult()
	first.OperandRole = "law/mutation/operand"
	for index := range first.Joins {
		first.Joins[index].Relation.Member = "law/mutation/relation"
		for source := range first.Joins[index].Sources {
			first.Joins[index].Sources[source] = ruleprogram.PriorSource(0)
		}
	}
	for index := range first.Fold.Outputs {
		first.Fold.Outputs[index].Destination.Member = "law/mutation/destination"
	}
	for index := range first.Fold.Inputs {
		first.Fold.Inputs[index] = ruleprogram.JoinRef(0)
	}
	if first.Carry != nil {
		first.Carry.Mode = ruleprogram.CarryModeInvalid
	}
	if first.Activation != nil {
		for index := range first.Activation.Transport {
			first.Activation.Transport[index].Exported = !first.Activation.Transport[index].Exported
		}
	}
	if got := emitlaw.Canonical(AllocationResult()); got != allocationResultGeometry {
		t.Fatalf("a caller's edits reached the next declaration:\n%s", got)
	}
}

// allocationResultIdentity is the rule identity this declaration is sealed under.
const allocationResultIdentity = `rule                 value-allocation
lane                 mounted
writes               value
owner                value
semantic             semantic/rule/value/allocation
role[0]              semantic/operand/value/allocation
issue[0]             occurrence=occurrence/allocation form=program-form/local-entry requirement=program-requirement/unrestricted
`

// TestAllocationResultRuleEntryIsTheSealedDeclaration holds the rule entry to its identity, to
// the declaration this suite was emitted from, and to handing out issuance a
// caller owns. An entry that shared its issuance storage would let one reader's
// edit become every later reader's declaration.
func TestAllocationResultRuleEntryIsTheSealedDeclaration(t *testing.T) {
	entry := RuleEntry()
	if got := emitlaw.CanonicalEntry(entry); got != allocationResultIdentity {
		t.Fatalf("rule identity has moved away from its law suite:\ngot:\n%s\nwant:\n%s", got, allocationResultIdentity)
	}
	if got := emitlaw.Canonical(entry.Program); got != allocationResultGeometry {
		t.Fatalf("the entry carries a different declaration than the one it is sealed over:\n%s", got)
	}
	for index := range entry.Issues {
		entry.Issues[index].Occurrence = "law/mutation/occurrence"
		entry.Issues[index].Form = "law/mutation/form"
		entry.Issues[index].Requirement = "law/mutation/requirement"
	}
	for index := range entry.Roles {
		entry.Roles[index] = "law/mutation/role"
	}
	if got := emitlaw.CanonicalEntry(RuleEntry()); got != allocationResultIdentity {
		t.Fatalf("a caller's edits reached the next rule entry:\n%s", got)
	}
}

// TestAllocationResultRefusesEveryStructuralMutation is the negative half of the declaration's
// structure: for every term the cold ABI carries, the edit that removes or
// corrupts it, and the verdict Check gives it. The table is total over the
// declaration rather than a sample of it, which is the whole reason it is
// derived: an authored suite states the three edits its author thought of.
//
// Each verdict is the one this suite's emitter watched Check give while
// deriving. Check runs for real here, so a checker that stops refusing an edit
// fails this law, and a checker that refuses it differently shows up as a
// regeneration diff.
func TestAllocationResultRefusesEveryStructuralMutation(t *testing.T) {
	for _, law := range []struct {
		mutation string
		apply    func(declaration *ruleprogram.Program)
		kind     ruleprogram.ProblemKind
		join     int
		input    int
		output   int
	}{
		{mutation: "the operand role is cleared", apply: func(declaration *ruleprogram.Program) { declaration.OperandRole = "" }, kind: ruleprogram.ProblemOperand},
		{mutation: "the candidate provider is cleared", apply: func(declaration *ruleprogram.Program) { declaration.Candidate = axismember.CandidateRef{} }, kind: ruleprogram.ProblemCandidate},
		{mutation: "the candidate relation loses its member", apply: func(declaration *ruleprogram.Program) { declaration.Candidate.AxisRelation.Member = "" }, kind: ruleprogram.ProblemCandidate},
		{mutation: "the fold names no reducer", apply: func(declaration *ruleprogram.Program) { declaration.Fold.Reducer.Member = "" }, kind: ruleprogram.ProblemFold},
		{mutation: "the fold publishes nothing", apply: func(declaration *ruleprogram.Program) { declaration.Fold.Outputs = nil }, kind: ruleprogram.ProblemOutput},
		{mutation: "output 0 loses its destination projection", apply: func(declaration *ruleprogram.Program) { declaration.Fold.Outputs[0].Destination.Member = "" }, kind: ruleprogram.ProblemOutput},
		{mutation: "output 0 loses its declared column", apply: func(declaration *ruleprogram.Program) { declaration.Fold.Outputs[0].Column.Key = "" }, kind: ruleprogram.ProblemOutput},
		{mutation: "output 0 loses its publication mode", apply: func(declaration *ruleprogram.Program) { declaration.Fold.Outputs[0].Mode = ruleprogram.ModeInvalid }, kind: ruleprogram.ProblemOutput},
		{mutation: "output 0 publishes into a value slot the fold does not have", apply: func(declaration *ruleprogram.Program) { declaration.Fold.Outputs[0].ValueSlot = 1 }, kind: ruleprogram.ProblemOutput},
		{mutation: "output 0 claims a route it does not publish through", apply: func(declaration *ruleprogram.Program) { declaration.Fold.Outputs[0].RouteJoinPresent = true }, kind: ruleprogram.ProblemOutput},
		{mutation: "the carry loses its disposition", apply: func(declaration *ruleprogram.Program) { declaration.Carry.Mode = ruleprogram.CarryModeInvalid }, kind: ruleprogram.ProblemCarry},
		{mutation: "the carry names an input port the declaration does not open", apply: func(declaration *ruleprogram.Program) { declaration.Carry.Input = ruleprogram.InputRef(2) }, kind: ruleprogram.ProblemInput},
		{mutation: "the transforming carry loses its transform", apply: func(declaration *ruleprogram.Program) { declaration.Carry.Transform.Member = "" }, kind: ruleprogram.ProblemCarry},
	} {
		declaration := AllocationResult().Clone()
		law.apply(&declaration)
		problem, valid := declaration.Check()
		if valid {
			t.Fatalf("Check admits a declaration where %s", law.mutation)
		}
		if problem.Kind != law.kind || problem.Join != law.join || problem.Input != law.input || problem.Output != law.output {
			t.Fatalf("where %s, Check refused with %+v", law.mutation, problem)
		}
	}
}
