package outputowners

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"

	"github.com/wippyai/go-lua/analysis/schema"
	"github.com/wippyai/go-lua/analysis/schema/denominator"
)

// Generate rebuilds or checks the cold Program output-owner evidence source.
func Generate(out string, check bool) error {
	evidence, err := Build()
	if err != nil {
		return err
	}
	rendered, err := render(evidence)
	if err != nil {
		return err
	}
	current, readErr := os.ReadFile(out)
	if check {
		if readErr != nil || !bytes.Equal(current, rendered) {
			return fmt.Errorf("program output owners: evidence is stale")
		}
		return nil
	}
	if err := os.WriteFile(out, rendered, 0o644); err != nil {
		return fmt.Errorf("program output owners: write evidence: %w", err)
	}
	return nil
}

func render(e Evidence) ([]byte, error) {
	var out strings.Builder
	out.WriteString("// Code generated by Program output-owner evidence; DO NOT EDIT.\n\npackage outputowners\n\n")
	out.WriteString("import (\n\t\"github.com/wippyai/go-lua/analysis/schema\"\n\t\"github.com/wippyai/go-lua/analysis/schema/denominator\"\n)\n\n")
	fmt.Fprintf(&out, "var Generated = Evidence{\n\t\tDigest: %q,\n\t\tRows: []Row{\n", e.Digest)
	for _, row := range e.Rows {
		out.WriteString("\t\t\t{Relation: ")
		renderID(&out, row.Relation)
		fmt.Fprintf(&out, ", Owner: denominator.RelationOwner(%d)},\n", row.Owner)
	}
	out.WriteString("\t\t},\n\t}\n")
	return format.Source([]byte(out.String()))
}

func renderID(out *strings.Builder, id schema.EntryID) {
	if key, ok := denominatorKey(id); ok {
		fmt.Fprintf(out, "schema.NewEntryID(schema.SurfaceKindDenominator, schema.Key(%q))", key)
		return
	}
	fmt.Fprintf(out, "schema.EntryID{%s}", byteLiteral(id))
}

func denominatorKey(id schema.EntryID) (string, bool) {
	for _, entry := range denominator.GeneratedRelationEntries() {
		if entry.ID() == id {
			return string(entry.Key()), true
		}
	}
	return "", false
}

func byteLiteral(id schema.EntryID) string {
	var out strings.Builder
	for index, value := range id {
		if index != 0 {
			out.WriteString(",")
		}
		fmt.Fprintf(&out, "0x%02x", value)
	}
	return out.String()
}
