// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.

package relation

import (
	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
	"github.com/wippyai/go-lua/analysis/relation/semantic/signature"
	"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"
	placementdomain "github.com/wippyai/go-lua/domain/placement"
	valuedomain "github.com/wippyai/go-lua/domain/value"
)

// PlacementFreshBirthColumns are the owner column codecs of the
// placement/freshbirth binding.
type PlacementFreshBirthColumns struct {
	Value                *relbindgen.Column[valuedomain.Value]
	Placement            *relbindgen.Column[placementdomain.Fact]
	FreshResultCandidate *relbindgen.Column[valuedomain.FreshResultCall]
}

// NewPlacementFreshBirthColumns names this family's own owner columns. A column an axis
// other than this one publishes is handed in, never reached for.
func NewPlacementFreshBirthColumns(value *relbindgen.Column[valuedomain.Value], placement *relbindgen.Column[placementdomain.Fact], freshResultCandidate *relbindgen.Column[valuedomain.FreshResultCall]) (PlacementFreshBirthColumns, bool) {
	columns := PlacementFreshBirthColumns{Value: value, Placement: placement, FreshResultCandidate: freshResultCandidate}
	if !columns.Available() {
		return PlacementFreshBirthColumns{}, false
	}
	return columns, true
}

// Available reports whether every column this binding needs carries an
// owner-issued type and live storage.
func (columns PlacementFreshBirthColumns) Available() bool {
	return columns.Value.Available() && columns.Placement.Available() && columns.FreshResultCandidate.Available()
}

// PlacementFreshBirthArgument is the decoded frame of one
// placement/freshbirth invocation.
type PlacementFreshBirthArgument struct {
	Candidate valuedomain.FreshResultCall
	Result    valuedomain.Value
}

// PlacementFreshBirthJudgment is the owner mathematics this binding carries. The axis
// states it by hand: nothing in this file can name a relation, a cell, a
// buffer or an engine value, so the mathematics stays where its owner wrote
// it and this artifact stays free of it.
type PlacementFreshBirthJudgment interface {
	relbindgen.Operation[PlacementFreshBirthArgument, placementdomain.Fact]
	Available() bool
}

// The hand-authored judgment answers this family's own contract, and the
// assertion is what makes the two halves one binding.
var _ PlacementFreshBirthJudgment = PlacementFreshBirthOperation{}

// BindPlacementFreshBirth admits the placement/freshbirth family
// under its sealed signature.
func BindPlacementFreshBirth(operation signature.Signature, judgment PlacementFreshBirthJudgment, columns PlacementFreshBirthColumns, refusal model.RefusalID) (binding.Factory, bool) {
	if judgment == nil || !judgment.Available() || !columns.Available() {
		return nil, false
	}
	return relbindgen.Bind(relbindgen.Spec[PlacementFreshBirthArgument, placementdomain.Fact]{
		Signature: operation,
		Decoder:   placementFreshBirthDecoder{columns: columns},
		Encoder:   placementFreshBirthEncoder{columns: columns},
		Operation: judgment,
		Refusal:   refusal,
	})
}

type placementFreshBirthDecoder struct {
	columns PlacementFreshBirthColumns
}

func (decoder placementFreshBirthDecoder) Decode(inputs relbindgen.Inputs) (PlacementFreshBirthArgument, bool) {
	candidate, ok := relbindgen.ScalarAt(inputs, 0, decoder.columns.FreshResultCandidate)
	if !ok {
		return PlacementFreshBirthArgument{}, false
	}
	result, ok := relbindgen.ScalarAt(inputs, 1, decoder.columns.Value)
	if !ok {
		return PlacementFreshBirthArgument{}, false
	}
	return PlacementFreshBirthArgument{Candidate: candidate, Result: result}, true
}

type placementFreshBirthEncoder struct {
	columns PlacementFreshBirthColumns
}

func (encoder placementFreshBirthEncoder) Encode(outputs relbindgen.Outputs, value placementdomain.Fact) bool {
	return relbindgen.PutColumn(outputs, 0, encoder.columns.Placement, value)
}
