// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.

package relation

import (
	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
	"github.com/wippyai/go-lua/analysis/relation/semantic/signature"
	"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"
	placementdomain "github.com/wippyai/go-lua/domain/placement"
)

// PlacementReturnEscapeColumns are the owner column codecs of the
// placement/returnescape binding.
type PlacementReturnEscapeColumns struct {
	Placement         *relbindgen.Column[placementdomain.Fact]
	PlacementRouteTag *relbindgen.Column[uint64]
}

// NewPlacementReturnEscapeColumns names this family's own owner columns. A column an axis
// other than this one publishes is handed in, never reached for.
func NewPlacementReturnEscapeColumns(placement *relbindgen.Column[placementdomain.Fact], placementRouteTag *relbindgen.Column[uint64]) (PlacementReturnEscapeColumns, bool) {
	columns := PlacementReturnEscapeColumns{Placement: placement, PlacementRouteTag: placementRouteTag}
	if !columns.Available() {
		return PlacementReturnEscapeColumns{}, false
	}
	return columns, true
}

// Available reports whether every column this binding needs carries an
// owner-issued type and live storage.
func (columns PlacementReturnEscapeColumns) Available() bool {
	return columns.Placement.Available() && columns.PlacementRouteTag.Available()
}

// PlacementReturnEscapeArgument is the decoded frame of one
// placement/returnescape invocation.
type PlacementReturnEscapeArgument struct {
	RouteTag uint64
	Current  placementdomain.Fact
}

// PlacementReturnEscapeJudgment is the owner mathematics this binding carries. The axis
// states it by hand: nothing in this file can name a relation, a cell, a
// buffer or an engine value, so the mathematics stays where its owner wrote
// it and this artifact stays free of it.
type PlacementReturnEscapeJudgment interface {
	relbindgen.Operation[PlacementReturnEscapeArgument, placementdomain.Fact]
	Available() bool
}

// The hand-authored judgment answers this family's own contract, and the
// assertion is what makes the two halves one binding.
var _ PlacementReturnEscapeJudgment = PlacementReturnEscapeOperation{}

// BindPlacementReturnEscape admits the placement/returnescape family
// under its sealed signature.
func BindPlacementReturnEscape(operation signature.Signature, judgment PlacementReturnEscapeJudgment, columns PlacementReturnEscapeColumns, refusal model.RefusalID) (binding.Factory, bool) {
	if judgment == nil || !judgment.Available() || !columns.Available() {
		return nil, false
	}
	return relbindgen.Bind(relbindgen.Spec[PlacementReturnEscapeArgument, placementdomain.Fact]{
		Signature: operation,
		Decoder:   placementReturnEscapeDecoder{columns: columns},
		Encoder:   placementReturnEscapeEncoder{columns: columns},
		Operation: judgment,
		Refusal:   refusal,
	})
}

type placementReturnEscapeDecoder struct {
	columns PlacementReturnEscapeColumns
}

func (decoder placementReturnEscapeDecoder) Decode(inputs relbindgen.Inputs) (PlacementReturnEscapeArgument, bool) {
	routeTag, ok := relbindgen.ScalarAt(inputs, 0, decoder.columns.PlacementRouteTag)
	if !ok {
		return PlacementReturnEscapeArgument{}, false
	}
	current, ok := relbindgen.ScalarAt(inputs, 1, decoder.columns.Placement)
	if !ok {
		return PlacementReturnEscapeArgument{}, false
	}
	return PlacementReturnEscapeArgument{RouteTag: routeTag, Current: current}, true
}

type placementReturnEscapeEncoder struct {
	columns PlacementReturnEscapeColumns
}

func (encoder placementReturnEscapeEncoder) Encode(outputs relbindgen.Outputs, value placementdomain.Fact) bool {
	return relbindgen.PutColumn(outputs, 0, encoder.columns.Placement, value)
}
