// Package parse implements lexical analysis and parsing for Lua source code.
//
// The package provides two main components:
//
// Scanner (lexer): Tokenizes Lua source into a stream of tokens. Handles all
// Lua lexical elements including identifiers, keywords, numbers (decimal and
// hex), strings (single/double quoted and multiline), operators, and comments.
// Also supports type annotation syntax extensions.
//
// Parser: Consumes the token stream and produces an AST. Generated by goyacc
// from parser.go.y, it implements recursive descent parsing for Lua's grammar
// including statements, expressions, and type annotations.
//
// Key entry points:
//
//	Parse(reader, name) - parse from io.Reader
//	ParseString(source, name) - parse from string with enhanced error messages
//
// Errors include position information and can render Rust-style diagnostics
// with source context when the original source is available.
package parse

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"strconv"
	"strings"
	"sync"

	"github.com/wippyai/go-lua/compiler/ast"
)

const EOF = -1
const whitespace1 = 1<<'\t' | 1<<' '
const whitespace2 = 1<<'\t' | 1<<'\n' | 1<<'\r' | 1<<' '

var tokenPool = sync.Pool{
	New: func() interface{} {
		return &ast.Token{}
	},
}

func getToken() *ast.Token {
	tok := tokenPool.Get().(*ast.Token)
	tok.Type = 0
	tok.Name = ""
	tok.Str = ""
	tok.Pos = ast.Position{}
	return tok
}

func putToken(tok *ast.Token) {
	if tok != nil {
		tokenPool.Put(tok)
	}
}

type scanResult int

const (
	scanOK scanResult = iota
	scanRedo
	scanError
)

func (sc *Scanner) scanMinus(tok *ast.Token) (scanResult, error) {
	switch sc.Peek() {
	case '-':
		if err := sc.skipComments(sc.Next()); err != nil {
			return scanError, err
		}
		return scanRedo, nil
	case '>':
		tok.Type = TArrow
		tok.Str = "->"
		sc.Next()
	default:
		tok.Type = '-'
		tok.Str = "-"
	}
	return scanOK, nil
}

func (sc *Scanner) scanDot(tok *ast.Token, buf *bytes.Buffer) error {
	ch2 := sc.Peek()
	switch {
	case isDecimal(ch2):
		tok.Type = TNumber
		if err := sc.scanNumber('.', buf); err != nil {
			return err
		}
		tok.Str = buf.String()
	case ch2 == '.':
		writeChar(buf, '.')
		writeChar(buf, sc.Next())
		if sc.Peek() == '.' {
			writeChar(buf, sc.Next())
			tok.Type = T3Comma
		} else {
			tok.Type = T2Comma
		}
		tok.Str = buf.String()
	default:
		tok.Type = '.'
		tok.Str = "."
	}
	return nil
}

func (sc *Scanner) scanColon(tok *ast.Token) {
	if sc.Peek() == ':' {
		sc.Next()
		if name, ok := sc.tryLabelLookahead(); ok {
			tok.Type = TLabel
			tok.Str = name
		} else {
			tok.Type = T2Colon
			tok.Str = "::"
		}
	} else {
		tok.Type = ':'
		tok.Str = ":"
	}
}

func (sc *Scanner) scanCompare(ch int, tok *ast.Token) {
	switch ch {
	case '=':
		if sc.Peek() == '=' {
			tok.Type = TEqeq
			tok.Str = "=="
			sc.Next()
		} else {
			tok.Type = '='
			tok.Str = "="
		}
	case '~':
		if sc.Peek() == '=' {
			tok.Type = TNeq
			tok.Str = "~="
			sc.Next()
		} else {
			tok.Type = '~'
			tok.Str = "~"
		}
	case '<':
		switch sc.Peek() {
		case '=':
			tok.Type = TLte
			tok.Str = "<="
			sc.Next()
		case '<':
			tok.Type = TShl
			tok.Str = "<<"
			sc.Next()
		default:
			tok.Type = '<'
			tok.Str = "<"
		}
	case '>':
		switch sc.Peek() {
		case '=':
			tok.Type = TGte
			tok.Str = ">="
			sc.Next()
		case '>':
			tok.Type = TShr
			tok.Str = ">>"
			sc.Next()
		default:
			tok.Type = '>'
			tok.Str = ">"
		}
	}
}

// Error represents a parse error with source location.
// When Source is set, Render() produces Rust-style diagnostics with context.
type Error struct {
	Pos     ast.Position
	Message string
	Token   string
	Source  string
}

func (e *Error) Error() string {
	if e.Source != "" {
		return e.Render()
	}
	pos := e.Pos
	if pos.Line == EOF {
		return fmt.Sprintf("%v at EOF: %s", pos.Source, e.Message)
	}
	return fmt.Sprintf("%v:%d:%d: %s", pos.Source, pos.Line, pos.Column, e.Message)
}

func (e *Error) String() string {
	return e.Message
}

// Render formats the error with source context showing the offending line and position.
func (e *Error) Render() string {
	if e.Source == "" {
		return e.Error()
	}

	var b strings.Builder
	lines := strings.Split(e.Source, "\n")

	// Header: error: message
	b.WriteString("error: ")
	b.WriteString(e.Message)
	b.WriteString("\n")

	lineNumStr := strconv.Itoa(e.Pos.Line)
	gutterWidth := len(lineNumStr) + 1

	// Location: --> file:line:col
	b.WriteString(strings.Repeat(" ", gutterWidth))
	b.WriteString("--> ")
	if e.Pos.Source != "" {
		b.WriteString(e.Pos.Source)
		b.WriteString(":")
	}
	b.WriteString(strconv.Itoa(e.Pos.Line))
	b.WriteString(":")
	b.WriteString(strconv.Itoa(e.Pos.Column))
	b.WriteString("\n")

	// Get source line
	line := ""
	if e.Pos.Line >= 1 && e.Pos.Line <= len(lines) {
		line = lines[e.Pos.Line-1]
	}

	if line != "" {
		gutter := strings.Repeat(" ", gutterWidth)

		// Empty line with pipe
		b.WriteString(gutter)
		b.WriteString("|\n")

		// Source line with right-aligned line number
		b.WriteString(fmt.Sprintf("%*d | ", gutterWidth-1, e.Pos.Line))
		b.WriteString(line)
		b.WriteString("\n")

		// Underline
		b.WriteString(gutter)
		b.WriteString("| ")
		col := e.Pos.Column
		if col < 1 {
			col = 1
		}
		if col > len(line)+1 {
			col = len(line) + 1
		}
		b.WriteString(strings.Repeat(" ", col-1))
		b.WriteString("^")
		// Underline the token if we have it
		if e.Token != "" && len(e.Token) > 1 {
			b.WriteString(strings.Repeat("~", len(e.Token)-1))
		}
		b.WriteString("\n")
	}

	return b.String()
}

func writeChar(buf *bytes.Buffer, c int) { buf.WriteByte(byte(c)) }

func isDecimal(ch int) bool { return '0' <= ch && ch <= '9' }

func isIdent(ch int, pos int) bool {
	return ch == '_' || 'A' <= ch && ch <= 'Z' || 'a' <= ch && ch <= 'z' || isDecimal(ch) && pos > 0
}

func isDigit(ch int) bool {
	return '0' <= ch && ch <= '9' || 'a' <= ch && ch <= 'f' || 'A' <= ch && ch <= 'F'
}

// Scanner tokenizes Lua source code into a stream of tokens.
type Scanner struct {
	Pos    ast.Position
	reader *bufio.Reader
}

// NewScanner creates a scanner for the given input with the specified source name.
func NewScanner(reader io.Reader, source string) *Scanner {
	return &Scanner{
		Pos: ast.Position{
			Source: source,
			Line:   1,
			Column: 0,
		},
		reader: bufio.NewReaderSize(reader, 4096),
	}
}

func (sc *Scanner) Error(tok string, msg string) *Error {
	return &Error{Pos: sc.Pos, Message: msg, Token: tok}
}

func (sc *Scanner) TokenError(tok ast.Token, msg string) *Error {
	return &Error{Pos: tok.Pos, Message: msg, Token: tok.Str}
}

func (sc *Scanner) readNext() int {
	ch, err := sc.reader.ReadByte()
	if err == io.EOF {
		return EOF
	}
	return int(ch)
}

func (sc *Scanner) Newline(ch int) {
	if ch < 0 {
		return
	}
	sc.Pos.Line += 1
	sc.Pos.Column = 0
	next := sc.Peek()
	if ch == '\n' && next == '\r' || ch == '\r' && next == '\n' {
		_, _ = sc.reader.ReadByte()
	}
}

func (sc *Scanner) Next() int {
	ch := sc.readNext()
	switch ch {
	case '\n', '\r':
		sc.Newline(ch)
		ch = int('\n')
	case EOF:
		sc.Pos.Line = EOF
		sc.Pos.Column = 0
	default:
		sc.Pos.Column++
	}
	return ch
}

func (sc *Scanner) Peek() int {
	ch := sc.readNext()
	if ch != EOF {
		_ = sc.reader.UnreadByte()
	}
	return ch
}

// tryLabelLookahead attempts to match ::name:: label syntax.
// Returns the label name if matched, consuming the input. Otherwise returns empty
// string without consuming. Called after the opening :: is consumed.
func (sc *Scanner) tryLabelLookahead() (string, bool) {
	data, err := sc.reader.Peek(256)
	if err != nil && len(data) == 0 {
		return "", false
	}

	i := 0
	for i < len(data) && (data[i] == ' ' || data[i] == '\t') {
		i++
	}

	// Must start with letter or underscore (identifier start)
	if i >= len(data) {
		return "", false
	}
	ch := data[i]
	if !isIdent(int(ch), 0) {
		return "", false
	}

	// Collect identifier
	nameStart := i
	for i < len(data) && ((data[i] >= 'a' && data[i] <= 'z') ||
		(data[i] >= 'A' && data[i] <= 'Z') ||
		(data[i] >= '0' && data[i] <= '9') ||
		data[i] == '_') {
		i++
	}
	name := string(data[nameStart:i])

	// Skip trailing whitespace
	for i < len(data) && (data[i] == ' ' || data[i] == '\t') {
		i++
	}

	// Must end with ::
	if i+1 >= len(data) || data[i] != ':' || data[i+1] != ':' {
		return "", false
	}
	i += 2

	_, _ = sc.reader.Discard(i)
	sc.Pos.Column += i

	return name, true
}

func (sc *Scanner) skipWhiteSpace(whitespace int64) int {
	ch := sc.Next()
	for ; ch >= 0 && ch < 64 && whitespace&(1<<uint(ch)) != 0; ch = sc.Next() {
	}
	return ch
}

func (sc *Scanner) skipComments(ch int) error {
	// multiline comment
	if sc.Peek() == '[' {
		ch = sc.Next()
		if sc.Peek() == '[' || sc.Peek() == '=' {
			var buf bytes.Buffer
			if err := sc.scanMultilineString(sc.Next(), &buf); err != nil {
				return sc.Error(buf.String(), "invalid multiline comment")
			}
			return nil
		}
	}
	for ch != '\n' && ch != '\r' && ch >= 0 {
		ch = sc.Next()
	}
	return nil
}

func (sc *Scanner) scanIdent(ch int, buf *bytes.Buffer) {
	writeChar(buf, ch)
	for isIdent(sc.Peek(), 1) {
		writeChar(buf, sc.Next())
	}
}

func (sc *Scanner) scanDecimal(ch int, buf *bytes.Buffer) {
	writeChar(buf, ch)
	for isDecimal(sc.Peek()) {
		writeChar(buf, sc.Next())
	}
}

func (sc *Scanner) scanNumber(ch int, buf *bytes.Buffer) error {
	if ch == '0' { // octal
		if sc.Peek() == 'x' || sc.Peek() == 'X' {
			writeChar(buf, ch)
			writeChar(buf, sc.Next())
			hasvalue := false
			for isDigit(sc.Peek()) {
				writeChar(buf, sc.Next())
				hasvalue = true
			}
			if !hasvalue {
				return sc.Error(buf.String(), "illegal hexadecimal number")
			}
			return nil
		} else if sc.Peek() != '.' && isDecimal(sc.Peek()) {
			ch = sc.Next()
		}
	}
	sc.scanDecimal(ch, buf)
	if sc.Peek() == '.' {
		sc.scanDecimal(sc.Next(), buf)
	}
	if ch = sc.Peek(); ch == 'e' || ch == 'E' {
		writeChar(buf, sc.Next())
		if ch = sc.Peek(); ch == '-' || ch == '+' {
			writeChar(buf, sc.Next())
		}
		if !isDecimal(sc.Peek()) {
			return sc.Error(buf.String(), "malformed exponent")
		}
		sc.scanDecimal(sc.Next(), buf)
	}

	return nil
}

func (sc *Scanner) scanString(quote int, buf *bytes.Buffer) error {
	ch := sc.Next()
	for ch != quote {
		if ch == '\n' || ch == '\r' || ch < 0 {
			return sc.Error(buf.String(), "unterminated string")
		}
		if ch == '\\' {
			if err := sc.scanEscape(ch, buf); err != nil {
				return err
			}
		} else {
			writeChar(buf, ch)
		}
		ch = sc.Next()
	}
	return nil
}

func (sc *Scanner) scanEscape(_ int, buf *bytes.Buffer) error {
	ch := sc.Next()
	switch ch {
	case 'a':
		buf.WriteByte('\a')
	case 'b':
		buf.WriteByte('\b')
	case 'f':
		buf.WriteByte('\f')
	case 'n':
		buf.WriteByte('\n')
	case 'r':
		buf.WriteByte('\r')
	case 't':
		buf.WriteByte('\t')
	case 'v':
		buf.WriteByte('\v')
	case '\\':
		buf.WriteByte('\\')
	case '"':
		buf.WriteByte('"')
	case '\'':
		buf.WriteByte('\'')
	case '\n':
		buf.WriteByte('\n')
	case '\r':
		buf.WriteByte('\n')
		sc.Newline('\r')
	default:
		if '0' <= ch && ch <= '9' {
			digits := []byte{byte(ch)}
			for i := 0; i < 2 && isDecimal(sc.Peek()); i++ {
				digits = append(digits, byte(sc.Next()))
			}
			val, _ := strconv.ParseInt(string(digits), 10, 32)
			if val > 255 {
				return sc.Error(string(digits), "decimal escape too large")
			}
			writeChar(buf, int(val))
		} else {
			writeChar(buf, ch)
		}
	}
	return nil
}

func (sc *Scanner) countSep(ch int) (int, int) {
	count := 0
	for ; ch == '='; count++ {
		ch = sc.Next()
	}
	return count, ch
}

func (sc *Scanner) scanMultilineString(ch int, buf *bytes.Buffer) error {
	var count1, count2 int
	count1, ch = sc.countSep(ch)
	if ch != '[' {
		return sc.Error(string(rune(ch)), "invalid multiline string")
	}
	ch = sc.Next()
	if ch == '\n' || ch == '\r' {
		ch = sc.Next()
	}
	for {
		if ch < 0 {
			return sc.Error(buf.String(), "unterminated multiline string")
		} else if ch == ']' {
			count2, ch = sc.countSep(sc.Next())
			if count1 == count2 && ch == ']' {
				goto finally
			}
			buf.WriteByte(']')
			buf.WriteString(strings.Repeat("=", count2))
			continue
		}
		writeChar(buf, ch)
		ch = sc.Next()
	}

finally:
	return nil
}

func (sc *Scanner) scanSlash(tok *ast.Token) {
	if sc.Peek() == '/' {
		tok.Type = TIdiv
		tok.Str = "//"
		sc.Next()
	} else {
		tok.Type = '/'
		tok.Str = "/"
	}
}

func (sc *Scanner) scanQuestion(tok *ast.Token) {
	if sc.Peek() == ':' {
		sc.Next()
		tok.Type = TQuestionColon
		tok.Str = "?:"
	} else {
		tok.Type = TQuestion
		tok.Str = "?"
	}
}

func (sc *Scanner) scanBracket(tok *ast.Token, buf *bytes.Buffer) error {
	if c := sc.Peek(); c == '[' || c == '=' {
		tok.Type = TString
		if err := sc.scanMultilineString(sc.Next(), buf); err != nil {
			return err
		}
		tok.Str = buf.String()
	} else {
		tok.Type = '['
		tok.Str = "["
	}
	return nil
}

var reservedWords = map[string]int{
	"and": TAnd, "break": TBreak, "do": TDo, "else": TElse, "elseif": TElseIf,
	"end": TEnd, "false": TFalse, "for": TFor, "function": TFunction, "fun": TFun,
	"if": TIf, "in": TIn, "local": TLocal, "nil": TNil, "not": TNot, "or": TOr,
	"return": TReturn, "repeat": TRepeat, "then": TThen, "true": TTrue,
	"until": TUntil, "while": TWhile, "goto": TGoto,
	"interface": TInterface, "as": TAs, "asserts": TAsserts, "readonly": TReadonly, "is": TIs, "typeof": TTypeof,
	"keyof": TKeyof, "extends": TExtends,
}

var friendlyTokenNames = map[string]string{
	"TAnd": "'and'", "TBreak": "'break'", "TDo": "'do'", "TElse": "'else'",
	"TElseIf": "'elseif'", "TEnd": "'end'", "TFalse": "'false'", "TFor": "'for'",
	"TFunction": "'function'", "TIf": "'if'", "TIn": "'in'", "TLocal": "'local'",
	"TNil": "'nil'", "TNot": "'not'", "TOr": "'or'", "TReturn": "'return'",
	"TRepeat": "'repeat'", "TThen": "'then'", "TTrue": "'true'", "TUntil": "'until'",
	"TWhile": "'while'", "TGoto": "'goto'",
	"TType": "'type'", "TInterface": "'interface'", "TReadonly": "'readonly'", "TAs": "'as'",
	"TAsserts": "'asserts'", "TIs": "'is'", "TTypeof": "'typeof'", "TKeyof": "'keyof'", "TExtends": "'extends'",
	"TFun":  "'fun'",
	"TEqeq": "'=='", "TNeq": "'~='", "TLte": "'<='", "TGte": "'>='",
	"T2Comma": "'..'", "T3Comma": "'...'", "T2Colon": "'::'", "TLabel": "label",
	"TShl": "'<<'", "TShr": "'>>'", "TIdiv": "'//'",
	"TArrow": "'->'", "TQuestion": "'?'", "TBang": "'!'", "TQuestionColon": "'?:'",
	"TIdent": "identifier", "TNumber": "number", "TString": "string",
}

// FriendlyTokenName converts a token type to a human-readable name for error messages.
func FriendlyTokenName(c int) string {
	name := yyTokname(c)
	if friendly, ok := friendlyTokenNames[name]; ok {
		return friendly
	}
	if len(name) == 3 && name[0] == '\'' && name[2] == '\'' {
		return name
	}
	return name
}

// Scan reads and returns the next token from the input.
func (sc *Scanner) Scan(lexer *Lexer) (ast.Token, error) {
redo:
	var err error
	tok := getToken() // Get pooled token instead of creating new one
	newline := false

	ch := sc.skipWhiteSpace(whitespace1)
	if ch == '\n' || ch == '\r' {
		newline = true
		ch = sc.skipWhiteSpace(whitespace2)
	}

	if ch == '(' && lexer.PrevTokenType == ')' {
		lexer.PNewLine = newline
	} else {
		lexer.PNewLine = false
	}

	var _buf bytes.Buffer
	buf := &_buf
	tok.Pos = sc.Pos

	switch {
	case isIdent(ch, 0):
		tok.Type = TIdent
		sc.scanIdent(ch, buf)
		tok.Str = buf.String()
		if typ, ok := reservedWords[tok.Str]; ok {
			tok.Type = typ
		}
	case isDecimal(ch):
		tok.Type = TNumber
		err = sc.scanNumber(ch, buf)
		tok.Str = buf.String()
	default:
		switch ch {
		case EOF:
			tok.Type = EOF
		case '-':
			var result scanResult
			result, err = sc.scanMinus(tok)
			if err != nil {
				goto finally
			}
			if result == scanRedo {
				putToken(tok)
				goto redo
			}
		case '"', '\'':
			tok.Type = TString
			err = sc.scanString(ch, buf)
			tok.Str = buf.String()
		case '[':
			err = sc.scanBracket(tok, buf)
		case '=', '~', '<', '>':
			sc.scanCompare(ch, tok)
		case '.':
			err = sc.scanDot(tok, buf)
		case ':':
			sc.scanColon(tok)
		case '/':
			sc.scanSlash(tok)
		case '+', '*', '%', '^', '#', '(', ')', '{', '}', ']', ';', ',', '&', '|', '@':
			tok.Type = ch
			tok.Str = string(rune(ch))
		case '?':
			sc.scanQuestion(tok)
		case '!':
			tok.Type = TBang
			tok.Str = "!"
		default:
			writeChar(buf, ch)
			err = sc.Error(buf.String(), "Invalid token")
			goto finally
		}
	}

finally:
	tok.Pos.EndLine = sc.Pos.Line
	tok.Pos.EndColumn = sc.Pos.Column
	tok.Name = TokenName(tok.Type)

	// Return a value copy, not the pooled pointer
	result := *tok
	putToken(tok) // Return pooled token
	return result, err
}

// Lexer implements the yyLexer interface for goyacc.
type Lexer struct {
	scanner       *Scanner
	Stmts         []ast.Stmt
	PNewLine      bool
	Token         ast.Token
	PrevTokenType int
	PendingGT     *ast.Token // Pending '>' from split '>>'
}

func (lx *Lexer) Lex(lval *yySymType) int {
	// Check for pending '>' from split '>>'
	if lx.PendingGT != nil {
		tok := lx.PendingGT
		lx.PendingGT = nil
		lval.token = *tok
		lx.Token = *tok
		return '>'
	}

	lx.PrevTokenType = lx.Token.Type
	tok, err := lx.scanner.Scan(lx)
	if err != nil {
		panic(err)
	}
	if tok.Type < 0 {
		return 0
	}
	lval.token = tok
	lx.Token = tok
	return tok.Type
}

func (lx *Lexer) Error(message string) {
	panic(lx.scanner.Error(lx.Token.Str, message))
}

func (lx *Lexer) TokenError(tok ast.Token, message string) {
	panic(lx.scanner.TokenError(tok, message))
}

// Parse reads Lua source from reader and returns the parsed statement list.
func Parse(reader io.Reader, name string) (chunk []ast.Stmt, err error) {
	lexer := &Lexer{NewScanner(reader, name), nil, false, ast.Token{Str: ""}, TNil, nil}
	defer func() {
		if e := recover(); e != nil {
			err, _ = e.(error)
		}
	}()
	yyParse(lexer)
	chunk = lexer.Stmts
	return
}

// ParseString parses Lua source from a string.
// Errors include source context for enhanced diagnostic rendering.
func ParseString(source, name string) (chunk []ast.Stmt, err error) {
	lexer := &Lexer{NewScanner(strings.NewReader(source), name), nil, false, ast.Token{Str: ""}, TNil, nil}
	defer func() {
		if e := recover(); e != nil {
			if parseErr, ok := e.(*Error); ok {
				parseErr.Source = source
				err = parseErr
			} else {
				err, _ = e.(error)
			}
		}
	}()
	yyParse(lexer)
	chunk = lexer.Stmts
	return
}
