// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package parse

import __yyfmt__ "fmt"

//line parser.go.y:2

import (
	"github.com/wippyai/go-lua/compiler/ast"
	"github.com/wippyai/go-lua/compiler/parse/numparse"
)

// parenthesizedType closes a parenthesized type. Parentheses around a type and
// the parameter list of a function type are the same token sequence, so both
// reduce through funcparamlist and the arrow that follows decides which one was
// written. Without an arrow the parentheses group exactly one type, so a
// parameter name, a variadic marker, or a second entry is a parameter list with
// no function type to belong to.
func parenthesizedType(yylex yyLexer, params functionTypeParams, open, close ast.Token) ast.TypeExpr {
	if params.Variadic == nil && len(params.Params) == 1 && params.Params[0].Name == "" && params.Params[0].Type != nil {
		typ := params.Params[0].Type
		typ.SetPosFromToken(open.Pos)
		typ.SetLastPosFromToken(close.Pos)
		return typ
	}
	yylex.(*Lexer).TokenError(open, "parameter list is not a type: expected -> after )")
	return &ast.PrimitiveTypeExpr{Name: "unknown"}
}

// functionTypeParams is parser-only assembly for a function-type parameter
// list. The AST retains fixed parameters and the optional variadic tail in
// their distinct semantic fields; no parameter-name sentinel represents `...`.
type functionTypeParams struct {
	Params           []ast.FunctionParamExpr
	Variadic         ast.TypeExpr
	VariadicPosition ast.Position
}

func functionType(params functionTypeParams, returns []ast.TypeExpr) *ast.FunctionTypeExpr {
	return &ast.FunctionTypeExpr{
		Params:           params.Params,
		Variadic:         params.Variadic,
		VariadicPosition: params.VariadicPosition,
		Returns:          returns,
	}
}

func appendFunctionTypeParam(yylex yyLexer, params functionTypeParams, param ast.FunctionParamExpr) functionTypeParams {
	if params.Variadic != nil {
		yylex.(*Lexer).TokenError(ast.Token{Str: "...", Pos: params.VariadicPosition}, "variadic function type parameter must be terminal")
	}
	params.Params = append(params.Params, param)
	return params
}

func setFunctionTypeVariadic(yylex yyLexer, params functionTypeParams, marker ast.Token, typ ast.TypeExpr) functionTypeParams {
	if params.Variadic != nil {
		yylex.(*Lexer).TokenError(marker, "function type has more than one variadic parameter")
	}
	params.Variadic = typ
	params.VariadicPosition = marker.Pos
	return params
}

func callExpr(callee, receiver ast.Expr, method ast.Token, typeArgs []ast.TypeExpr, args callArguments) ast.Expr {
	call := &ast.FuncCallExpr{
		Func: callee, Receiver: receiver,
		Method: method.Str, MethodPosition: method.Pos,
		TypeArgs: typeArgs, Args: args.values,
	}
	if receiver != nil {
		call.CopyPos(receiver)
	} else {
		call.CopyPos(callee)
	}
	call.SetLastPosFromToken(args.end)
	return call
}

func positionAtEnd(node ast.PositionHolder) ast.Position {
	return ast.Position{Line: node.LastLine(), Column: node.LastColumn()}
}

func typeReference(name ast.Token) *ast.TypeRefExpr {
	ref := &ast.TypeRefExpr{Path: []string{name.Str}, RootPosition: name.Pos}
	ref.SetPosFromToken(name.Pos)
	ref.SetLastPosFromToken(name.Pos)
	return ref
}

func qualifyTypeReference(ref *ast.TypeRefExpr, name ast.Token) *ast.TypeRefExpr {
	ref.Path = append(ref.Path, name.Str)
	ref.SetLastPosFromToken(name.Pos)
	return ref
}

func genericTypeReference(base *ast.TypeRefExpr, args []ast.TypeExpr, close ast.Token) *ast.GenericTypeExpr {
	generic := &ast.GenericTypeExpr{Base: base, Args: args}
	generic.CopyPos(base)
	generic.SetLastPosFromToken(close.Pos)
	return generic
}

// annotationExpr keeps the authored annotation range intact.  Its span begins
// at @ and ends at either the name or the closing parenthesis, rather than at
// an argument expression.
func annotationExpr(at, name, end ast.Token, args []ast.Expr) ast.AnnotationExpr {
	annotation := ast.AnnotationExpr{Name: name.Str, Args: args}
	annotation.SetPosFromToken(at.Pos)
	annotation.SetLastPosFromToken(end.Pos)
	return annotation
}

func annotationToken(annotation ast.AnnotationExpr, file string) ast.Token {
	return ast.Token{
		Str: "@" + annotation.Name,
		Pos: ast.Position{
			File:      file,
			Line:      annotation.Line(),
			Column:    annotation.Column(),
			EndLine:   annotation.LastLine(),
			EndColumn: annotation.LastColumn(),
		},
	}
}

func annotatedType(typ ast.TypeExpr, annotations []ast.AnnotationExpr) ast.TypeExpr {
	if len(annotations) == 0 {
		return typ
	}
	result := &ast.AnnotatedTypeExpr{Inner: typ, Annotations: annotations}
	result.CopyPos(typ)
	result.CopyLastPos(&annotations[len(annotations)-1])
	return result
}

func annotationError(yylex yyLexer, annotation ast.AnnotationExpr) {
	lexer := yylex.(*Lexer)
	lexer.TokenError(annotationToken(annotation, lexer.scanner.Pos.File), "annotations are only supported on primitive types and arrays")
}

// annotateDirectType owns ordinary postfix annotation policy. The narrow
// accepted set is intentional: unsupported source remains rejected rather
// than silently extending the language with a new annotation surface.
func annotateDirectType(yylex yyLexer, typ ast.TypeExpr, annotations []ast.AnnotationExpr) ast.TypeExpr {
	switch typ.(type) {
	case *ast.PrimitiveTypeExpr, *ast.ArrayTypeExpr:
		return annotatedType(typ, annotations)
	default:
		if len(annotations) != 0 {
			annotationError(yylex, annotations[0])
		}
		return typ
	}
}

// annotateFieldType keeps the pre-existing optional-tail surface while making
// the type expression itself, rather than its containing field, the owner.
func annotateFieldType(yylex yyLexer, typ ast.TypeExpr, annotations []ast.AnnotationExpr) ast.TypeExpr {
	if _, ok := typ.(*ast.OptionalTypeExpr); ok {
		return annotatedType(typ, annotations)
	}
	if len(annotations) != 0 {
		annotationError(yylex, annotations[0])
	}
	return typ
}

type returnTypeAnnotation struct {
	types []ast.TypeExpr
	known bool
	end   ast.Position
}

type callArguments struct {
	values []ast.Expr
	end    ast.Position
}

type interfaceBody struct {
	members []ast.InterfaceMember
}

//line parser.go.y:236
type yySymType struct {
	yys   int
	token ast.Token

	stmts []ast.Stmt
	stmt  ast.Stmt

	funcname *ast.FuncName
	funcexpr *ast.FunctionExpr

	exprlist []ast.Expr
	expr     ast.Expr

	fieldlist []*ast.Field
	field     *ast.Field
	fieldsep  string

	namelist []nameWithPos
	parlist  *ast.ParList

	typeexpr       ast.TypeExpr
	typeexprlist   []ast.TypeExpr
	callargs       callArguments
	returntype     returnTypeAnnotation
	typeparam      ast.TypeParamExpr
	typeparams     []ast.TypeParamExpr
	recordfield    ast.RecordFieldExpr
	recordfields   []ast.RecordFieldExpr
	typedname      typedNameEntry
	typednames     []typedNameEntry
	ifacemember    ast.InterfaceMember
	interfacebody  interfaceBody
	typereflist    []*ast.TypeRefExpr
	typeref        *ast.TypeRefExpr
	funcparam      ast.FunctionParamExpr
	functionparams functionTypeParams
	annotation     ast.AnnotationExpr
	annotations    []ast.AnnotationExpr
}

const TAnd = 57346
const TBreak = 57347
const TDo = 57348
const TElse = 57349
const TElseIf = 57350
const TEnd = 57351
const TFalse = 57352
const TFor = 57353
const TFunction = 57354
const TIf = 57355
const TIn = 57356
const TLocal = 57357
const TNil = 57358
const TNot = 57359
const TOr = 57360
const TReturn = 57361
const TRepeat = 57362
const TThen = 57363
const TTrue = 57364
const TUntil = 57365
const TWhile = 57366
const TGoto = 57367
const TAssertsRefinement = 57368
const TInterface = 57369
const TReadonly = 57370
const TAs = 57371
const TAsserts = 57372
const TIs = 57373
const TTypeof = 57374
const TKeyof = 57375
const TExtends = 57376
const TFun = 57377
const TEqeq = 57378
const TNeq = 57379
const TLte = 57380
const TGte = 57381
const T2Comma = 57382
const T3Comma = 57383
const T2Colon = 57384
const TTypeArgsOpen = 57385
const TLabel = 57386
const TIdent = 57387
const TNumber = 57388
const TString = 57389
const TShl = 57390
const TShr = 57391
const TIdiv = 57392
const TArrow = 57393
const TQuestion = 57394
const TBang = 57395
const TQuestionColon = 57396
const UNARY = 57397
const TAnnotationTail = 57398
const TAssertsBare = 57399

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"TAnd",
	"TBreak",
	"TDo",
	"TElse",
	"TElseIf",
	"TEnd",
	"TFalse",
	"TFor",
	"TFunction",
	"TIf",
	"TIn",
	"TLocal",
	"TNil",
	"TNot",
	"TOr",
	"TReturn",
	"TRepeat",
	"TThen",
	"TTrue",
	"TUntil",
	"TWhile",
	"TGoto",
	"TAssertsRefinement",
	"TInterface",
	"TReadonly",
	"TAs",
	"TAsserts",
	"TIs",
	"TTypeof",
	"TKeyof",
	"TExtends",
	"TFun",
	"TEqeq",
	"TNeq",
	"TLte",
	"TGte",
	"T2Comma",
	"T3Comma",
	"T2Colon",
	"TTypeArgsOpen",
	"TLabel",
	"TIdent",
	"TNumber",
	"TString",
	"'@'",
	"'{'",
	"'}'",
	"'('",
	"')'",
	"'>'",
	"TShl",
	"TShr",
	"TIdiv",
	"'['",
	"']'",
	"TArrow",
	"TQuestion",
	"TBang",
	"TQuestionColon",
	"'<'",
	"'|'",
	"'~'",
	"'&'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARY",
	"'^'",
	"TAnnotationTail",
	"TAssertsBare",
	"';'",
	"'='",
	"','",
	"':'",
	"'.'",
	"'#'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:1529

// nameWithPos holds a name with its token position
type nameWithPos struct {
	Name string
	Pos  ast.Position
}

// splitNameList extracts names and positions from nameWithPos entries
func splitNameList(entries []nameWithPos) ([]string, []ast.Position) {
	names := make([]string, len(entries))
	positions := make([]ast.Position, len(entries))
	for i, e := range entries {
		names[i] = e.Name
		positions[i] = e.Pos
	}
	return names, positions
}

// typedNameEntry holds a name with optional type annotation
type typedNameEntry struct {
	Name string
	Pos  ast.Position
	Type ast.TypeExpr
}

// splitTypedNames extracts names, positions, and types from typed name entries
func splitTypedNames(entries []typedNameEntry) ([]string, []ast.Position, []ast.TypeExpr) {
	names := make([]string, len(entries))
	positions := make([]ast.Position, len(entries))
	var types []ast.TypeExpr
	hasTypes := false
	for i, e := range entries {
		names[i] = e.Name
		positions[i] = e.Pos
		if e.Type != nil {
			hasTypes = true
		}
	}
	if hasTypes {
		types = make([]ast.TypeExpr, len(entries))
		for i, e := range entries {
			types[i] = e.Type
		}
	}
	return names, positions, types
}

// toFuncParams converts typedNameEntry slice to FunctionParamExpr slice
func toFuncParams(entries []typedNameEntry) []ast.FunctionParamExpr {
	params := make([]ast.FunctionParamExpr, len(entries))
	for i, e := range entries {
		params[i] = ast.FunctionParamExpr{Name: e.Name, NamePosition: e.Pos, Type: e.Type}
	}
	return params
}

func TokenName(c int) string {
	if c >= TAnd && c-TAnd < len(yyToknames) {
		if yyToknames[c-TAnd] != "" {
			return yyToknames[c-TAnd]
		}
	}
	return string([]byte{byte(c)})
}

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 21,
	77, 36,
	78, 36,
	-2, 88,
	-1, 115,
	77, 120,
	-2, 38,
	-1, 124,
	77, 37,
	78, 37,
	-2, 88,
	-1, 246,
	62, 128,
	79, 128,
	-2, 161,
}

const yyPrivate = 57344

const yyLast = 1794

var yyAct = [...]int16{
	144, 287, 410, 107, 209, 57, 234, 232, 134, 257,
	369, 212, 143, 224, 69, 244, 283, 26, 60, 153,
	242, 68, 111, 255, 145, 206, 51, 36, 105, 27,
	236, 170, 171, 50, 239, 236, 237, 54, 35, 318,
	228, 59, 229, 61, 238, 56, 323, 237, 55, 43,
	288, 44, 237, 53, 74, 428, 317, 467, 228, 48,
	229, 239, 54, 228, 123, 229, 214, 101, 102, 103,
	104, 142, 435, 55, 114, 463, 177, 424, 126, 54,
	440, 52, 49, 174, 167, 133, 412, 404, 397, 379,
	55, 295, 217, 169, 216, 343, 289, 179, 175, 204,
	205, 434, 225, 226, 462, 227, 182, 183, 184, 185,
	186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
	196, 197, 198, 199, 200, 201, 202, 203, 225, 293,
	225, 455, 450, 433, 429, 383, 76, 380, 173, 174,
	378, 46, 47, 219, 319, 290, 315, 282, 168, 223,
	360, 280, 218, 54, 294, 240, 260, 434, 434, 434,
	76, 222, 54, 316, 55, 316, 320, 76, 221, 267,
	320, 269, 166, 55, 316, 76, 278, 279, 25, 273,
	228, 108, 229, 108, 98, 271, 29, 230, 41, 277,
	106, 276, 28, 38, 268, 176, 270, 99, 30, 285,
	361, 275, 108, 116, 117, 118, 119, 120, 231, 121,
	122, 321, 415, 231, 235, 464, 100, 32, 228, 372,
	229, 115, 31, 43, 356, 44, 300, 24, 91, 228,
	228, 229, 229, 113, 307, 362, 291, 286, 296, 305,
	70, 40, 314, 181, 37, 114, 386, 460, 297, 309,
	54, 311, 449, 301, 302, 303, 299, 39, 228, 322,
	229, 55, 260, 381, 334, 367, 228, 339, 229, 445,
	363, 228, 364, 229, 45, 313, 228, 228, 229, 229,
	24, 344, 266, 326, 336, 324, 265, 261, 350, 228,
	354, 229, 210, 351, 357, 338, 359, 346, 235, 349,
	263, 352, 285, 262, 235, 277, 358, 304, 329, 330,
	252, 331, 253, 333, 332, 254, 208, 213, 370, 370,
	70, 260, 376, 365, 377, 366, 328, 292, 235, 371,
	373, 327, 368, 284, 264, 56, 382, 233, 384, 43,
	43, 44, 44, 53, 53, 7, 10, 34, 67, 391,
	9, 14, 15, 13, 396, 16, 393, 392, 398, 6,
	12, 312, 401, 399, 11, 18, 208, 20, 310, 308,
	70, 70, 390, 407, 274, 408, 411, 207, 405, 272,
	413, 70, 403, 42, 17, 19, 21, 172, 355, 73,
	400, 24, 70, 72, 416, 125, 422, 71, 425, 66,
	62, 337, 23, 164, 426, 430, 468, 411, 458, 431,
	447, 441, 305, 436, 427, 411, 5, 439, 423, 417,
	388, 389, 387, 420, 443, 394, 340, 75, 162, 448,
	178, 124, 58, 1, 347, 451, 452, 446, 411, 281,
	454, 456, 78, 211, 418, 421, 146, 245, 457, 444,
	461, 112, 215, 110, 33, 22, 77, 63, 8, 65,
	64, 3, 466, 341, 4, 465, 2, 98, 0, 469,
	0, 0, 0, 0, 83, 84, 82, 81, 85, 0,
	99, 0, 329, 330, 252, 331, 253, 333, 332, 254,
	0, 79, 95, 96, 97, 0, 0, 0, 0, 100,
	328, 80, 93, 94, 92, 86, 87, 88, 89, 90,
	0, 91, 29, 0, 41, 0, 419, 0, 28, 38,
	0, 0, 0, 0, 30, 0, 0, 0, 0, 116,
	117, 118, 119, 120, 0, 121, 122, 0, 0, 0,
	78, 0, 0, 32, 0, 0, 0, 115, 31, 43,
	0, 44, 109, 24, 77, 0, 0, 0, 0, 113,
	0, 0, 0, 0, 0, 98, 0, 40, 0, 0,
	37, 0, 83, 84, 82, 81, 85, 0, 99, 0,
	0, 0, 0, 39, 0, 0, 0, 0, 0, 79,
	95, 96, 97, 0, 78, 0, 459, 100, 0, 80,
	93, 94, 92, 86, 87, 88, 89, 90, 77, 91,
	0, 0, 0, 0, 342, 0, 0, 0, 0, 98,
	136, 137, 138, 139, 140, 0, 83, 84, 82, 81,
	85, 0, 99, 0, 0, 29, 0, 41, 135, 0,
	0, 28, 38, 79, 95, 96, 97, 30, 78, 0,
	0, 100, 0, 80, 93, 94, 92, 86, 87, 88,
	89, 90, 77, 91, 0, 442, 32, 0, 0, 0,
	45, 31, 43, 98, 44, 0, 24, 402, 0, 0,
	83, 84, 82, 81, 85, 0, 99, 0, 0, 29,
	40, 41, 0, 37, 0, 28, 38, 79, 95, 96,
	97, 30, 78, 0, 0, 100, 39, 80, 93, 94,
	92, 86, 87, 88, 89, 90, 77, 91, 0, 0,
	32, 0, 0, 0, 45, 31, 43, 98, 44, 0,
	24, 141, 0, 0, 83, 84, 82, 81, 85, 0,
	99, 0, 0, 0, 40, 0, 0, 37, 0, 0,
	385, 79, 95, 96, 97, 0, 78, 0, 0, 100,
	39, 80, 93, 94, 92, 86, 87, 88, 89, 90,
	77, 91, 0, 0, 0, 128, 129, 130, 131, 132,
	0, 98, 0, 0, 0, 0, 0, 0, 83, 84,
	82, 81, 85, 127, 99, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 79, 95, 96, 97, 0,
	298, 0, 78, 100, 0, 80, 93, 94, 92, 86,
	87, 88, 89, 90, 0, 91, 77, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 98, 0, 0,
	0, 0, 0, 0, 83, 84, 82, 81, 85, 0,
	99, 0, 0, 29, 0, 41, 0, 0, 0, 28,
	38, 79, 95, 96, 97, 30, 220, 0, 78, 100,
	0, 80, 93, 94, 92, 86, 87, 88, 89, 90,
	0, 91, 77, 0, 32, 0, 0, 0, 45, 31,
	43, 0, 44, 98, 24, 0, 0, 0, 0, 0,
	83, 84, 82, 81, 85, 0, 99, 0, 40, 0,
	0, 37, 0, 0, 0, 0, 180, 79, 95, 96,
	97, 0, 78, 0, 39, 100, 0, 80, 93, 94,
	92, 86, 87, 88, 89, 90, 77, 91, 0, 165,
	0, 0, 0, 0, 0, 0, 0, 98, 0, 0,
	0, 0, 0, 0, 83, 84, 82, 81, 85, 0,
	99, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 79, 95, 96, 97, 0, 78, 0, 163, 100,
	0, 80, 93, 94, 92, 86, 87, 88, 89, 90,
	77, 91, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 98, 0, 0, 0, 0, 0, 0, 83, 84,
	82, 81, 85, 0, 99, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 79, 95, 96, 97, 0,
	78, 0, 0, 100, 0, 80, 93, 94, 92, 86,
	87, 88, 89, 90, 77, 91, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 98, 0, 0, 0, 0,
	0, 0, 83, 84, 82, 81, 85, 0, 99, 0,
	0, 0, 0, 78, 0, 0, 0, 0, 0, 79,
	95, 96, 97, 0, 0, 0, 0, 100, 0, 80,
	93, 94, 92, 86, 87, 88, 89, 90, 98, 91,
	0, 0, 0, 0, 0, 83, 84, 82, 81, 85,
	0, 99, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 79, 95, 96, 97, 0, 0, 0, 0,
	100, 0, 80, 93, 94, 92, 86, 87, 88, 89,
	90, 98, 91, 0, 0, 0, 0, 0, 83, 84,
	82, 81, 85, 0, 99, 0, 0, 0, 0, 0,
	0, 98, 0, 0, 0, 79, 95, 96, 97, 0,
	0, 0, 85, 100, 99, 80, 93, 94, 92, 86,
	87, 88, 89, 90, 0, 91, 95, 96, 97, 0,
	0, 0, 0, 100, 0, 98, 93, 94, 92, 86,
	87, 88, 89, 90, 0, 91, 85, 0, 99, 0,
	0, 0, 0, 0, 0, 98, 0, 0, 0, 0,
	95, 96, 97, 0, 0, 0, 85, 100, 99, 0,
	0, 94, 92, 86, 87, 88, 89, 90, 98, 91,
	95, 96, 97, 0, 0, 0, 0, 100, 0, 85,
	0, 99, 92, 86, 87, 88, 89, 90, 98, 91,
	0, 0, 0, 95, 96, 97, 0, 0, 0, 85,
	100, 99, 0, 0, 98, 0, 86, 87, 88, 89,
	90, 0, 91, 0, 0, 97, 0, 99, 0, 0,
	100, 0, 0, 0, 0, 0, 86, 87, 88, 89,
	90, 97, 91, 0, 0, 149, 100, 0, 0, 0,
	0, 147, 0, 0, 88, 89, 90, 148, 91, 0,
	0, 0, 247, 248, 252, 249, 253, 250, 251, 254,
	156, 0, 0, 0, 0, 0, 0, 149, 0, 0,
	246, 151, 150, 147, 154, 243, 155, 0, 0, 148,
	0, 0, 241, 0, 247, 248, 252, 249, 253, 250,
	251, 254, 156, 149, 0, 0, 0, 0, 0, 147,
	0, 0, 246, 151, 150, 148, 154, 0, 155, 0,
	157, 158, 0, 159, 335, 160, 161, 0, 156, 0,
	0, 0, 0, 0, 0, 149, 0, 0, 152, 151,
	150, 147, 154, 0, 155, 0, 0, 148, 0, 0,
	0, 306, 157, 158, 0, 159, 0, 160, 161, 0,
	156, 149, 0, 0, 0, 0, 258, 147, 0, 0,
	259, 151, 150, 148, 154, 0, 155, 453, 157, 158,
	0, 159, 0, 160, 161, 0, 156, 149, 0, 0,
	0, 0, 258, 147, 0, 0, 259, 151, 150, 148,
	154, 0, 155, 438, 157, 158, 0, 159, 0, 160,
	161, 0, 156, 149, 0, 0, 0, 0, 258, 147,
	0, 0, 259, 151, 150, 148, 154, 0, 155, 432,
	157, 158, 0, 159, 0, 160, 161, 0, 156, 149,
	0, 0, 0, 0, 258, 147, 0, 0, 259, 151,
	150, 148, 154, 0, 155, 409, 157, 158, 0, 159,
	0, 160, 161, 0, 156, 149, 0, 0, 0, 0,
	258, 147, 0, 0, 259, 151, 150, 148, 154, 0,
	155, 395, 157, 158, 0, 159, 0, 160, 161, 0,
	156, 149, 0, 0, 0, 0, 258, 147, 0, 0,
	259, 151, 150, 148, 154, 0, 155, 325, 157, 158,
	0, 159, 0, 160, 161, 0, 156, 149, 0, 0,
	0, 0, 258, 147, 0, 0, 259, 151, 150, 148,
	154, 0, 155, 256, 157, 158, 0, 159, 0, 160,
	161, 0, 156, 149, 0, 0, 0, 0, 374, 147,
	0, 0, 259, 151, 150, 148, 154, 0, 155, 0,
	157, 158, 0, 159, 0, 160, 161, 0, 156, 149,
	0, 0, 0, 0, 0, 147, 0, 0, 152, 151,
	150, 148, 154, 0, 155, 0, 157, 158, 0, 159,
	0, 160, 161, 0, 156, 149, 0, 0, 0, 0,
	0, 147, 0, 0, 152, 151, 150, 148, 154, 0,
	437, 0, 157, 158, 0, 159, 0, 160, 161, 0,
	156, 149, 0, 0, 0, 0, 0, 147, 0, 0,
	152, 151, 150, 148, 154, 0, 414, 0, 157, 158,
	0, 159, 0, 160, 161, 0, 156, 149, 0, 0,
	0, 0, 0, 147, 0, 0, 152, 151, 150, 148,
	154, 0, 406, 0, 157, 158, 0, 159, 0, 160,
	161, 0, 156, 149, 0, 0, 0, 0, 0, 147,
	0, 0, 152, 151, 150, 148, 154, 0, 375, 0,
	157, 158, 0, 159, 0, 160, 161, 345, 156, 0,
	348, 0, 0, 0, 0, 0, 0, 0, 152, 151,
	150, 0, 154, 0, 353, 329, 330, 252, 331, 253,
	333, 332, 254, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 328,
}

var yyPact = [...]int16{
	-1000, -1000, 340, 102, -1000, -1000, 843, -1000, 64, 2,
	-1000, 843, -1000, 843, 355, 354, 336, -1000, 352, 348,
	344, -1000, -1000, -1000, 843, -1000, 58, 1026, -1000, -1000,
	-1000, -1000, -1000, -1000, 2, -1000, -1000, 843, 843, 843,
	843, 139, -1000, -1000, 502, -1000, 843, 229, 843, 748,
	-1000, 293, 593, 679, -1000, -1000, 1593, 419, -1000, 972,
	380, 918, 95, 70, 139, -48, -1000, 342, 61, -1000,
	19, -1000, 118, 18, 864, 191, 843, 843, 843, 843,
	843, 843, 843, 843, 843, 843, 843, 843, 843, 843,
	843, 843, 843, 843, 843, 843, 843, 843, 1593, 1593,
	-1000, 155, 155, 155, 155, -1000, 325, 241, 272, -1000,
	16, -1000, 75, 843, 1026, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 58, -1000, 2, 808, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 292, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 97, 50, 116, 153, 280, -1000, -1000, -1000,
	-1000, -1000, -28, -19, 1295, 1541, 236, 254, 251, 289,
	235, 231, -1000, -1000, 843, -1000, 843, 843, 334, -1000,
	593, 329, 139, 843, 326, 1593, 1593, 74, 69, 288,
	-1000, -1000, 1026, 1069, 1112, 1132, 1132, 1132, 1132, 1132,
	1132, 1229, 1245, 1245, 155, 155, 155, 155, 1209, 1166,
	1186, 1229, 1229, 155, -1000, -1000, 185, -29, 17, 67,
	275, 76, -1000, 12, -1000, 176, -1000, -1000, 843, 752,
	-1000, -1000, 293, -1000, -1000, 1593, -1000, -1000, 1593, 1593,
	1593, -1000, 250, 1353, -1000, 324, 1593, 323, 1593, 316,
	225, 1593, 96, -1000, -1000, -23, -28, 254, 251, 289,
	235, 231, -1000, -1000, -1000, 92, 152, -1000, 1593, -33,
	116, 1515, 281, 1327, 370, 843, 1593, 417, 1026, -1000,
	536, 89, -1000, -1000, -1000, -1000, 58, -1000, 116, 116,
	1593, 1748, 288, -1000, -44, -46, -29, -1000, 1723, 1593,
	347, 172, -29, -1000, 272, 1593, -1000, 1026, 73, -1000,
	116, 148, 148, 140, 177, -1000, -1000, 212, 221, 50,
	-1000, 50, -1000, -1000, 207, -1000, 455, 1593, 1593, 160,
	1567, 1697, 116, 1593, 88, 10, 87, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 213, 1593, 85, 1593, 698, 194,
	-1000, 413, 843, -1000, 116, -1000, -1000, -1000, 593, -1000,
	-1000, 416, 24, 1489, 116, 9, -29, -1000, -1000, 116,
	843, 1593, -1000, -1000, 625, -1000, -1000, 8, -1000, -1000,
	166, -1000, 1671, -1000, 1593, 1463, 116, 116, 7, 1645,
	-1000, -1000, 154, -1000, 116, -1000, -1000, -1000, -1000, 843,
	438, 414, 120, 409, -1000, 152, -1, 1593, -1000, 405,
	1026, -24, -1000, 82, 1593, 256, 1437, 116, 116, 152,
	81, -6, 1619, 116, 1411, 1, 402, 644, -1000, 843,
	-1000, 218, -1000, -1000, 1593, 116, 401, -1000, 1593, -1000,
	202, 80, 152, -1000, 1593, 1593, 116, 1385, 152, 79,
	1593, -1000, -1000, 399, 590, 195, 52, -1000, 116, -1000,
	-1000, 116, 116, 152, 23, -1000, 165, -1000, -1000, -1000,
	-29, 5, -1000, -1000, -1000, 397, -1000, -29, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 432, 466, 5, 464, 463, 461, 460, 459, 458,
	383, 457, 17, 29, 38, 347, 402, 455, 33, 454,
	28, 25, 27, 453, 22, 452, 451, 447, 8, 0,
	24, 446, 12, 2, 26, 13, 1, 3, 445, 443,
	11, 20, 15, 10, 4, 14, 439, 434, 430, 16,
	19, 9, 23, 6, 7,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 2, 2, 2, 3, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 5, 5, 6,
	6, 6, 7, 7, 8, 8, 9, 9, 10, 10,
	10, 10, 10, 10, 10, 10, 11, 11, 12, 12,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 14, 15, 15,
	15, 15, 17, 16, 16, 16, 16, 34, 18, 18,
	18, 18, 19, 20, 20, 20, 20, 21, 21, 21,
	21, 21, 22, 22, 23, 23, 23, 24, 24, 24,
	26, 26, 26, 26, 26, 26, 26, 26, 27, 27,
	27, 27, 27, 27, 27, 27, 27, 28, 28, 28,
	28, 28, 28, 25, 25, 36, 36, 36, 36, 29,
	29, 29, 29, 30, 30, 30, 31, 31, 31, 31,
	31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
	31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
	31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
	31, 31, 31, 31, 31, 31, 50, 50, 32, 32,
	33, 33, 35, 35, 51, 51, 52, 52, 52, 52,
	41, 41, 41, 42, 42, 43, 43, 54, 54, 53,
	53, 53, 37, 38, 38, 39, 39, 40, 40, 44,
	44, 45, 45, 48, 48, 48, 49, 49, 46, 46,
	46, 47, 47,
}

var yyR2 = [...]int8{
	0, 1, 2, 3, 0, 2, 2, 1, 3, 1,
	3, 5, 4, 6, 8, 9, 11, 7, 3, 4,
	4, 2, 1, 2, 4, 5, 5, 0, 5, 1,
	2, 1, 1, 3, 1, 3, 1, 3, 1, 4,
	3, 3, 3, 3, 3, 3, 1, 3, 1, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	2, 2, 2, 2, 3, 3, 2, 1, 1, 1,
	1, 3, 3, 2, 3, 4, 5, 3, 2, 3,
	1, 1, 2, 6, 5, 7, 6, 1, 3, 1,
	3, 5, 2, 3, 1, 3, 2, 3, 5, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 0, 2, 3, 6, 1,
	3, 3, 7, 1, 2, 2, 1, 1, 1, 1,
	1, 1, 1, 4, 4, 3, 7, 3, 7, 6,
	5, 6, 4, 5, 3, 6, 8, 5, 7, 7,
	6, 4, 3, 4, 3, 3, 4, 4, 8, 4,
	2, 2, 4, 4, 4, 4, 3, 3, 1, 3,
	3, 3, 1, 1, 3, 1, 1, 3, 2, 4,
	1, 3, 2, 3, 3, 1, 2, 1, 2, 2,
	4, 5, 3, 0, 1, 1, 3, 1, 3, 1,
	3, 1, 3, 0, 2, 3, 1, 1, 0, 2,
	2, 6, 7,
}

var yyChk = [...]int16{
	-1000, -1, -2, -6, -4, 76, 19, 5, -9, -15,
	6, 24, 20, 13, 11, 12, 15, 44, 25, 45,
	27, -10, -17, -16, 51, 76, -12, -13, 16, 10,
	22, 46, 41, -19, -15, -14, -22, 68, 17, 81,
	65, 12, -10, 47, 49, 45, 77, 78, 57, 80,
	-18, -34, 79, 51, -22, -14, 43, -3, -1, -13,
	-3, -13, 45, -11, -7, -8, 45, 12, -44, -45,
	45, 45, 45, 45, -13, -16, 78, 18, 4, 53,
	63, 39, 38, 36, 37, 40, 67, 68, 69, 70,
	71, 73, 66, 64, 65, 54, 55, 56, 29, 42,
	61, -13, -13, -13, -13, -20, 51, -37, 63, 50,
	-23, -24, -26, 57, -13, 45, 27, 28, 29, 30,
	31, 33, 34, -12, -10, -15, -13, 45, 27, 28,
	29, 30, 31, -18, -28, 45, 27, 28, 29, 30,
	31, 52, -12, -32, -29, -30, -31, 16, 22, 10,
	47, 46, 45, -50, 49, 51, 35, 27, 28, 30,
	32, 33, 9, 6, 23, 21, 77, 14, 78, -20,
	79, 80, 45, 77, 78, 79, 77, -37, -48, 79,
	52, 52, -13, -13, -13, -13, -13, -13, -13, -13,
	-13, -13, -13, -13, -13, -13, -13, -13, -13, -13,
	-13, -13, -13, -13, -29, -29, -21, 52, 41, -44,
	51, -39, -40, 45, 50, -25, 78, 76, 77, -13,
	58, -18, -34, 52, -35, 78, 53, 55, 64, 66,
	34, 60, -54, 57, -53, 48, 63, 80, 63, 80,
	-29, 57, -41, 50, -42, -27, 45, 27, 28, 30,
	32, 33, 29, 31, 34, -52, 52, -51, 41, 45,
	-29, 51, 49, 49, 45, 51, 51, -3, -13, -3,
	-13, -12, 45, -28, 45, -20, -12, -45, -29, -29,
	77, -46, 78, -49, 45, -50, 52, -36, 79, 79,
	78, -21, 52, 53, 78, 79, -24, -13, 58, -18,
	-29, -30, -30, -30, 57, -53, 58, -29, 45, -32,
	45, -32, 45, 50, -29, 50, 78, 79, 62, 52,
	78, 59, -29, 79, -52, 52, -41, 50, 45, 27,
	28, 30, 33, 32, -29, 57, -41, 31, -13, -29,
	9, -5, 78, 6, -29, 9, -42, -47, 12, -49,
	-36, -3, -32, 51, -29, 41, 52, -36, -40, -29,
	77, 60, 58, 58, 51, -35, -35, 58, -42, -43,
	-29, -43, 59, -51, 41, 51, -29, -29, 52, 79,
	50, 50, -29, 50, -29, 52, 52, 9, 7, 8,
	-13, -3, -28, -3, 9, 52, -29, 79, -36, -3,
	-13, -29, 52, -12, 79, -54, 51, -29, -29, 52,
	-33, -29, 79, -29, 51, 58, -3, -13, 6, 78,
	9, -38, -37, 9, 78, -29, -3, 9, 79, 52,
	-29, -33, 52, 52, 78, 78, -29, 51, 52, -33,
	79, 9, 21, -3, -13, 51, -32, 9, -29, 50,
	52, -29, -29, 52, -33, 52, -29, -3, 9, 6,
	52, -44, 52, 52, 50, -3, -36, 52, 9, -36,
}

var yyDef = [...]int16{
	4, -2, 1, 2, 5, 6, 29, 31, 0, 9,
	4, 0, 4, 0, 0, 0, 0, 22, 0, 38,
	0, -2, 89, 90, 0, 3, 30, 48, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 0, 0, 0,
	0, 0, 88, 87, 0, 38, 0, 0, 0, 0,
	93, 0, 0, 0, 100, 101, 0, 0, 7, 0,
	0, 0, 46, 0, 0, 32, 34, 0, 21, 229,
	231, 23, 0, 233, 0, 90, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	86, 80, 81, 82, 83, 102, 0, 0, 0, 112,
	0, 114, 0, 0, 119, -2, 121, 122, 123, 124,
	125, 126, 127, 8, -2, 0, 0, 40, 41, 42,
	43, 44, 45, 94, 0, 137, 138, 139, 140, 141,
	142, 98, 0, 0, 198, 149, 153, 156, 157, 158,
	159, 160, 161, 162, 0, 0, 0, 0, 0, 0,
	0, 0, 10, 4, 0, 4, 0, 0, 0, 18,
	0, 0, 0, 0, 0, 0, 0, 0, 238, 0,
	91, 92, 49, 59, 60, 61, 62, 63, 64, 65,
	66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
	76, 77, 78, 79, 84, 85, 0, 145, 107, 109,
	0, 0, 225, 227, 113, 116, 143, 144, 0, 0,
	39, 95, 0, 99, 97, 0, 202, 203, 0, 0,
	0, 155, 154, 0, 217, 0, 0, 0, 0, 0,
	0, 0, 0, 190, 210, 0, -2, 129, 130, 132,
	136, 134, 131, 133, 135, 0, 0, 206, 0, 161,
	205, 0, 0, 0, 191, 0, 0, 0, 12, 27,
	0, 0, 47, 33, 35, 19, 20, 230, 232, 24,
	0, 0, 0, 234, 236, 237, 145, 4, 0, 0,
	0, 0, 145, 222, 0, 0, 115, 117, 0, 96,
	199, 150, 151, 0, 0, 218, 185, 0, 219, 0,
	196, 0, 197, 165, 0, 167, 212, 0, 0, 174,
	0, 0, 208, 0, 0, 182, 0, 184, 128, 129,
	130, 132, 134, 136, 0, 0, 0, 0, 0, 0,
	11, 0, 0, 4, 25, 26, 239, 240, 0, 235,
	4, 0, 146, 0, 108, 110, 145, 4, 226, 228,
	0, 155, 186, 195, 0, 163, 164, 0, 211, 213,
	215, 214, 0, 207, 0, 0, 172, 204, 181, 0,
	183, 187, 0, 189, 192, 193, 194, 13, 4, 0,
	0, 0, 223, 0, 104, 147, 205, 0, 4, 0,
	118, 0, 220, 0, 0, 216, 0, 170, 209, 173,
	0, 205, 0, 177, 0, 0, 0, 0, 4, 0,
	17, 0, 224, 103, 0, 111, 0, 106, 0, 221,
	0, 0, 169, 171, 0, 0, 175, 0, 180, 0,
	0, 14, 4, 0, 0, 0, 0, 105, 152, 166,
	168, 201, 200, 179, 0, 178, 0, 28, 15, 4,
	145, 0, 148, 176, 188, 0, 241, 145, 16, 242,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 81, 3, 71, 66, 3,
	51, 52, 69, 67, 78, 68, 80, 70, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 79, 76,
	63, 77, 53, 3, 48, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 57, 3, 58, 73, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 49, 64, 50, 65,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 54, 55, 56, 59,
	60, 61, 62, 72, 74, 75,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:326
		{
			yyVAL.stmts = yyDollar[1].stmts
			if l, ok := yylex.(*Lexer); ok {
				l.Stmts = yyVAL.stmts
			}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:332
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
			if l, ok := yylex.(*Lexer); ok {
				l.Stmts = yyVAL.stmts
			}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:338
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
			if l, ok := yylex.(*Lexer); ok {
				l.Stmts = yyVAL.stmts
			}
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:346
		{
			yyVAL.stmts = []ast.Stmt{}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:349
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:352
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:357
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:362
		{
			yyVAL.stmt = &ast.AssignStmt{Lhs: yyDollar[1].exprlist, Rhs: yyDollar[3].exprlist}
			yyVAL.stmt.CopyPos(yyDollar[1].exprlist[0])
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:367
		{
			if _, ok := yyDollar[1].expr.(*ast.FuncCallExpr); !ok {
				yylex.(*Lexer).Error("parse error")
			} else {
				yyVAL.stmt = &ast.FuncCallStmt{Expr: yyDollar[1].expr}
				yyVAL.stmt.CopyPos(yyDollar[1].expr)
			}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:375
		{
			yyVAL.stmt = &ast.DoBlockStmt{Stmts: yyDollar[2].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:380
		{
			yyVAL.stmt = &ast.WhileStmt{Condition: yyDollar[2].expr, Stmts: yyDollar[4].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[5].token.Pos)
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:385
		{
			yyVAL.stmt = &ast.RepeatStmt{Condition: yyDollar[4].expr, Stmts: yyDollar[2].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastLine(yyDollar[4].expr.Line())
		}
	case 13:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:390
		{
			yyVAL.stmt = &ast.IfStmt{Condition: yyDollar[2].expr, Then: yyDollar[4].stmts, EndPosition: yyDollar[6].token.Pos}
			cur := yyVAL.stmt
			for _, elseif := range yyDollar[5].stmts {
				cur.(*ast.IfStmt).Else = []ast.Stmt{elseif}
				cur = elseif
			}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[6].token.Pos)
		}
	case 14:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:400
		{
			yyVAL.stmt = &ast.IfStmt{Condition: yyDollar[2].expr, Then: yyDollar[4].stmts, EndPosition: yyDollar[8].token.Pos}
			cur := yyVAL.stmt
			for _, elseif := range yyDollar[5].stmts {
				cur.(*ast.IfStmt).Else = []ast.Stmt{elseif}
				cur = elseif
			}
			cur.(*ast.IfStmt).Else = yyDollar[7].stmts
			cur.(*ast.IfStmt).HasElse = true
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[8].token.Pos)
		}
	case 15:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:412
		{
			yyVAL.stmt = &ast.NumberForStmt{Name: yyDollar[2].token.Str, NamePosition: yyDollar[2].token.Pos, Init: yyDollar[4].expr, Limit: yyDollar[6].expr, Stmts: yyDollar[8].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[9].token.Pos)
		}
	case 16:
		yyDollar = yyS[yypt-11 : yypt+1]
//line parser.go.y:417
		{
			yyVAL.stmt = &ast.NumberForStmt{Name: yyDollar[2].token.Str, NamePosition: yyDollar[2].token.Pos, Init: yyDollar[4].expr, Limit: yyDollar[6].expr, Step: yyDollar[8].expr, Stmts: yyDollar[10].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[11].token.Pos)
		}
	case 17:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:422
		{
			names, positions := splitNameList(yyDollar[2].namelist)
			yyVAL.stmt = &ast.GenericForStmt{Names: names, NamePositions: positions, Exprs: yyDollar[4].exprlist, Stmts: yyDollar[6].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[7].token.Pos)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:428
		{
			yyVAL.stmt = &ast.FuncDefStmt{Name: yyDollar[2].funcname, Func: yyDollar[3].funcexpr}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.CopyLastPos(yyDollar[3].funcexpr)
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:433
		{
			yyVAL.stmt = &ast.LocalAssignStmt{Names: []string{yyDollar[3].token.Str}, NamePositions: []ast.Position{yyDollar[3].token.Pos}, Exprs: []ast.Expr{yyDollar[4].funcexpr}, LocalFunction: true}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.CopyLastPos(yyDollar[4].funcexpr)
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:438
		{
			names, positions, types := splitTypedNames(yyDollar[2].typednames)
			yyVAL.stmt = &ast.LocalAssignStmt{Names: names, NamePositions: positions, Types: types, Exprs: yyDollar[4].exprlist}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:443
		{
			names, positions, types := splitTypedNames(yyDollar[2].typednames)
			yyVAL.stmt = &ast.LocalAssignStmt{Names: names, NamePositions: positions, Types: types, Exprs: []ast.Expr{}}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:448
		{
			yyVAL.stmt = &ast.LabelStmt{Name: yyDollar[1].token.Str}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:452
		{
			yyVAL.stmt = &ast.GotoStmt{Label: yyDollar[2].token.Str}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:456
		{
			if yyDollar[1].token.Str != "type" {
				yylex.(*Lexer).Error("unexpected identifier")
			}
			yyVAL.stmt = &ast.TypeDefStmt{Name: yyDollar[2].token.Str, NamePosition: yyDollar[2].token.Pos, Type: yyDollar[4].typeexpr}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.CopyLastPos(yyDollar[4].typeexpr)
		}
	case 25:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:464
		{
			if yyDollar[1].token.Str != "type" {
				yylex.(*Lexer).Error("unexpected identifier")
			}
			yyVAL.stmt = &ast.TypeDefStmt{Name: yyDollar[2].token.Str, NamePosition: yyDollar[2].token.Pos, TypeParams: yyDollar[3].typeparams, Type: yyDollar[5].typeexpr}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.CopyLastPos(yyDollar[5].typeexpr)
		}
	case 26:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:472
		{
			yyVAL.stmt = &ast.InterfaceDefStmt{Name: yyDollar[2].token.Str, NamePosition: yyDollar[2].token.Pos, Extends: yyDollar[3].typereflist, Members: yyDollar[4].interfacebody.members}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[5].token.Pos)
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:479
		{
			yyVAL.stmts = []ast.Stmt{}
		}
	case 28:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:482
		{
			yyVAL.stmts = append(yyDollar[1].stmts, &ast.IfStmt{Condition: yyDollar[3].expr, Then: yyDollar[5].stmts})
			yyVAL.stmts[len(yyVAL.stmts)-1].SetPosFromToken(yyDollar[2].token.Pos)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:488
		{
			yyVAL.stmt = &ast.ReturnStmt{Exprs: nil}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:492
		{
			yyVAL.stmt = &ast.ReturnStmt{Exprs: yyDollar[2].exprlist}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:496
		{
			yyVAL.stmt = &ast.BreakStmt{}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:502
		{
			yyVAL.funcname = yyDollar[1].funcname
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:505
		{
			yyVAL.funcname = &ast.FuncName{Func: nil, Receiver: yyDollar[1].funcname.Func, Method: yyDollar[3].token.Str, MethodPosition: yyDollar[3].token.Pos}
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:510
		{
			yyVAL.funcname = &ast.FuncName{Func: &ast.IdentExpr{Value: yyDollar[1].token.Str}}
			yyVAL.funcname.Func.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:514
		{
			key := &ast.StringExpr{Value: yyDollar[3].token.Str}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			fn := &ast.AttrGetExpr{Object: yyDollar[1].funcname.Func, Key: key, KeySyntax: ast.AttrKeyDot}
			fn.CopyPos(yyDollar[1].funcname.Func)
			fn.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.funcname = &ast.FuncName{Func: fn}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:525
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:528
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:533
		{
			yyVAL.expr = &ast.IdentExpr{Value: yyDollar[1].token.Str}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:537
		{
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: yyDollar[3].expr, KeySyntax: ast.AttrKeyIndex}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastLine(yyDollar[4].token.Pos.Line)
			yyVAL.expr.SetLastColumn(yyDollar[4].token.Pos.Column + 1)
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:543
		{
			key := &ast.StringExpr{Value: yyDollar[3].token.Str}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:551
		{
			key := &ast.StringExpr{Value: "interface"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:559
		{
			key := &ast.StringExpr{Value: "readonly"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:567
		{
			key := &ast.StringExpr{Value: "as"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:575
		{
			key := &ast.StringExpr{Value: "asserts"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:583
		{
			key := &ast.StringExpr{Value: "is"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:593
		{
			yyVAL.namelist = []nameWithPos{{Name: yyDollar[1].token.Str, Pos: yyDollar[1].token.Pos}}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:596
		{
			yyVAL.namelist = append(yyDollar[1].namelist, nameWithPos{Name: yyDollar[3].token.Str, Pos: yyDollar[3].token.Pos})
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:601
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:604
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:609
		{
			yyVAL.expr = &ast.NilExpr{}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:613
		{
			yyVAL.expr = &ast.FalseExpr{}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:617
		{
			yyVAL.expr = &ast.TrueExpr{}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:621
		{
			yyVAL.expr = &ast.NumberExpr{Value: yyDollar[1].token.Str}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:625
		{
			yyVAL.expr = &ast.Comma3Expr{}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:629
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:632
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:635
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:638
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:641
		{
			yyVAL.expr = &ast.LogicalOpExpr{Lhs: yyDollar[1].expr, Operator: "or", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:646
		{
			yyVAL.expr = &ast.LogicalOpExpr{Lhs: yyDollar[1].expr, Operator: "and", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:651
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: ">", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:656
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: "<", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:661
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: ">=", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:666
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: "<=", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:671
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: "==", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:676
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: "~=", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:681
		{
			yyVAL.expr = &ast.StringConcatOpExpr{Lhs: yyDollar[1].expr, Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:686
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "+", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:691
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "-", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:696
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "*", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:701
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "/", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:706
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "%", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:711
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "^", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:716
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "&", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:721
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "|", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:726
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "~", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:731
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "<<", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:736
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: ">>", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:741
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "//", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:746
		{
			yyVAL.expr = &ast.UnaryMinusOpExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.CopyPos(yyDollar[2].expr)
			yyVAL.expr.CopyLastPos(yyDollar[2].expr)
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:751
		{
			yyVAL.expr = &ast.UnaryNotOpExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.CopyLastPos(yyDollar[2].expr)
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:756
		{
			yyVAL.expr = &ast.UnaryLenOpExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.CopyPos(yyDollar[2].expr)
			yyVAL.expr.CopyLastPos(yyDollar[2].expr)
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:761
		{
			yyVAL.expr = &ast.UnaryBNotOpExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.CopyPos(yyDollar[2].expr)
			yyVAL.expr.CopyLastPos(yyDollar[2].expr)
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:766
		{
			yyVAL.expr = &ast.CastExpr{Expr: yyDollar[1].expr, Type: yyDollar[3].typeexpr, Syntax: ast.CastSyntaxAs}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].typeexpr)
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:771
		{
			yyVAL.expr = &ast.CastExpr{Expr: yyDollar[1].expr, Type: yyDollar[3].typeexpr, Syntax: ast.CastSyntaxColonColon}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].typeexpr)
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:776
		{
			yyVAL.expr = &ast.NonNilAssertExpr{Expr: yyDollar[1].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[2].token.Pos)
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:783
		{
			yyVAL.expr = &ast.StringExpr{Value: yyDollar[1].token.Str}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:789
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:792
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:795
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:798
		{
			if ex, ok := yyDollar[2].expr.(*ast.Comma3Expr); ok {
				ex.AdjustRet = true
			}
			yyVAL.expr = yyDollar[2].expr
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:808
		{
			call := yyDollar[2].expr.(*ast.FuncCallExpr)
			call.AdjustRet = true
			call.SetPosFromToken(yyDollar[1].token.Pos)
			call.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = call
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:817
		{
			yyVAL.expr = callExpr(yyDollar[1].expr, nil, ast.Token{}, nil, yyDollar[2].callargs)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:822
		{
			yyVAL.expr = callExpr(yyDollar[1].expr, nil, ast.Token{}, yyDollar[2].typeexprlist, yyDollar[3].callargs)
		}
	case 95:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:825
		{
			yyVAL.expr = callExpr(nil, yyDollar[1].expr, yyDollar[3].token, nil, yyDollar[4].callargs)
		}
	case 96:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:828
		{
			yyVAL.expr = callExpr(nil, yyDollar[1].expr, yyDollar[3].token, yyDollar[4].typeexprlist, yyDollar[5].callargs)
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:833
		{
			yyVAL.typeexprlist = yyDollar[2].typeexprlist
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:838
		{
			if yylex.(*Lexer).PNewLine {
				yylex.(*Lexer).TokenError(yyDollar[1].token, "ambiguous syntax (function call x new statement)")
			}
			yyVAL.callargs = callArguments{values: []ast.Expr{}, end: yyDollar[2].token.Pos}
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:844
		{
			if yylex.(*Lexer).PNewLine {
				yylex.(*Lexer).TokenError(yyDollar[1].token, "ambiguous syntax (function call x new statement)")
			}
			yyVAL.callargs = callArguments{values: yyDollar[2].exprlist, end: yyDollar[3].token.Pos}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:850
		{
			yyVAL.callargs = callArguments{values: []ast.Expr{yyDollar[1].expr}, end: positionAtEnd(yyDollar[1].expr)}
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:853
		{
			yyVAL.callargs = callArguments{values: []ast.Expr{yyDollar[1].expr}, end: positionAtEnd(yyDollar[1].expr)}
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:858
		{
			yyVAL.expr = &ast.FunctionExpr{TypeParams: yyDollar[2].funcexpr.TypeParams, ParList: yyDollar[2].funcexpr.ParList, ReturnTypes: yyDollar[2].funcexpr.ReturnTypes, ReturnsKnown: yyDollar[2].funcexpr.ReturnsKnown, Stmts: yyDollar[2].funcexpr.Stmts}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.CopyLastPos(yyDollar[2].funcexpr)
		}
	case 103:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:865
		{
			yyVAL.funcexpr = &ast.FunctionExpr{ParList: yyDollar[2].parlist, ReturnTypes: yyDollar[4].returntype.types, ReturnsKnown: yyDollar[4].returntype.known, Stmts: yyDollar[5].stmts}
			yyVAL.funcexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.funcexpr.SetLastPosFromToken(yyDollar[6].token.Pos)
		}
	case 104:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:870
		{
			yyVAL.funcexpr = &ast.FunctionExpr{ParList: &ast.ParList{HasVargs: false, Names: []string{}}, ReturnTypes: yyDollar[3].returntype.types, ReturnsKnown: yyDollar[3].returntype.known, Stmts: yyDollar[4].stmts}
			yyVAL.funcexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.funcexpr.SetLastPosFromToken(yyDollar[5].token.Pos)
		}
	case 105:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:875
		{
			yyVAL.funcexpr = &ast.FunctionExpr{TypeParams: yyDollar[1].typeparams, ParList: yyDollar[3].parlist, ReturnTypes: yyDollar[5].returntype.types, ReturnsKnown: yyDollar[5].returntype.known, Stmts: yyDollar[6].stmts}
			yyVAL.funcexpr.SetPosFromToken(yyDollar[2].token.Pos)
			yyVAL.funcexpr.SetLastPosFromToken(yyDollar[7].token.Pos)
		}
	case 106:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:880
		{
			yyVAL.funcexpr = &ast.FunctionExpr{TypeParams: yyDollar[1].typeparams, ParList: &ast.ParList{HasVargs: false, Names: []string{}}, ReturnTypes: yyDollar[4].returntype.types, ReturnsKnown: yyDollar[4].returntype.known, Stmts: yyDollar[5].stmts}
			yyVAL.funcexpr.SetPosFromToken(yyDollar[2].token.Pos)
			yyVAL.funcexpr.SetLastPosFromToken(yyDollar[6].token.Pos)
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:887
		{
			yyVAL.parlist = &ast.ParList{HasVargs: true, VarargPosition: yyDollar[1].token.Pos, Names: []string{}}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:890
		{
			yyVAL.parlist = &ast.ParList{HasVargs: true, VarargType: yyDollar[3].typeexpr, VarargPosition: yyDollar[1].token.Pos, Names: []string{}}
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:893
		{
			names, positions, types := splitTypedNames(yyDollar[1].typednames)
			yyVAL.parlist = &ast.ParList{HasVargs: false, Names: names, NamePositions: positions, Types: types}
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:897
		{
			names, positions, types := splitTypedNames(yyDollar[1].typednames)
			yyVAL.parlist = &ast.ParList{HasVargs: true, VarargPosition: yyDollar[3].token.Pos, Names: names, NamePositions: positions, Types: types}
		}
	case 111:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:901
		{
			names, positions, types := splitTypedNames(yyDollar[1].typednames)
			yyVAL.parlist = &ast.ParList{HasVargs: true, VarargType: yyDollar[5].typeexpr, VarargPosition: yyDollar[3].token.Pos, Names: names, NamePositions: positions, Types: types}
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:908
		{
			yyVAL.expr = &ast.TableExpr{Fields: []*ast.Field{}}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.SetLastPosFromToken(yyDollar[2].token.Pos)
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:913
		{
			yyVAL.expr = &ast.TableExpr{Fields: yyDollar[2].fieldlist}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:921
		{
			yyVAL.fieldlist = []*ast.Field{yyDollar[1].field}
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:924
		{
			yyVAL.fieldlist = append(yyDollar[1].fieldlist, yyDollar[3].field)
		}
	case 116:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:927
		{
			yyVAL.fieldlist = yyDollar[1].fieldlist
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:932
		{
			key := &ast.StringExpr{Value: yyDollar[1].token.Str}
			key.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.field = &ast.Field{Key: key, KeySyntax: ast.AttrKeyDot, Value: yyDollar[3].expr}
			yyVAL.field.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.field.CopyLastPos(yyDollar[3].expr)
		}
	case 118:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:939
		{
			yyVAL.field = &ast.Field{Key: yyDollar[2].expr, KeySyntax: ast.AttrKeyIndex, Value: yyDollar[5].expr}
			yyVAL.field.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.field.CopyLastPos(yyDollar[5].expr)
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:944
		{
			yyVAL.field = &ast.Field{Value: yyDollar[1].expr}
			yyVAL.field.CopyPos(yyDollar[1].expr)
			yyVAL.field.CopyLastPos(yyDollar[1].expr)
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:952
		{
			yyVAL.token = yyDollar[1].token
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:955
		{
			yyVAL.token = yyDollar[1].token
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:958
		{
			yyVAL.token = yyDollar[1].token
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:961
		{
			yyVAL.token = yyDollar[1].token
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:964
		{
			yyVAL.token = yyDollar[1].token
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:967
		{
			yyVAL.token = yyDollar[1].token
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:970
		{
			yyVAL.token = yyDollar[1].token
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:973
		{
			yyVAL.token = yyDollar[1].token
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:979
		{
			yyVAL.token = yyDollar[1].token
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:982
		{
			yyVAL.token = yyDollar[1].token
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:985
		{
			yyVAL.token = yyDollar[1].token
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:988
		{
			yyVAL.token = yyDollar[1].token
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:991
		{
			yyVAL.token = yyDollar[1].token
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:994
		{
			yyVAL.token = yyDollar[1].token
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:997
		{
			yyVAL.token = yyDollar[1].token
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1000
		{
			yyVAL.token = yyDollar[1].token
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1003
		{
			yyVAL.token = yyDollar[1].token
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1010
		{
			yyVAL.token = yyDollar[1].token
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1013
		{
			yyVAL.token = yyDollar[1].token
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1016
		{
			yyVAL.token = yyDollar[1].token
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1019
		{
			yyVAL.token = yyDollar[1].token
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1022
		{
			yyVAL.token = yyDollar[1].token
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1025
		{
			yyVAL.token = yyDollar[1].token
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1030
		{
			yyVAL.fieldsep = ","
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1033
		{
			yyVAL.fieldsep = ";"
		}
	case 145:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:1040
		{
			yyVAL.returntype = returnTypeAnnotation{}
		}
	case 146:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1043
		{
			last := yyDollar[2].typeexprlist[len(yyDollar[2].typeexprlist)-1]
			yyVAL.returntype = returnTypeAnnotation{
				types: yyDollar[2].typeexprlist,
				known: true,
				end: ast.Position{
					Line: last.LastLine(), Column: last.LastColumn(),
					EndLine: last.LastLine(), EndColumn: last.LastColumn(),
				},
			}
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1054
		{
			yyVAL.returntype = returnTypeAnnotation{known: true, end: yyDollar[3].token.Pos}
		}
	case 148:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1057
		{
			yyVAL.returntype = returnTypeAnnotation{types: append([]ast.TypeExpr{yyDollar[3].typeexpr}, yyDollar[5].typeexprlist...), known: true, end: yyDollar[6].token.Pos}
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1062
		{
			yyVAL.typeexpr = yyDollar[1].typeexpr
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1065
		{
			if union, ok := yyDollar[1].typeexpr.(*ast.UnionTypeExpr); ok {
				union.Types = append(union.Types, yyDollar[3].typeexpr)
				yyVAL.typeexpr = union
			} else {
				yyVAL.typeexpr = &ast.UnionTypeExpr{Types: []ast.TypeExpr{yyDollar[1].typeexpr, yyDollar[3].typeexpr}}
				yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			}
			yyVAL.typeexpr.CopyLastPos(yyDollar[3].typeexpr)
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1075
		{
			if inter, ok := yyDollar[1].typeexpr.(*ast.IntersectionTypeExpr); ok {
				inter.Types = append(inter.Types, yyDollar[3].typeexpr)
				yyVAL.typeexpr = inter
			} else {
				yyVAL.typeexpr = &ast.IntersectionTypeExpr{Types: []ast.TypeExpr{yyDollar[1].typeexpr, yyDollar[3].typeexpr}}
				yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			}
			yyVAL.typeexpr.CopyLastPos(yyDollar[3].typeexpr)
		}
	case 152:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1085
		{
			yyVAL.typeexpr = &ast.ConditionalTypeExpr{Check: yyDollar[1].typeexpr, Extends: yyDollar[3].typeexpr, Then: yyDollar[5].typeexpr, Else: yyDollar[7].typeexpr}
			yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			yyVAL.typeexpr.CopyLastPos(yyDollar[7].typeexpr)
		}
	case 153:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1092
		{
			yyVAL.typeexpr = yyDollar[1].typeexpr
		}
	case 154:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1095
		{
			yyVAL.typeexpr = annotateDirectType(yylex, yyDollar[1].typeexpr, yyDollar[2].annotations)
		}
	case 155:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1098
		{
			yyVAL.typeexpr = &ast.OptionalTypeExpr{Inner: yyDollar[1].typeexpr}
			yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[2].token.Pos)
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1105
		{
			yyVAL.typeexpr = &ast.PrimitiveTypeExpr{Name: "nil"}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1109
		{
			yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: true}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1113
		{
			yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: false}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 159:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1117
		{
			yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: yyDollar[1].token.Str}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1121
		{
			if i, ok := numparse.ParseIntegerLiteral(yyDollar[1].token.Str); ok {
				yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: i}
			} else if f, ok := numparse.ParseFloatLiteral(yyDollar[1].token.Str); ok {
				yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: f}
			} else {
				yyVAL.typeexpr = &ast.LiteralTypeExpr{}
			}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1131
		{
			yyVAL.typeexpr = &ast.PrimitiveTypeExpr{Name: yyDollar[1].token.Str}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 162:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1135
		{
			yyVAL.typeexpr = yyDollar[1].typeref
		}
	case 163:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1138
		{
			yyVAL.typeexpr = genericTypeReference(typeReference(yyDollar[1].token), yyDollar[3].typeexprlist, yyDollar[4].token)
		}
	case 164:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1141
		{
			yyVAL.typeexpr = genericTypeReference(yyDollar[1].typeref, yyDollar[3].typeexprlist, yyDollar[4].token)
		}
	case 165:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1144
		{
			yyVAL.typeexpr = &ast.ArrayTypeExpr{Element: yyDollar[2].typeexpr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 166:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1149
		{
			yyVAL.typeexpr = &ast.MapTypeExpr{Key: yyDollar[3].typeexpr, Value: yyDollar[6].typeexpr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[7].token.Pos)
		}
	case 167:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1154
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: yyDollar[2].recordfields}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 168:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1159
		{
			yyVAL.typeexpr = functionType(yyDollar[2].functionparams, yyDollar[6].typeexprlist)
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[7].token.Pos)
		}
	case 169:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1164
		{
			yyVAL.typeexpr = functionType(yyDollar[2].functionparams, []ast.TypeExpr{})
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[6].token.Pos)
		}
	case 170:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:1169
		{
			yyVAL.typeexpr = functionType(yyDollar[2].functionparams, []ast.TypeExpr{yyDollar[5].typeexpr})
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.CopyLastPos(yyDollar[5].typeexpr)
		}
	case 171:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1174
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: yyDollar[5].typeexprlist}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[6].token.Pos)
		}
	case 172:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1179
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{yyDollar[4].typeexpr}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.CopyLastPos(yyDollar[4].typeexpr)
		}
	case 173:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:1184
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[5].token.Pos)
		}
	case 174:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1189
		{
			yyVAL.typeexpr = parenthesizedType(yylex, yyDollar[2].functionparams, yyDollar[1].token, yyDollar[3].token)
		}
	case 175:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1192
		{
			yyVAL.typeexpr = functionType(yyDollar[3].functionparams, []ast.TypeExpr{yyDollar[6].typeexpr})
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.CopyLastPos(yyDollar[6].typeexpr)
		}
	case 176:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:1197
		{
			yyVAL.typeexpr = functionType(yyDollar[3].functionparams, yyDollar[7].typeexprlist)
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[8].token.Pos)
		}
	case 177:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:1202
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{yyDollar[5].typeexpr}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.CopyLastPos(yyDollar[5].typeexpr)
		}
	case 178:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1207
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: yyDollar[6].typeexprlist}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[7].token.Pos)
		}
	case 179:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1212
		{
			yyVAL.typeexpr = functionType(yyDollar[3].functionparams, []ast.TypeExpr{})
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[7].token.Pos)
		}
	case 180:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1217
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[6].token.Pos)
		}
	case 181:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1222
		{
			yyVAL.typeexpr = functionType(yyDollar[3].functionparams, nil)
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[4].token.Pos)
		}
	case 182:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1227
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: nil}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 183:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1232
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: yyDollar[3].recordfields}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[4].token.Pos)
		}
	case 184:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1237
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: nil}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 185:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1242
		{
			yyVAL.typeexpr = &ast.ArrayTypeExpr{Element: yyDollar[1].typeexpr}
			yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 186:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1250
		{
			yyVAL.typeexpr = &ast.ArrayTypeExpr{Element: annotatedType(yyDollar[1].typeexpr, yyDollar[2].annotations)}
			yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[4].token.Pos)
		}
	case 187:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1255
		{
			arr := &ast.ArrayTypeExpr{Element: yyDollar[3].typeexpr, Readonly: true}
			arr.SetPosFromToken(yyDollar[1].token.Pos)
			arr.SetLastPosFromToken(yyDollar[4].token.Pos)
			yyVAL.typeexpr = arr
		}
	case 188:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:1261
		{
			m := &ast.MapTypeExpr{Key: yyDollar[4].typeexpr, Value: yyDollar[7].typeexpr, Readonly: true}
			m.SetPosFromToken(yyDollar[1].token.Pos)
			m.SetLastPosFromToken(yyDollar[8].token.Pos)
			yyVAL.typeexpr = m
		}
	case 189:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1267
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: yyDollar[3].recordfields, Readonly: true}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[4].token.Pos)
		}
	case 190:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1272
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: nil}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[2].token.Pos)
		}
	case 191:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1277
		{
			yyVAL.typeexpr = &ast.AssertsTypeExpr{ParamName: yyDollar[2].token.Str, ParamPosition: yyDollar[2].token.Pos, NarrowTo: nil}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[2].token.Pos)
		}
	case 192:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1282
		{
			yyVAL.typeexpr = &ast.AssertsTypeExpr{ParamName: yyDollar[2].token.Str, ParamPosition: yyDollar[2].token.Pos, NarrowTo: yyDollar[4].typeexpr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.CopyLastPos(yyDollar[4].typeexpr)
		}
	case 193:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1287
		{
			yyVAL.typeexpr = &ast.TypeOfExpr{Expr: yyDollar[3].expr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[4].token.Pos)
		}
	case 194:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1292
		{
			yyVAL.typeexpr = &ast.KeyOfExpr{Inner: yyDollar[3].typeexpr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[4].token.Pos)
		}
	case 195:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1297
		{
			yyVAL.typeexpr = &ast.IndexAccessExpr{Object: yyDollar[1].typeexpr, Index: yyDollar[3].typeexpr}
			yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[4].token.Pos)
		}
	case 196:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1304
		{
			yyVAL.typeref = qualifyTypeReference(typeReference(yyDollar[1].token), yyDollar[3].token)
		}
	case 197:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1307
		{
			yyVAL.typeref = qualifyTypeReference(yyDollar[1].typeref, yyDollar[3].token)
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1312
		{
			yyVAL.typeexprlist = []ast.TypeExpr{yyDollar[1].typeexpr}
		}
	case 199:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1315
		{
			yyVAL.typeexprlist = append(yyDollar[1].typeexprlist, yyDollar[3].typeexpr)
		}
	case 200:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1320
		{
			yyVAL.typeexprlist = []ast.TypeExpr{yyDollar[1].typeexpr, yyDollar[3].typeexpr}
		}
	case 201:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1323
		{
			yyVAL.typeexprlist = append(yyDollar[1].typeexprlist, yyDollar[3].typeexpr)
		}
	case 202:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1328
		{
			yyVAL.token = yyDollar[1].token
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1331
		{
			yyVAL.token = ast.Token{
				Type: '>',
				Str:  ">",
				Pos:  ast.Position{File: yyDollar[1].token.Pos.File, Line: yyDollar[1].token.Pos.Line, Column: yyDollar[1].token.Pos.Column},
			}
			yylex.(*Lexer).PendingGT = &ast.Token{
				Type: '>',
				Str:  ">",
				Pos:  ast.Position{File: yyDollar[1].token.Pos.File, Line: yyDollar[1].token.Pos.Line, Column: yyDollar[1].token.Pos.Column + 1},
			}
		}
	case 204:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1345
		{
			yyVAL.funcparam = ast.FunctionParamExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr}
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1348
		{
			yyVAL.funcparam = ast.FunctionParamExpr{Name: "", Type: yyDollar[1].typeexpr}
		}
	case 206:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1353
		{
			yyVAL.functionparams = functionTypeParams{Params: []ast.FunctionParamExpr{yyDollar[1].funcparam}}
		}
	case 207:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1356
		{
			yyVAL.functionparams = appendFunctionTypeParam(yylex, yyDollar[1].functionparams, yyDollar[3].funcparam)
		}
	case 208:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1359
		{
			yyVAL.functionparams = setFunctionTypeVariadic(yylex, functionTypeParams{}, yyDollar[1].token, yyDollar[2].typeexpr)
		}
	case 209:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1362
		{
			yyVAL.functionparams = setFunctionTypeVariadic(yylex, yyDollar[1].functionparams, yyDollar[3].token, yyDollar[4].typeexpr)
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1367
		{
			yyVAL.recordfields = []ast.RecordFieldExpr{yyDollar[1].recordfield}
		}
	case 211:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1370
		{
			yyVAL.recordfields = append(yyDollar[1].recordfields, yyDollar[3].recordfield)
		}
	case 212:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1373
		{
			yyVAL.recordfields = yyDollar[1].recordfields
		}
	case 213:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1378
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: false}
		}
	case 214:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1381
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: true}
		}
	case 215:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1386
		{
			yyVAL.typeexpr = yyDollar[1].typeexpr
		}
	case 216:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1389
		{
			yyVAL.typeexpr = annotateFieldType(yylex, yyDollar[1].typeexpr, yyDollar[2].annotations)
		}
	case 217:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1394
		{
			yyVAL.annotations = []ast.AnnotationExpr{yyDollar[1].annotation}
		}
	case 218:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1397
		{
			yyVAL.annotations = append(yyDollar[1].annotations, yyDollar[2].annotation)
		}
	case 219:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1402
		{
			yyVAL.annotation = annotationExpr(yyDollar[1].token, yyDollar[2].token, yyDollar[2].token, nil)
		}
	case 220:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1405
		{
			yyVAL.annotation = annotationExpr(yyDollar[1].token, yyDollar[2].token, yyDollar[4].token, nil)
		}
	case 221:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:1408
		{
			yyVAL.annotation = annotationExpr(yyDollar[1].token, yyDollar[2].token, yyDollar[5].token, yyDollar[4].exprlist)
		}
	case 222:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1413
		{
			yyVAL.typeparams = yyDollar[2].typeparams
		}
	case 223:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:1418
		{
			yyVAL.typeparams = nil
		}
	case 224:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1421
		{
			yyVAL.typeparams = yyDollar[1].typeparams
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1426
		{
			yyVAL.typeparams = []ast.TypeParamExpr{yyDollar[1].typeparam}
		}
	case 226:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1429
		{
			yyVAL.typeparams = append(yyDollar[1].typeparams, yyDollar[3].typeparam)
		}
	case 227:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1434
		{
			yyVAL.typeparam = ast.TypeParamExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Constraint: nil}
		}
	case 228:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1437
		{
			yyVAL.typeparam = ast.TypeParamExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Constraint: yyDollar[3].typeexpr}
		}
	case 229:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1442
		{
			yyVAL.typednames = []typedNameEntry{yyDollar[1].typedname}
		}
	case 230:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1445
		{
			yyVAL.typednames = append(yyDollar[1].typednames, yyDollar[3].typedname)
		}
	case 231:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1450
		{
			yyVAL.typedname = typedNameEntry{Name: yyDollar[1].token.Str, Pos: yyDollar[1].token.Pos, Type: nil}
		}
	case 232:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1453
		{
			yyVAL.typedname = typedNameEntry{Name: yyDollar[1].token.Str, Pos: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr}
		}
	case 233:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:1458
		{
			yyVAL.typereflist = nil
		}
	case 234:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1461
		{
			yyVAL.typereflist = []*ast.TypeRefExpr{yyDollar[2].typeref}
		}
	case 235:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1464
		{
			yyVAL.typereflist = append(yyDollar[1].typereflist, yyDollar[3].typeref)
		}
	case 236:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1469
		{
			yyVAL.typeref = typeReference(yyDollar[1].token)
		}
	case 237:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1472
		{
			yyVAL.typeref = yyDollar[1].typeref
		}
	case 238:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:1477
		{
			yyVAL.interfacebody = interfaceBody{}
		}
	case 239:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1480
		{
			yyVAL.interfacebody = yyDollar[1].interfacebody
			yyVAL.interfacebody.members = append(yyVAL.interfacebody.members, ast.InterfaceMember{
				Kind: ast.InterfaceFieldMember,
				Name: yyDollar[2].recordfield.Name, NamePosition: yyDollar[2].recordfield.NamePosition, Type: yyDollar[2].recordfield.Type,
				Optional: yyDollar[2].recordfield.Optional,
			})
		}
	case 240:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1488
		{
			yyVAL.interfacebody = yyDollar[1].interfacebody
			yyVAL.interfacebody.members = append(yyVAL.interfacebody.members, yyDollar[2].ifacemember)
		}
	case 241:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1494
		{
			returns := yyDollar[6].returntype.types
			if yyDollar[6].returntype.known && returns == nil {
				returns = []ast.TypeExpr{}
			}
			typ := &ast.FunctionTypeExpr{TypeParams: yyDollar[3].typeparams, Params: []ast.FunctionParamExpr{}, Returns: returns}
			typ.SetPosFromToken(yyDollar[1].token.Pos)
			if yyDollar[6].returntype.end.Line != 0 {
				typ.SetLastPosFromToken(yyDollar[6].returntype.end)
			} else {
				typ.SetLastPosFromToken(yyDollar[5].token.Pos)
			}
			yyVAL.ifacemember = ast.InterfaceMember{
				Kind: ast.InterfaceMethodMember,
				Name: yyDollar[2].token.Str, NamePosition: yyDollar[2].token.Pos, Type: typ,
			}
		}
	case 242:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1511
		{
			returns := yyDollar[7].returntype.types
			if yyDollar[7].returntype.known && returns == nil {
				returns = []ast.TypeExpr{}
			}
			typ := &ast.FunctionTypeExpr{TypeParams: yyDollar[3].typeparams, Params: toFuncParams(yyDollar[5].typednames), Returns: returns}
			typ.SetPosFromToken(yyDollar[1].token.Pos)
			if yyDollar[7].returntype.end.Line != 0 {
				typ.SetLastPosFromToken(yyDollar[7].returntype.end)
			} else {
				typ.SetLastPosFromToken(yyDollar[6].token.Pos)
			}
			yyVAL.ifacemember = ast.InterfaceMember{
				Kind: ast.InterfaceMethodMember,
				Name: yyDollar[2].token.Str, NamePosition: yyDollar[2].token.Pos, Type: typ,
			}
		}
	}
	goto yystack /* stack new state and value */
}
