// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package parse

import __yyfmt__ "fmt"

//line parser.go.y:2

import (
	"github.com/wippyai/go-lua/compiler/ast"
	"github.com/wippyai/go-lua/compiler/parse/numparse"
)

func setLastPosFromExprs(node ast.PositionHolder, exprs []ast.Expr, fallback ast.PositionHolder) {
	if node == nil {
		return
	}
	if len(exprs) > 0 {
		node.CopyLastPos(exprs[len(exprs)-1])
		return
	}
	if fallback != nil {
		node.CopyLastPos(fallback)
	}
}

//line parser.go.y:71
type yySymType struct {
	yys   int
	token ast.Token

	stmts []ast.Stmt
	stmt  ast.Stmt

	funcname *ast.FuncName
	funcexpr *ast.FunctionExpr

	exprlist []ast.Expr
	expr     ast.Expr

	fieldlist []*ast.Field
	field     *ast.Field
	fieldsep  string
	fieldname string

	namelist []nameWithPos
	parlist  *ast.ParList

	typeexpr     ast.TypeExpr
	typeexprlist []ast.TypeExpr
	typeparam    ast.TypeParamExpr
	typeparams   []ast.TypeParamExpr
	recordfield  ast.RecordFieldExpr
	recordfields []ast.RecordFieldExpr
	typedname    typedNameEntry
	typednames   []typedNameEntry
	ifacemethod  ast.InterfaceMethodExpr
	ifacemethods []ast.InterfaceMethodExpr
	typereflist  []*ast.TypeRefExpr
	funcparam    ast.FunctionParamExpr
	funcparams   []ast.FunctionParamExpr
	annotation   ast.AnnotationExpr
	annotations  []ast.AnnotationExpr
}

const TAnd = 57346
const TBreak = 57347
const TDo = 57348
const TElse = 57349
const TElseIf = 57350
const TEnd = 57351
const TFalse = 57352
const TFor = 57353
const TFunction = 57354
const TIf = 57355
const TIn = 57356
const TLocal = 57357
const TNil = 57358
const TNot = 57359
const TOr = 57360
const TReturn = 57361
const TRepeat = 57362
const TThen = 57363
const TTrue = 57364
const TUntil = 57365
const TWhile = 57366
const TGoto = 57367
const TType = 57368
const TInterface = 57369
const TReadonly = 57370
const TAs = 57371
const TAsserts = 57372
const TIs = 57373
const TTypeof = 57374
const TKeyof = 57375
const TExtends = 57376
const TFun = 57377
const TEqeq = 57378
const TNeq = 57379
const TLte = 57380
const TGte = 57381
const T2Comma = 57382
const T3Comma = 57383
const T2Colon = 57384
const TLabel = 57385
const TIdent = 57386
const TNumber = 57387
const TString = 57388
const TShl = 57389
const TShr = 57390
const TIdiv = 57391
const TArrow = 57392
const TQuestion = 57393
const TBang = 57394
const TQuestionColon = 57395
const UNARY = 57396

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"TAnd",
	"TBreak",
	"TDo",
	"TElse",
	"TElseIf",
	"TEnd",
	"TFalse",
	"TFor",
	"TFunction",
	"TIf",
	"TIn",
	"TLocal",
	"TNil",
	"TNot",
	"TOr",
	"TReturn",
	"TRepeat",
	"TThen",
	"TTrue",
	"TUntil",
	"TWhile",
	"TGoto",
	"TType",
	"TInterface",
	"TReadonly",
	"TAs",
	"TAsserts",
	"TIs",
	"TTypeof",
	"TKeyof",
	"TExtends",
	"TFun",
	"TEqeq",
	"TNeq",
	"TLte",
	"TGte",
	"T2Comma",
	"T3Comma",
	"T2Colon",
	"TLabel",
	"TIdent",
	"TNumber",
	"TString",
	"'{'",
	"'}'",
	"'('",
	"')'",
	"TShl",
	"TShr",
	"TIdiv",
	"'['",
	"']'",
	"TArrow",
	"TQuestion",
	"TBang",
	"TQuestionColon",
	"'>'",
	"'<'",
	"'|'",
	"'~'",
	"'&'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARY",
	"'^'",
	"';'",
	"'='",
	"','",
	"':'",
	"'.'",
	"'#'",
	"'@'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:1305

// nameWithPos holds a name with its token position
type nameWithPos struct {
	Name string
	Pos  ast.Position
}

// splitNameList extracts names and positions from nameWithPos entries
func splitNameList(entries []nameWithPos) ([]string, []ast.Position) {
	names := make([]string, len(entries))
	positions := make([]ast.Position, len(entries))
	for i, e := range entries {
		names[i] = e.Name
		positions[i] = e.Pos
	}
	return names, positions
}

// typedNameEntry holds a name with optional type annotation
type typedNameEntry struct {
	Name string
	Pos  ast.Position
	Type ast.TypeExpr
}

// splitTypedNames extracts names, positions, and types from typed name entries
func splitTypedNames(entries []typedNameEntry) ([]string, []ast.Position, []ast.TypeExpr) {
	names := make([]string, len(entries))
	positions := make([]ast.Position, len(entries))
	var types []ast.TypeExpr
	hasTypes := false
	for i, e := range entries {
		names[i] = e.Name
		positions[i] = e.Pos
		if e.Type != nil {
			hasTypes = true
		}
	}
	if hasTypes {
		types = make([]ast.TypeExpr, len(entries))
		for i, e := range entries {
			types[i] = e.Type
		}
	}
	return names, positions, types
}

// toFuncParams converts typedNameEntry slice to FunctionParamExpr slice
func toFuncParams(entries []typedNameEntry) []ast.FunctionParamExpr {
	params := make([]ast.FunctionParamExpr, len(entries))
	for i, e := range entries {
		params[i] = ast.FunctionParamExpr{Name: e.Name, Type: e.Type}
	}
	return params
}

func TokenName(c int) string {
	if c >= TAnd && c-TAnd < len(yyToknames) {
		if yyToknames[c-TAnd] != "" {
			return yyToknames[c-TAnd]
		}
	}
	return string([]byte{byte(c)})
}

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 21,
	73, 42,
	74, 42,
	-2, 95,
	-1, 113,
	73, 130,
	-2, 44,
	-1, 123,
	73, 43,
	74, 43,
	-2, 95,
}

const yyPrivate = 57344

const yyLast = 1887

var yyAct = [...]int16{
	425, 424, 317, 205, 55, 26, 288, 277, 262, 208,
	67, 109, 260, 185, 252, 202, 103, 58, 253, 255,
	66, 254, 274, 257, 324, 27, 43, 44, 248, 52,
	249, 324, 289, 257, 48, 150, 151, 57, 256, 59,
	323, 36, 255, 461, 255, 429, 257, 323, 256, 35,
	72, 53, 122, 489, 96, 51, 49, 415, 141, 54,
	333, 256, 50, 99, 100, 101, 102, 97, 401, 248,
	112, 249, 326, 248, 125, 249, 53, 450, 95, 149,
	389, 296, 444, 98, 54, 451, 303, 290, 325, 159,
	155, 371, 86, 87, 88, 74, 89, 184, 201, 360,
	162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
	172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
	182, 183, 291, 210, 7, 10, 246, 486, 483, 393,
	14, 15, 13, 248, 16, 249, 481, 215, 6, 12,
	478, 390, 244, 11, 18, 434, 20, 213, 225, 212,
	227, 450, 371, 229, 74, 322, 242, 243, 214, 240,
	450, 106, 17, 19, 450, 241, 53, 322, 24, 239,
	226, 146, 228, 156, 54, 53, 53, 53, 53, 53,
	53, 53, 373, 54, 54, 54, 54, 54, 54, 54,
	372, 5, 96, 471, 258, 280, 217, 218, 219, 220,
	221, 222, 223, 83, 371, 97, 153, 154, 147, 468,
	294, 449, 445, 29, 388, 41, 95, 450, 385, 28,
	38, 98, 292, 297, 295, 30, 25, 327, 84, 85,
	86, 87, 88, 154, 89, 450, 74, 112, 328, 321,
	298, 105, 328, 224, 32, 304, 96, 45, 31, 43,
	44, 328, 24, 412, 314, 46, 47, 490, 318, 97,
	320, 367, 309, 310, 311, 322, 40, 74, 148, 37,
	248, 248, 249, 249, 312, 98, 432, 280, 329, 332,
	39, 251, 280, 248, 344, 249, 104, 349, 89, 476,
	318, 354, 352, 351, 350, 336, 346, 359, 106, 330,
	357, 248, 241, 249, 334, 358, 470, 456, 365, 374,
	492, 348, 157, 488, 356, 250, 248, 426, 249, 248,
	248, 249, 249, 396, 376, 377, 378, 379, 364, 280,
	384, 375, 368, 391, 387, 248, 381, 249, 251, 248,
	386, 249, 319, 380, 68, 487, 392, 248, 394, 249,
	442, 329, 287, 477, 400, 397, 248, 161, 249, 329,
	45, 410, 403, 402, 29, 24, 41, 405, 411, 369,
	28, 38, 414, 286, 285, 413, 30, 43, 44, 204,
	52, 421, 68, 422, 281, 206, 404, 428, 293, 406,
	430, 416, 417, 418, 419, 32, 283, 282, 45, 31,
	43, 44, 435, 24, 140, 34, 204, 436, 9, 68,
	42, 65, 440, 21, 443, 203, 446, 40, 355, 366,
	37, 68, 447, 209, 284, 316, 315, 453, 308, 455,
	457, 39, 247, 460, 441, 318, 68, 462, 312, 312,
	312, 312, 238, 68, 464, 469, 230, 152, 71, 467,
	70, 472, 473, 124, 474, 69, 64, 60, 123, 347,
	480, 29, 482, 41, 144, 23, 305, 28, 38, 307,
	491, 484, 465, 30, 463, 485, 438, 114, 115, 116,
	117, 118, 119, 437, 120, 121, 433, 76, 409, 407,
	73, 398, 32, 300, 142, 113, 31, 43, 44, 107,
	24, 75, 362, 363, 361, 111, 232, 233, 234, 235,
	236, 237, 96, 370, 40, 56, 1, 37, 158, 81,
	82, 80, 79, 83, 231, 97, 306, 245, 39, 207,
	186, 264, 110, 211, 93, 94, 95, 108, 33, 22,
	61, 98, 8, 77, 78, 91, 92, 90, 84, 85,
	86, 87, 88, 29, 89, 41, 63, 408, 62, 28,
	38, 3, 301, 4, 2, 30, 0, 0, 0, 114,
	115, 116, 117, 118, 119, 0, 120, 121, 0, 76,
	0, 0, 0, 0, 32, 0, 0, 113, 31, 43,
	44, 0, 24, 75, 0, 0, 0, 111, 134, 135,
	136, 137, 138, 139, 96, 0, 40, 0, 0, 37,
	0, 81, 82, 80, 79, 83, 133, 97, 0, 0,
	39, 0, 0, 0, 0, 0, 93, 94, 95, 0,
	0, 0, 0, 98, 0, 77, 78, 91, 92, 90,
	84, 85, 86, 87, 88, 76, 89, 466, 0, 302,
	270, 339, 340, 271, 341, 272, 343, 342, 273, 75,
	0, 0, 0, 0, 0, 0, 0, 0, 338, 0,
	96, 0, 337, 0, 0, 0, 0, 81, 82, 80,
	79, 83, 0, 97, 0, 0, 0, 0, 0, 0,
	0, 0, 93, 94, 95, 0, 0, 76, 0, 98,
	0, 77, 78, 91, 92, 90, 84, 85, 86, 87,
	88, 75, 89, 0, 439, 0, 127, 128, 129, 130,
	131, 132, 96, 0, 0, 0, 0, 0, 0, 81,
	82, 80, 79, 83, 126, 97, 0, 0, 76, 0,
	0, 0, 0, 0, 93, 94, 95, 0, 0, 0,
	0, 98, 75, 77, 78, 91, 92, 90, 84, 85,
	86, 87, 88, 96, 89, 0, 0, 0, 0, 0,
	81, 82, 80, 79, 83, 0, 97, 0, 0, 76,
	0, 0, 0, 0, 395, 93, 94, 95, 0, 0,
	0, 0, 98, 75, 77, 78, 91, 92, 90, 84,
	85, 86, 87, 88, 96, 89, 0, 0, 0, 0,
	0, 81, 82, 80, 79, 83, 0, 97, 0, 0,
	76, 0, 0, 0, 0, 0, 93, 94, 95, 0,
	299, 0, 0, 98, 75, 77, 78, 91, 92, 90,
	84, 85, 86, 87, 88, 96, 89, 0, 0, 0,
	0, 0, 81, 82, 80, 79, 83, 0, 97, 0,
	0, 76, 0, 0, 0, 0, 0, 93, 94, 95,
	0, 216, 0, 0, 98, 75, 77, 78, 91, 92,
	90, 84, 85, 86, 87, 88, 96, 89, 0, 0,
	0, 0, 0, 81, 82, 80, 79, 83, 0, 97,
	0, 0, 0, 0, 0, 0, 0, 160, 93, 94,
	95, 0, 0, 76, 0, 98, 0, 77, 78, 91,
	92, 90, 84, 85, 86, 87, 88, 75, 89, 0,
	145, 0, 0, 0, 0, 0, 0, 0, 96, 0,
	0, 0, 0, 0, 0, 81, 82, 80, 79, 83,
	0, 97, 0, 0, 76, 0, 143, 0, 0, 0,
	93, 94, 95, 0, 0, 0, 0, 98, 75, 77,
	78, 91, 92, 90, 84, 85, 86, 87, 88, 96,
	89, 0, 0, 0, 0, 0, 81, 82, 80, 79,
	83, 0, 97, 0, 0, 76, 0, 0, 0, 0,
	0, 93, 94, 95, 0, 0, 0, 0, 98, 75,
	77, 78, 91, 92, 90, 84, 85, 86, 87, 88,
	96, 89, 0, 0, 0, 0, 0, 81, 82, 80,
	79, 83, 0, 97, 0, 0, 76, 0, 0, 0,
	0, 0, 93, 94, 95, 0, 0, 0, 0, 98,
	0, 77, 78, 91, 92, 90, 84, 85, 86, 87,
	88, 96, 89, 0, 0, 0, 0, 0, 81, 82,
	80, 79, 83, 0, 97, 0, 0, 0, 0, 0,
	0, 0, 0, 93, 94, 95, 0, 0, 0, 0,
	98, 0, 77, 78, 91, 92, 90, 84, 85, 86,
	87, 88, 96, 89, 0, 0, 0, 0, 0, 81,
	82, 80, 79, 83, 0, 97, 29, 0, 41, 0,
	0, 0, 28, 38, 93, 94, 95, 0, 30, 0,
	0, 98, 0, 77, 78, 91, 92, 90, 84, 85,
	86, 87, 88, 0, 89, 0, 0, 32, 0, 0,
	45, 31, 43, 44, 0, 24, 0, 96, 270, 339,
	340, 271, 341, 272, 343, 342, 273, 0, 83, 40,
	97, 0, 37, 0, 0, 0, 338, 0, 0, 93,
	94, 95, 0, 39, 0, 0, 98, 96, 0, 0,
	91, 92, 90, 84, 85, 86, 87, 88, 83, 89,
	97, 0, 0, 0, 0, 0, 0, 0, 0, 93,
	94, 95, 0, 0, 0, 0, 98, 96, 0, 0,
	0, 92, 90, 84, 85, 86, 87, 88, 83, 89,
	97, 0, 0, 0, 0, 0, 0, 0, 96, 93,
	94, 95, 0, 0, 0, 0, 98, 0, 0, 83,
	0, 97, 90, 84, 85, 86, 87, 88, 0, 89,
	93, 94, 95, 0, 0, 0, 0, 98, 0, 0,
	0, 0, 0, 189, 84, 85, 86, 87, 88, 187,
	89, 0, 0, 0, 0, 188, 0, 0, 0, 270,
	265, 266, 271, 267, 272, 268, 269, 273, 195, 0,
	0, 0, 0, 0, 0, 0, 0, 263, 191, 190,
	193, 261, 194, 189, 0, 0, 0, 259, 0, 187,
	0, 0, 0, 0, 0, 188, 0, 0, 0, 270,
	265, 266, 271, 267, 272, 268, 269, 273, 195, 0,
	0, 0, 0, 0, 0, 0, 0, 263, 191, 190,
	193, 0, 194, 189, 0, 0, 0, 345, 0, 187,
	0, 0, 0, 0, 0, 188, 0, 0, 0, 0,
	196, 197, 0, 198, 0, 199, 200, 0, 195, 189,
	0, 0, 0, 0, 0, 187, 0, 192, 191, 190,
	193, 188, 194, 0, 0, 0, 196, 197, 313, 198,
	0, 199, 200, 0, 195, 189, 0, 0, 0, 0,
	278, 187, 0, 279, 191, 190, 193, 188, 276, 479,
	0, 0, 196, 197, 0, 198, 0, 199, 200, 0,
	195, 189, 0, 0, 0, 0, 278, 187, 0, 279,
	191, 190, 193, 188, 276, 475, 0, 0, 196, 197,
	0, 198, 0, 199, 200, 0, 195, 189, 0, 0,
	0, 0, 278, 187, 0, 279, 191, 190, 193, 188,
	276, 459, 0, 0, 196, 197, 0, 198, 0, 199,
	200, 0, 195, 189, 0, 0, 0, 0, 278, 187,
	0, 279, 191, 190, 193, 188, 276, 454, 0, 0,
	196, 197, 0, 198, 0, 199, 200, 0, 195, 189,
	0, 0, 0, 0, 278, 187, 0, 279, 191, 190,
	193, 188, 276, 448, 0, 0, 196, 197, 0, 198,
	0, 199, 200, 0, 195, 189, 0, 0, 0, 0,
	278, 187, 0, 279, 191, 190, 193, 188, 276, 423,
	0, 0, 196, 197, 0, 198, 0, 199, 200, 0,
	195, 189, 0, 0, 0, 0, 278, 187, 0, 279,
	191, 190, 193, 188, 276, 399, 0, 0, 196, 197,
	0, 198, 0, 199, 200, 0, 195, 189, 0, 0,
	0, 0, 278, 187, 0, 279, 191, 190, 193, 188,
	194, 335, 0, 0, 196, 197, 0, 198, 0, 199,
	200, 0, 195, 189, 0, 0, 0, 0, 278, 187,
	0, 279, 191, 190, 193, 188, 276, 331, 0, 0,
	196, 197, 0, 198, 0, 199, 200, 0, 195, 189,
	0, 0, 0, 0, 278, 187, 0, 279, 191, 190,
	193, 188, 276, 275, 0, 0, 196, 197, 0, 198,
	0, 199, 200, 0, 195, 189, 0, 0, 0, 0,
	382, 187, 0, 279, 191, 190, 193, 188, 194, 0,
	0, 0, 196, 197, 0, 198, 0, 199, 200, 0,
	195, 189, 0, 0, 0, 0, 0, 187, 0, 192,
	191, 190, 193, 188, 194, 0, 0, 0, 196, 197,
	0, 198, 0, 199, 200, 0, 195, 189, 0, 0,
	0, 0, 0, 187, 0, 192, 191, 190, 193, 188,
	458, 0, 0, 0, 196, 197, 0, 198, 0, 199,
	200, 0, 195, 189, 0, 0, 0, 0, 0, 187,
	0, 192, 191, 190, 193, 188, 452, 0, 0, 0,
	196, 197, 0, 198, 0, 199, 200, 0, 195, 189,
	0, 0, 0, 0, 0, 187, 0, 192, 191, 190,
	193, 188, 431, 0, 0, 0, 196, 197, 0, 198,
	0, 199, 200, 0, 195, 189, 0, 0, 0, 0,
	0, 187, 0, 192, 191, 190, 193, 188, 427, 0,
	0, 0, 196, 197, 0, 198, 0, 199, 200, 0,
	195, 189, 0, 0, 0, 0, 0, 187, 0, 192,
	191, 190, 193, 188, 420, 0, 0, 0, 196, 197,
	0, 198, 0, 199, 200, 0, 195, 189, 0, 0,
	0, 0, 0, 187, 0, 192, 191, 190, 193, 188,
	383, 0, 0, 0, 196, 197, 0, 198, 0, 199,
	200, 0, 195, 0, 0, 0, 0, 0, 0, 0,
	0, 192, 191, 190, 193, 0, 353,
}

var yyPact = [...]int16{
	-1000, -1000, 119, 154, -1000, -1000, 1106, -1000, 182, -20,
	-1000, 1106, -1000, 1106, 413, 412, 399, -1000, 411, 406,
	404, -1000, -1000, -1000, 1106, -1000, 21, 991, -1000, -1000,
	-1000, -1000, -1000, -1000, -20, -1000, -1000, 1106, 1106, 1106,
	1106, 237, -1000, -1000, 451, -1000, 1106, 316, 1106, 690,
	-1000, 572, 354, -1000, -1000, 485, -1000, 950, 441, 909,
	98, 194, 237, -40, -1000, 403, 133, -1000, 15, -1000,
	100, 14, 857, 307, 1106, 1106, 1106, 1106, 1106, 1106,
	1106, 1106, 1106, 1106, 1106, 1106, 1106, 1106, 1106, 1106,
	1106, 1106, 1106, 1106, 1106, 1106, 1655, 1655, -1000, 217,
	217, 217, 217, -1000, 365, 336, 379, -1000, 75, -1000,
	85, 1106, 991, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 21, -1000, -20, 816, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 331, 331, 331, 331, 331, 331, 331,
	-1000, 193, -1000, -1000, 1106, -1000, 1106, 1106, 402, -1000,
	480, 398, 237, 1106, 392, 1655, 1655, 69, 52, 388,
	-1000, -1000, 991, 1032, 1073, 1128, 1128, 1128, 1128, 1128,
	1128, 163, 25, 25, 217, 217, 217, 217, 1209, 1158,
	1188, 163, 163, 217, -1000, 281, -36, -1000, -1000, -1000,
	-1000, -1000, -38, 1263, 1603, 335, 350, 349, 380, 325,
	324, -1000, 302, -43, 12, 48, 338, 150, -1000, 6,
	-1000, 543, -1000, -1000, 1106, 775, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 484, 991, -1000, 575, 80,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	21, -1000, 208, 208, 1655, 457, 384, -1000, 1655, 1655,
	1655, -1000, -59, 1343, -1000, 382, 381, 1655, 294, 1655,
	191, -1000, -1000, -28, 13, 350, 349, 380, 325, 324,
	-1000, -1000, -1000, -1000, 177, 222, 1577, -1000, 1655, -15,
	208, 1551, 624, 1303, 428, 1106, 1655, -43, -1000, 1837,
	1655, 377, 264, -43, -1000, 379, 1655, -1000, 991, 26,
	-1000, 495, 1106, -1000, 208, -1000, -1000, 375, -1000, 224,
	224, 204, -1000, -1000, 277, 320, -1000, 130, 208, -1000,
	254, -1000, 1132, 1655, 1655, 1655, 1655, 287, 1629, 1811,
	168, 284, 208, 1655, 164, 5, 93, -1000, -35, -1000,
	-1000, -1000, -1000, -1000, 285, 1655, 81, 1655, 734, 273,
	-1000, 482, 17, 1525, 208, -7, -43, -1000, -1000, 208,
	1106, -1000, -1000, 1106, 483, 479, 312, 1655, -1000, 203,
	-1000, 1655, -1000, -1000, -18, -1000, -34, -34, -34, -34,
	1785, -1000, 1655, 1499, 208, 261, 1759, 208, -30, 1733,
	-1000, -1000, 221, -1000, 208, -1000, -1000, 477, -1000, 222,
	71, 1655, -1000, 474, 991, 467, 693, -1000, 1106, -1000,
	300, 7, -1000, 162, 208, 1655, -59, -59, -59, -59,
	1473, 208, 208, 222, 161, 11, 1707, 1447, 257, 1681,
	208, 1421, -32, -1000, 1655, 208, 465, -1000, -1000, -1000,
	463, 641, -43, 159, 1655, -1000, 258, 143, 222, -1000,
	1655, 1655, 1395, 239, 303, 90, -1000, 208, 1369, 222,
	86, 1655, 78, -1000, -1000, -1000, -1000, -1000, -43, 208,
	-1000, -1000, 208, 208, 77, 295, -1000, -1000, 263, 222,
	3, -1000, 209, -1000, 461, -1000, 260, -1000, -1000, -1000,
	-1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 515, 564, 4, 563, 562, 561, 558, 556, 542,
	410, 540, 5, 25, 49, 405, 465, 539, 62, 538,
	16, 15, 41, 537, 11, 533, 532, 531, 0, 13,
	530, 2, 1, 6, 241, 529, 9, 12, 8, 3,
	10, 527, 526, 518, 7, 22, 21, 14, 513,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 2, 2, 2, 3, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 5, 5, 6,
	6, 6, 7, 7, 7, 7, 7, 7, 7, 7,
	8, 8, 9, 9, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 11, 11, 12, 12, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 14, 15, 15, 15, 15, 17,
	16, 16, 16, 16, 16, 16, 16, 16, 18, 18,
	18, 18, 19, 20, 20, 20, 20, 21, 21, 21,
	21, 21, 22, 22, 23, 23, 23, 24, 24, 24,
	26, 26, 26, 26, 26, 26, 26, 26, 26, 27,
	27, 27, 27, 27, 27, 27, 27, 27, 25, 25,
	33, 33, 33, 33, 28, 28, 28, 28, 29, 29,
	29, 30, 30, 30, 30, 30, 30, 30, 30, 30,
	30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
	30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
	30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
	30, 30, 30, 30, 31, 31, 32, 32, 48, 48,
	44, 44, 45, 45, 45, 45, 37, 37, 37, 38,
	38, 38, 38, 38, 38, 38, 38, 47, 47, 46,
	46, 46, 34, 35, 35, 36, 36, 39, 39, 40,
	40, 43, 43, 43, 41, 41, 42, 42,
}

var yyR2 = [...]int8{
	0, 1, 2, 3, 0, 2, 2, 1, 3, 1,
	3, 5, 4, 6, 8, 9, 11, 7, 3, 4,
	4, 2, 1, 2, 4, 5, 5, 0, 5, 1,
	2, 1, 1, 3, 3, 3, 3, 3, 3, 3,
	1, 3, 1, 3, 1, 4, 3, 3, 3, 3,
	3, 3, 3, 1, 3, 1, 3, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 2, 2, 2,
	2, 3, 3, 2, 1, 1, 1, 1, 3, 3,
	2, 4, 4, 4, 4, 4, 4, 4, 2, 3,
	1, 1, 2, 6, 5, 7, 6, 1, 3, 1,
	3, 5, 2, 3, 1, 3, 2, 3, 5, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	0, 2, 3, 6, 1, 3, 3, 7, 1, 2,
	2, 1, 1, 1, 1, 1, 1, 3, 4, 3,
	7, 3, 7, 6, 5, 6, 4, 5, 7, 6,
	9, 8, 8, 7, 6, 8, 5, 7, 7, 6,
	4, 3, 4, 3, 3, 4, 8, 4, 2, 2,
	4, 4, 4, 4, 1, 3, 3, 3, 1, 1,
	3, 1, 1, 3, 2, 4, 1, 3, 2, 3,
	4, 3, 4, 3, 4, 3, 4, 1, 2, 2,
	4, 5, 3, 1, 3, 1, 3, 1, 3, 1,
	3, 0, 2, 3, 0, 2, 5, 6,
}

var yyChk = [...]int16{
	-1000, -1, -2, -6, -4, 72, 19, 5, -9, -15,
	6, 24, 20, 13, 11, 12, 15, 43, 25, 44,
	27, -10, -17, -16, 49, 72, -12, -13, 16, 10,
	22, 45, 41, -19, -15, -14, -22, 66, 17, 77,
	63, 12, -10, 46, 47, 44, 73, 74, 54, 76,
	-18, 75, 49, -22, -14, -3, -1, -13, -3, -13,
	44, -11, -7, -8, 44, 12, -39, -40, 44, 44,
	44, 44, -13, -16, 74, 18, 4, 60, 61, 39,
	38, 36, 37, 40, 65, 66, 67, 68, 69, 71,
	64, 62, 63, 51, 52, 53, 29, 42, 58, -13,
	-13, -13, -13, -20, 49, -34, 61, 48, -23, -24,
	-26, 54, -13, 44, 26, 27, 28, 29, 30, 31,
	33, 34, -12, -10, -15, -13, 44, 26, 27, 28,
	29, 30, 31, 44, 26, 27, 28, 29, 30, 31,
	50, -12, 9, 6, 23, 21, 73, 14, 74, -20,
	75, 76, 44, 73, 74, 75, 73, -34, -43, 75,
	50, 50, -13, -13, -13, -13, -13, -13, -13, -13,
	-13, -13, -13, -13, -13, -13, -13, -13, -13, -13,
	-13, -13, -13, -13, -28, -29, -30, 16, 22, 10,
	46, 45, 44, 47, 49, 35, 27, 28, 30, 32,
	33, -28, -21, 50, 41, -39, 49, -35, -36, 44,
	48, -25, 74, 72, 73, -13, 55, -18, -18, -18,
	-18, -18, -18, -18, 50, -3, -13, -3, -13, -12,
	44, 44, 26, 27, 28, 29, 30, 31, 44, -20,
	-12, -40, -28, -28, 73, -41, 74, 44, 62, 64,
	34, 57, -47, 54, -46, 78, 76, 61, -28, 54,
	-37, 48, -38, 44, -27, 27, 28, 30, 32, 33,
	26, 29, 31, 34, -45, 50, 49, -44, 41, 44,
	-28, 49, 47, 47, 44, 49, 49, 50, -33, 75,
	75, 74, -21, 50, 60, 74, 75, -24, -13, 55,
	9, -5, 74, 6, -28, 9, -42, 12, 44, -29,
	-29, -29, -46, 55, -28, 44, 44, -31, -28, 48,
	-28, 48, 74, 75, 59, 75, 59, 50, 74, 56,
	-45, 50, -28, 75, -45, 50, -37, 48, 44, 27,
	28, 30, 33, 32, -28, 54, -37, 31, -13, -28,
	-33, -3, -31, 49, -28, 41, 50, -33, -36, -28,
	73, 9, 7, 8, -13, -3, 44, 57, 55, 49,
	-48, 74, 60, 52, 55, -38, -28, -28, -28, -28,
	56, -44, 41, 49, -28, 50, 56, -28, 50, 75,
	48, 48, -28, 48, -28, 50, 50, -3, 9, 50,
	-28, 75, -33, -3, -13, -3, -13, 6, 74, 9,
	49, -28, 50, -12, -28, 75, -47, -47, -47, -47,
	49, -28, -28, 50, -32, -28, 56, 49, -28, 75,
	-28, 49, 55, 9, 74, -28, -3, 9, 9, 21,
	-3, -13, 50, -39, 75, 50, -28, -32, 50, 50,
	74, 74, 49, -28, 50, -32, 50, -28, 49, 50,
	-32, 75, -31, 9, -3, 9, 6, -33, 50, -28,
	48, 50, -28, -28, -32, 50, 50, 50, 50, 50,
	-32, 50, -28, 50, -3, -33, 50, 50, 50, 50,
	48, 9, 50,
}

var yyDef = [...]int16{
	4, -2, 1, 2, 5, 6, 29, 31, 0, 9,
	4, 0, 4, 0, 0, 0, 0, 22, 0, 44,
	0, -2, 96, 97, 0, 3, 30, 55, 57, 58,
	59, 60, 61, 62, 63, 64, 65, 0, 0, 0,
	0, 0, 95, 94, 0, 44, 0, 0, 0, 0,
	100, 0, 0, 110, 111, 0, 7, 0, 0, 0,
	53, 0, 0, 32, 40, 0, 21, 237, 239, 23,
	0, 241, 0, 97, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 93, 87,
	88, 89, 90, 112, 0, 0, 0, 122, 0, 124,
	0, 0, 129, -2, 131, 132, 133, 134, 135, 136,
	137, 138, 8, -2, 0, 0, 46, 47, 48, 49,
	50, 51, 52, 0, 0, 0, 0, 0, 0, 0,
	108, 0, 10, 4, 0, 4, 0, 0, 0, 18,
	0, 0, 0, 0, 0, 0, 0, 0, 244, 0,
	98, 99, 56, 66, 67, 68, 69, 70, 71, 72,
	73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
	83, 84, 85, 86, 91, 154, 158, 161, 162, 163,
	164, 165, 166, 0, 0, 0, 0, 0, 0, 0,
	0, 92, 0, 150, 117, 119, 0, 0, 233, 235,
	123, 126, 148, 149, 0, 0, 45, 101, 102, 103,
	104, 105, 106, 107, 109, 0, 12, 27, 0, 0,
	54, 33, 34, 35, 36, 37, 38, 39, 41, 19,
	20, 238, 240, 24, 0, 0, 0, 242, 0, 0,
	0, 160, 159, 0, 227, 0, 0, 0, 0, 0,
	0, 198, 216, 166, 0, 140, 141, 143, 147, 145,
	139, 142, 144, 146, 0, 0, 0, 212, 0, 166,
	211, 0, 0, 0, 199, 0, 0, 150, 4, 0,
	0, 0, 0, 150, 232, 0, 0, 125, 127, 0,
	11, 0, 0, 4, 25, 26, 245, 0, 243, 155,
	156, 0, 228, 194, 0, 229, 167, 0, 204, 169,
	0, 171, 218, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 214, 0, 0, 191, 0, 193, 0, 140,
	141, 143, 145, 147, 0, 0, 0, 0, 0, 0,
	4, 0, 151, 0, 118, 120, 150, 4, 234, 236,
	0, 13, 4, 0, 0, 0, 0, 160, 203, 0,
	168, 0, 208, 209, 0, 217, 219, 221, 223, 225,
	0, 213, 0, 0, 176, 0, 0, 210, 190, 0,
	192, 195, 0, 197, 200, 201, 202, 0, 114, 152,
	211, 0, 4, 0, 128, 0, 0, 4, 0, 17,
	0, 0, 230, 0, 205, 0, 220, 222, 224, 226,
	0, 174, 215, 177, 0, 211, 0, 0, 176, 0,
	186, 0, 0, 113, 0, 121, 0, 116, 14, 4,
	0, 0, 150, 0, 0, 231, 0, 0, 173, 175,
	0, 0, 0, 174, 177, 0, 179, 184, 0, 189,
	0, 0, 0, 115, 28, 15, 4, 246, 150, 157,
	170, 172, 207, 206, 0, 173, 178, 183, 175, 188,
	0, 187, 0, 153, 0, 247, 172, 181, 182, 185,
	196, 16, 180,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 77, 3, 69, 64, 3,
	49, 50, 67, 65, 74, 66, 76, 68, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 75, 72,
	61, 73, 60, 3, 78, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 54, 3, 55, 71, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 47, 62, 48, 63,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 51, 52, 53, 56, 57,
	58, 59, 70,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:154
		{
			yyVAL.stmts = yyDollar[1].stmts
			if l, ok := yylex.(*Lexer); ok {
				l.Stmts = yyVAL.stmts
			}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:160
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
			if l, ok := yylex.(*Lexer); ok {
				l.Stmts = yyVAL.stmts
			}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:166
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
			if l, ok := yylex.(*Lexer); ok {
				l.Stmts = yyVAL.stmts
			}
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:174
		{
			yyVAL.stmts = []ast.Stmt{}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:177
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:180
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:185
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:190
		{
			yyVAL.stmt = &ast.AssignStmt{Lhs: yyDollar[1].exprlist, Rhs: yyDollar[3].exprlist}
			yyVAL.stmt.CopyPos(yyDollar[1].exprlist[0])
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:195
		{
			if _, ok := yyDollar[1].expr.(*ast.FuncCallExpr); !ok {
				yylex.(*Lexer).Error("parse error")
			} else {
				yyVAL.stmt = &ast.FuncCallStmt{Expr: yyDollar[1].expr}
				yyVAL.stmt.CopyPos(yyDollar[1].expr)
			}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:203
		{
			yyVAL.stmt = &ast.DoBlockStmt{Stmts: yyDollar[2].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:208
		{
			yyVAL.stmt = &ast.WhileStmt{Condition: yyDollar[2].expr, Stmts: yyDollar[4].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[5].token.Pos)
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:213
		{
			yyVAL.stmt = &ast.RepeatStmt{Condition: yyDollar[4].expr, Stmts: yyDollar[2].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastLine(yyDollar[4].expr.Line())
		}
	case 13:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:218
		{
			yyVAL.stmt = &ast.IfStmt{Condition: yyDollar[2].expr, Then: yyDollar[4].stmts, EndPosition: yyDollar[6].token.Pos}
			cur := yyVAL.stmt
			for _, elseif := range yyDollar[5].stmts {
				cur.(*ast.IfStmt).Else = []ast.Stmt{elseif}
				cur = elseif
			}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[6].token.Pos)
		}
	case 14:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:228
		{
			yyVAL.stmt = &ast.IfStmt{Condition: yyDollar[2].expr, Then: yyDollar[4].stmts, EndPosition: yyDollar[8].token.Pos}
			cur := yyVAL.stmt
			for _, elseif := range yyDollar[5].stmts {
				cur.(*ast.IfStmt).Else = []ast.Stmt{elseif}
				cur = elseif
			}
			cur.(*ast.IfStmt).Else = yyDollar[7].stmts
			cur.(*ast.IfStmt).HasElse = true
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[8].token.Pos)
		}
	case 15:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:240
		{
			yyVAL.stmt = &ast.NumberForStmt{Name: yyDollar[2].token.Str, NamePosition: yyDollar[2].token.Pos, Init: yyDollar[4].expr, Limit: yyDollar[6].expr, Stmts: yyDollar[8].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[9].token.Pos)
		}
	case 16:
		yyDollar = yyS[yypt-11 : yypt+1]
//line parser.go.y:245
		{
			yyVAL.stmt = &ast.NumberForStmt{Name: yyDollar[2].token.Str, NamePosition: yyDollar[2].token.Pos, Init: yyDollar[4].expr, Limit: yyDollar[6].expr, Step: yyDollar[8].expr, Stmts: yyDollar[10].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[11].token.Pos)
		}
	case 17:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:250
		{
			names, positions := splitNameList(yyDollar[2].namelist)
			yyVAL.stmt = &ast.GenericForStmt{Names: names, NamePositions: positions, Exprs: yyDollar[4].exprlist, Stmts: yyDollar[6].stmts}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[7].token.Pos)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:256
		{
			yyVAL.stmt = &ast.FuncDefStmt{Name: yyDollar[2].funcname, Func: yyDollar[3].funcexpr}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.CopyLastPos(yyDollar[3].funcexpr)
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:261
		{
			yyVAL.stmt = &ast.LocalAssignStmt{Names: []string{yyDollar[3].token.Str}, NamePositions: []ast.Position{yyDollar[3].token.Pos}, Exprs: []ast.Expr{yyDollar[4].funcexpr}}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.CopyLastPos(yyDollar[4].funcexpr)
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:266
		{
			names, positions, types := splitTypedNames(yyDollar[2].typednames)
			yyVAL.stmt = &ast.LocalAssignStmt{Names: names, NamePositions: positions, Types: types, Exprs: yyDollar[4].exprlist}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:271
		{
			names, positions, types := splitTypedNames(yyDollar[2].typednames)
			yyVAL.stmt = &ast.LocalAssignStmt{Names: names, NamePositions: positions, Types: types, Exprs: []ast.Expr{}}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:276
		{
			yyVAL.stmt = &ast.LabelStmt{Name: yyDollar[1].token.Str}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:280
		{
			yyVAL.stmt = &ast.GotoStmt{Label: yyDollar[2].token.Str}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:284
		{
			if yyDollar[1].token.Str != "type" {
				yylex.(*Lexer).Error("unexpected identifier")
			}
			yyVAL.stmt = &ast.TypeDefStmt{Name: yyDollar[2].token.Str, Type: yyDollar[4].typeexpr}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 25:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:291
		{
			if yyDollar[1].token.Str != "type" {
				yylex.(*Lexer).Error("unexpected identifier")
			}
			yyVAL.stmt = &ast.TypeDefStmt{Name: yyDollar[2].token.Str, TypeParams: yyDollar[3].typeparams, Type: yyDollar[5].typeexpr}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 26:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:298
		{
			yyVAL.stmt = &ast.InterfaceDefStmt{Name: yyDollar[2].token.Str, Extends: yyDollar[3].typereflist, Methods: yyDollar[4].ifacemethods}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.stmt.SetLastPosFromToken(yyDollar[5].token.Pos)
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:305
		{
			yyVAL.stmts = []ast.Stmt{}
		}
	case 28:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:308
		{
			yyVAL.stmts = append(yyDollar[1].stmts, &ast.IfStmt{Condition: yyDollar[3].expr, Then: yyDollar[5].stmts})
			yyVAL.stmts[len(yyVAL.stmts)-1].SetPosFromToken(yyDollar[2].token.Pos)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:314
		{
			yyVAL.stmt = &ast.ReturnStmt{Exprs: nil}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:318
		{
			yyVAL.stmt = &ast.ReturnStmt{Exprs: yyDollar[2].exprlist}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:322
		{
			yyVAL.stmt = &ast.BreakStmt{}
			yyVAL.stmt.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:328
		{
			yyVAL.funcname = yyDollar[1].funcname
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:331
		{
			yyVAL.funcname = &ast.FuncName{Func: nil, Receiver: yyDollar[1].funcname.Func, Method: yyDollar[3].token.Str}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:334
		{
			yyVAL.funcname = &ast.FuncName{Func: nil, Receiver: yyDollar[1].funcname.Func, Method: "type"}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:337
		{
			yyVAL.funcname = &ast.FuncName{Func: nil, Receiver: yyDollar[1].funcname.Func, Method: "interface"}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:340
		{
			yyVAL.funcname = &ast.FuncName{Func: nil, Receiver: yyDollar[1].funcname.Func, Method: "readonly"}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:343
		{
			yyVAL.funcname = &ast.FuncName{Func: nil, Receiver: yyDollar[1].funcname.Func, Method: "as"}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:346
		{
			yyVAL.funcname = &ast.FuncName{Func: nil, Receiver: yyDollar[1].funcname.Func, Method: "asserts"}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:349
		{
			yyVAL.funcname = &ast.FuncName{Func: nil, Receiver: yyDollar[1].funcname.Func, Method: "is"}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:354
		{
			yyVAL.funcname = &ast.FuncName{Func: &ast.IdentExpr{Value: yyDollar[1].token.Str}}
			yyVAL.funcname.Func.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:358
		{
			key := &ast.StringExpr{Value: yyDollar[3].token.Str}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			fn := &ast.AttrGetExpr{Object: yyDollar[1].funcname.Func, Key: key, KeySyntax: ast.AttrKeyDot}
			fn.CopyPos(yyDollar[1].funcname.Func)
			fn.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.funcname = &ast.FuncName{Func: fn}
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:369
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:372
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:377
		{
			yyVAL.expr = &ast.IdentExpr{Value: yyDollar[1].token.Str}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:381
		{
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: yyDollar[3].expr, KeySyntax: ast.AttrKeyIndex}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastLine(yyDollar[4].token.Pos.Line)
			yyVAL.expr.SetLastColumn(yyDollar[4].token.Pos.Column + 1)
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:387
		{
			key := &ast.StringExpr{Value: yyDollar[3].token.Str}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:395
		{
			key := &ast.StringExpr{Value: "type"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:403
		{
			key := &ast.StringExpr{Value: "interface"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:411
		{
			key := &ast.StringExpr{Value: "readonly"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:419
		{
			key := &ast.StringExpr{Value: "as"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:427
		{
			key := &ast.StringExpr{Value: "asserts"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:435
		{
			key := &ast.StringExpr{Value: "is"}
			key.SetPosFromToken(yyDollar[3].token.Pos)
			key.SetLastPosFromToken(yyDollar[3].token.Pos)
			yyVAL.expr = &ast.AttrGetExpr{Object: yyDollar[1].expr, Key: key, KeySyntax: ast.AttrKeyDot}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:445
		{
			yyVAL.namelist = []nameWithPos{{Name: yyDollar[1].token.Str, Pos: yyDollar[1].token.Pos}}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:448
		{
			yyVAL.namelist = append(yyDollar[1].namelist, nameWithPos{Name: yyDollar[3].token.Str, Pos: yyDollar[3].token.Pos})
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:453
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:456
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:461
		{
			yyVAL.expr = &ast.NilExpr{}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:465
		{
			yyVAL.expr = &ast.FalseExpr{}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:469
		{
			yyVAL.expr = &ast.TrueExpr{}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:473
		{
			yyVAL.expr = &ast.NumberExpr{Value: yyDollar[1].token.Str}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:477
		{
			yyVAL.expr = &ast.Comma3Expr{}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:481
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:484
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:487
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:490
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:493
		{
			yyVAL.expr = &ast.LogicalOpExpr{Lhs: yyDollar[1].expr, Operator: "or", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:498
		{
			yyVAL.expr = &ast.LogicalOpExpr{Lhs: yyDollar[1].expr, Operator: "and", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:503
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: ">", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:508
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: "<", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:513
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: ">=", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:518
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: "<=", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:523
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: "==", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:528
		{
			yyVAL.expr = &ast.RelationalOpExpr{Lhs: yyDollar[1].expr, Operator: "~=", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:533
		{
			yyVAL.expr = &ast.StringConcatOpExpr{Lhs: yyDollar[1].expr, Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:538
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "+", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:543
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "-", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:548
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "*", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:553
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "/", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:558
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "%", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:563
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "^", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:568
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "&", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:573
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "|", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:578
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "~", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:583
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "<<", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:588
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: ">>", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:593
		{
			yyVAL.expr = &ast.ArithmeticOpExpr{Lhs: yyDollar[1].expr, Operator: "//", Rhs: yyDollar[3].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].expr)
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:598
		{
			yyVAL.expr = &ast.UnaryMinusOpExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.CopyPos(yyDollar[2].expr)
			yyVAL.expr.CopyLastPos(yyDollar[2].expr)
		}
	case 88:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:603
		{
			yyVAL.expr = &ast.UnaryNotOpExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.CopyLastPos(yyDollar[2].expr)
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:608
		{
			yyVAL.expr = &ast.UnaryLenOpExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.CopyPos(yyDollar[2].expr)
			yyVAL.expr.CopyLastPos(yyDollar[2].expr)
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:613
		{
			yyVAL.expr = &ast.UnaryBNotOpExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.CopyPos(yyDollar[2].expr)
			yyVAL.expr.CopyLastPos(yyDollar[2].expr)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:618
		{
			yyVAL.expr = &ast.CastExpr{Expr: yyDollar[1].expr, Type: yyDollar[3].typeexpr, Syntax: ast.CastSyntaxAs}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].typeexpr)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:623
		{
			yyVAL.expr = &ast.CastExpr{Expr: yyDollar[1].expr, Type: yyDollar[3].typeexpr, Syntax: ast.CastSyntaxColonColon}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[3].typeexpr)
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:628
		{
			yyVAL.expr = &ast.NonNilAssertExpr{Expr: yyDollar[1].expr}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			yyVAL.expr.CopyLastPos(yyDollar[1].expr)
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:635
		{
			yyVAL.expr = &ast.StringExpr{Value: yyDollar[1].token.Str}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:641
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:644
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:647
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:650
		{
			if ex, ok := yyDollar[2].expr.(*ast.Comma3Expr); ok {
				ex.AdjustRet = true
			}
			yyVAL.expr = yyDollar[2].expr
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:660
		{
			yyDollar[2].expr.(*ast.FuncCallExpr).AdjustRet = true
			yyVAL.expr = yyDollar[2].expr
		}
	case 100:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:666
		{
			yyVAL.expr = &ast.FuncCallExpr{Func: yyDollar[1].expr, Args: yyDollar[2].exprlist}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			setLastPosFromExprs(yyVAL.expr, yyDollar[2].exprlist, yyDollar[1].expr)
		}
	case 101:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:671
		{
			yyVAL.expr = &ast.FuncCallExpr{Method: yyDollar[3].token.Str, Receiver: yyDollar[1].expr, Args: yyDollar[4].exprlist}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			setLastPosFromExprs(yyVAL.expr, yyDollar[4].exprlist, yyDollar[1].expr)
		}
	case 102:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:676
		{
			yyVAL.expr = &ast.FuncCallExpr{Method: "type", Receiver: yyDollar[1].expr, Args: yyDollar[4].exprlist}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			setLastPosFromExprs(yyVAL.expr, yyDollar[4].exprlist, yyDollar[1].expr)
		}
	case 103:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:681
		{
			yyVAL.expr = &ast.FuncCallExpr{Method: "interface", Receiver: yyDollar[1].expr, Args: yyDollar[4].exprlist}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			setLastPosFromExprs(yyVAL.expr, yyDollar[4].exprlist, yyDollar[1].expr)
		}
	case 104:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:686
		{
			yyVAL.expr = &ast.FuncCallExpr{Method: "readonly", Receiver: yyDollar[1].expr, Args: yyDollar[4].exprlist}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			setLastPosFromExprs(yyVAL.expr, yyDollar[4].exprlist, yyDollar[1].expr)
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:691
		{
			yyVAL.expr = &ast.FuncCallExpr{Method: "as", Receiver: yyDollar[1].expr, Args: yyDollar[4].exprlist}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			setLastPosFromExprs(yyVAL.expr, yyDollar[4].exprlist, yyDollar[1].expr)
		}
	case 106:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:696
		{
			yyVAL.expr = &ast.FuncCallExpr{Method: "asserts", Receiver: yyDollar[1].expr, Args: yyDollar[4].exprlist}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			setLastPosFromExprs(yyVAL.expr, yyDollar[4].exprlist, yyDollar[1].expr)
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:701
		{
			yyVAL.expr = &ast.FuncCallExpr{Method: "is", Receiver: yyDollar[1].expr, Args: yyDollar[4].exprlist}
			yyVAL.expr.CopyPos(yyDollar[1].expr)
			setLastPosFromExprs(yyVAL.expr, yyDollar[4].exprlist, yyDollar[1].expr)
		}
	case 108:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:708
		{
			if yylex.(*Lexer).PNewLine {
				yylex.(*Lexer).TokenError(yyDollar[1].token, "ambiguous syntax (function call x new statement)")
			}
			yyVAL.exprlist = []ast.Expr{}
		}
	case 109:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:714
		{
			if yylex.(*Lexer).PNewLine {
				yylex.(*Lexer).TokenError(yyDollar[1].token, "ambiguous syntax (function call x new statement)")
			}
			yyVAL.exprlist = yyDollar[2].exprlist
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:720
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:723
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:728
		{
			yyVAL.expr = &ast.FunctionExpr{TypeParams: yyDollar[2].funcexpr.TypeParams, ParList: yyDollar[2].funcexpr.ParList, ReturnTypes: yyDollar[2].funcexpr.ReturnTypes, Stmts: yyDollar[2].funcexpr.Stmts}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.CopyLastPos(yyDollar[2].funcexpr)
		}
	case 113:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:735
		{
			yyVAL.funcexpr = &ast.FunctionExpr{ParList: yyDollar[2].parlist, ReturnTypes: yyDollar[4].typeexprlist, Stmts: yyDollar[5].stmts}
			yyVAL.funcexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.funcexpr.SetLastPosFromToken(yyDollar[6].token.Pos)
		}
	case 114:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:740
		{
			yyVAL.funcexpr = &ast.FunctionExpr{ParList: &ast.ParList{HasVargs: false, Names: []string{}}, ReturnTypes: yyDollar[3].typeexprlist, Stmts: yyDollar[4].stmts}
			yyVAL.funcexpr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.funcexpr.SetLastPosFromToken(yyDollar[5].token.Pos)
		}
	case 115:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:745
		{
			yyVAL.funcexpr = &ast.FunctionExpr{TypeParams: yyDollar[1].typeparams, ParList: yyDollar[3].parlist, ReturnTypes: yyDollar[5].typeexprlist, Stmts: yyDollar[6].stmts}
			yyVAL.funcexpr.SetPosFromToken(yyDollar[2].token.Pos)
			yyVAL.funcexpr.SetLastPosFromToken(yyDollar[7].token.Pos)
		}
	case 116:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:750
		{
			yyVAL.funcexpr = &ast.FunctionExpr{TypeParams: yyDollar[1].typeparams, ParList: &ast.ParList{HasVargs: false, Names: []string{}}, ReturnTypes: yyDollar[4].typeexprlist, Stmts: yyDollar[5].stmts}
			yyVAL.funcexpr.SetPosFromToken(yyDollar[2].token.Pos)
			yyVAL.funcexpr.SetLastPosFromToken(yyDollar[6].token.Pos)
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:757
		{
			yyVAL.parlist = &ast.ParList{HasVargs: true, VarargPosition: yyDollar[1].token.Pos, Names: []string{}}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:760
		{
			yyVAL.parlist = &ast.ParList{HasVargs: true, VarargType: yyDollar[3].typeexpr, VarargPosition: yyDollar[1].token.Pos, Names: []string{}}
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:763
		{
			names, positions, types := splitTypedNames(yyDollar[1].typednames)
			yyVAL.parlist = &ast.ParList{HasVargs: false, Names: names, NamePositions: positions, Types: types}
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:767
		{
			names, positions, types := splitTypedNames(yyDollar[1].typednames)
			yyVAL.parlist = &ast.ParList{HasVargs: true, VarargPosition: yyDollar[3].token.Pos, Names: names, NamePositions: positions, Types: types}
		}
	case 121:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:771
		{
			names, positions, types := splitTypedNames(yyDollar[1].typednames)
			yyVAL.parlist = &ast.ParList{HasVargs: true, VarargType: yyDollar[5].typeexpr, VarargPosition: yyDollar[3].token.Pos, Names: names, NamePositions: positions, Types: types}
		}
	case 122:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:778
		{
			yyVAL.expr = &ast.TableExpr{Fields: []*ast.Field{}}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.SetLastPosFromToken(yyDollar[2].token.Pos)
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:783
		{
			yyVAL.expr = &ast.TableExpr{Fields: yyDollar[2].fieldlist}
			yyVAL.expr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.expr.SetLastPosFromToken(yyDollar[3].token.Pos)
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:791
		{
			yyVAL.fieldlist = []*ast.Field{yyDollar[1].field}
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:794
		{
			yyVAL.fieldlist = append(yyDollar[1].fieldlist, yyDollar[3].field)
		}
	case 126:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:797
		{
			yyVAL.fieldlist = yyDollar[1].fieldlist
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:802
		{
			yyVAL.field = &ast.Field{Key: &ast.StringExpr{Value: yyDollar[1].fieldname}, KeySyntax: ast.AttrKeyDot, Value: yyDollar[3].expr}
		}
	case 128:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:805
		{
			yyVAL.field = &ast.Field{Key: yyDollar[2].expr, KeySyntax: ast.AttrKeyIndex, Value: yyDollar[5].expr}
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:808
		{
			yyVAL.field = &ast.Field{Value: yyDollar[1].expr}
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:814
		{
			yyVAL.fieldname = yyDollar[1].token.Str
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:817
		{
			yyVAL.fieldname = "type"
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:820
		{
			yyVAL.fieldname = "interface"
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:823
		{
			yyVAL.fieldname = "readonly"
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:826
		{
			yyVAL.fieldname = "as"
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:829
		{
			yyVAL.fieldname = "asserts"
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:832
		{
			yyVAL.fieldname = "is"
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:835
		{
			yyVAL.fieldname = "keyof"
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:838
		{
			yyVAL.fieldname = "extends"
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:843
		{
			yyVAL.token = yyDollar[1].token
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:846
		{
			yyVAL.token = yyDollar[1].token
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:849
		{
			yyVAL.token = yyDollar[1].token
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:852
		{
			yyVAL.token = yyDollar[1].token
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:855
		{
			yyVAL.token = yyDollar[1].token
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:858
		{
			yyVAL.token = yyDollar[1].token
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:861
		{
			yyVAL.token = yyDollar[1].token
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:864
		{
			yyVAL.token = yyDollar[1].token
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:867
		{
			yyVAL.token = yyDollar[1].token
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:872
		{
			yyVAL.fieldsep = ","
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:875
		{
			yyVAL.fieldsep = ";"
		}
	case 150:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:882
		{
			yyVAL.typeexprlist = nil
		}
	case 151:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:885
		{
			yyVAL.typeexprlist = yyDollar[2].typeexprlist
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:888
		{
			yyVAL.typeexprlist = nil
		}
	case 153:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:891
		{
			yyVAL.typeexprlist = append([]ast.TypeExpr{yyDollar[3].typeexpr}, yyDollar[5].typeexprlist...)
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:896
		{
			yyVAL.typeexpr = yyDollar[1].typeexpr
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:899
		{
			if union, ok := yyDollar[1].typeexpr.(*ast.UnionTypeExpr); ok {
				union.Types = append(union.Types, yyDollar[3].typeexpr)
				yyVAL.typeexpr = union
			} else {
				yyVAL.typeexpr = &ast.UnionTypeExpr{Types: []ast.TypeExpr{yyDollar[1].typeexpr, yyDollar[3].typeexpr}}
				yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			}
			yyVAL.typeexpr.CopyLastPos(yyDollar[3].typeexpr)
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:909
		{
			if inter, ok := yyDollar[1].typeexpr.(*ast.IntersectionTypeExpr); ok {
				inter.Types = append(inter.Types, yyDollar[3].typeexpr)
				yyVAL.typeexpr = inter
			} else {
				yyVAL.typeexpr = &ast.IntersectionTypeExpr{Types: []ast.TypeExpr{yyDollar[1].typeexpr, yyDollar[3].typeexpr}}
				yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			}
			yyVAL.typeexpr.CopyLastPos(yyDollar[3].typeexpr)
		}
	case 157:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:919
		{
			yyVAL.typeexpr = &ast.ConditionalTypeExpr{Check: yyDollar[1].typeexpr, Extends: yyDollar[3].typeexpr, Then: yyDollar[5].typeexpr, Else: yyDollar[7].typeexpr}
			yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:925
		{
			yyVAL.typeexpr = yyDollar[1].typeexpr
		}
	case 159:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:928
		{
			if prim, ok := yyDollar[1].typeexpr.(*ast.PrimitiveTypeExpr); ok {
				prim.Annotations = yyDollar[2].annotations
				yyVAL.typeexpr = prim
			} else if arr, ok := yyDollar[1].typeexpr.(*ast.ArrayTypeExpr); ok {
				arr.ArrayAnnotations = yyDollar[2].annotations
				yyVAL.typeexpr = arr
			} else {
				yyVAL.typeexpr = yyDollar[1].typeexpr
			}
		}
	case 160:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:939
		{
			yyVAL.typeexpr = &ast.OptionalTypeExpr{Inner: yyDollar[1].typeexpr}
			yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
			yyVAL.typeexpr.SetLastPosFromToken(yyDollar[2].token.Pos)
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:946
		{
			yyVAL.typeexpr = &ast.PrimitiveTypeExpr{Name: "nil"}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 162:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:950
		{
			yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: true}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 163:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:954
		{
			yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: false}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:958
		{
			yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: yyDollar[1].token.Str}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:962
		{
			if i, ok := numparse.ParseIntegerLiteral(yyDollar[1].token.Str); ok {
				yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: i}
			} else if f, ok := numparse.ParseFloatLiteral(yyDollar[1].token.Str); ok {
				yyVAL.typeexpr = &ast.LiteralTypeExpr{Value: f}
			} else {
				yyVAL.typeexpr = &ast.LiteralTypeExpr{}
			}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 166:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:972
		{
			yyVAL.typeexpr = &ast.PrimitiveTypeExpr{Name: yyDollar[1].token.Str}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 167:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:976
		{
			yyVAL.typeexpr = &ast.TypeRefExpr{Path: []string{yyDollar[1].token.Str, yyDollar[3].token.Str}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 168:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:980
		{
			yyVAL.typeexpr = &ast.GenericTypeExpr{
				Base: &ast.TypeRefExpr{Path: []string{yyDollar[1].token.Str}},
				Args: yyDollar[3].typeexprlist,
			}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 169:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:987
		{
			yyVAL.typeexpr = &ast.ArrayTypeExpr{Element: yyDollar[2].typeexpr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 170:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:991
		{
			yyVAL.typeexpr = &ast.MapTypeExpr{Key: yyDollar[3].typeexpr, Value: yyDollar[6].typeexpr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:995
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: yyDollar[2].recordfields}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 172:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:999
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[2].funcparams, Returns: yyDollar[6].typeexprlist}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 173:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1003
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[2].funcparams, Returns: []ast.TypeExpr{}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 174:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:1007
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[2].funcparams, Returns: []ast.TypeExpr{yyDollar[5].typeexpr}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 175:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1011
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: yyDollar[5].typeexprlist}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 176:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1015
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{yyDollar[4].typeexpr}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 177:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:1019
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 178:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1023
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[3].funcparams, Returns: []ast.TypeExpr{yyDollar[6].typeexpr}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 179:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1027
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{yyDollar[5].typeexpr}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 180:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:1031
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[3].funcparams, Returns: yyDollar[7].typeexprlist}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 181:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:1035
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[3].funcparams, Returns: []ast.TypeExpr{}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 182:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:1039
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: yyDollar[6].typeexprlist}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 183:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1043
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 184:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1047
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[3].funcparams, Returns: []ast.TypeExpr{yyDollar[6].typeexpr}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 185:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:1051
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[3].funcparams, Returns: yyDollar[7].typeexprlist}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 186:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:1055
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{yyDollar[5].typeexpr}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 187:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1059
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: yyDollar[6].typeexprlist}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 188:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:1063
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[3].funcparams, Returns: []ast.TypeExpr{}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 189:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1067
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: []ast.TypeExpr{}}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 190:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1071
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: yyDollar[3].funcparams, Returns: nil}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 191:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1075
		{
			yyVAL.typeexpr = &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: nil}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 192:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1079
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: yyDollar[3].recordfields}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 193:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1083
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: nil}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 194:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1087
		{
			yyVAL.typeexpr = &ast.ArrayTypeExpr{Element: yyDollar[1].typeexpr}
			yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
		}
	case 195:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1091
		{
			arr := &ast.ArrayTypeExpr{Element: yyDollar[3].typeexpr, Readonly: true}
			arr.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr = arr
		}
	case 196:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:1096
		{
			m := &ast.MapTypeExpr{Key: yyDollar[4].typeexpr, Value: yyDollar[7].typeexpr, Readonly: true}
			m.SetPosFromToken(yyDollar[1].token.Pos)
			yyVAL.typeexpr = m
		}
	case 197:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1101
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: yyDollar[3].recordfields, Readonly: true}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 198:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1105
		{
			yyVAL.typeexpr = &ast.RecordTypeExpr{Fields: nil}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 199:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1109
		{
			yyVAL.typeexpr = &ast.AssertsTypeExpr{ParamName: yyDollar[2].token.Str, NarrowTo: nil}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 200:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1113
		{
			yyVAL.typeexpr = &ast.AssertsTypeExpr{ParamName: yyDollar[2].token.Str, NarrowTo: yyDollar[4].typeexpr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 201:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1117
		{
			yyVAL.typeexpr = &ast.TypeOfExpr{Expr: yyDollar[3].expr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 202:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1121
		{
			yyVAL.typeexpr = &ast.KeyOfExpr{Inner: yyDollar[3].typeexpr}
			yyVAL.typeexpr.SetPosFromToken(yyDollar[1].token.Pos)
		}
	case 203:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1125
		{
			yyVAL.typeexpr = &ast.IndexAccessExpr{Object: yyDollar[1].typeexpr, Index: yyDollar[3].typeexpr}
			yyVAL.typeexpr.CopyPos(yyDollar[1].typeexpr)
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1131
		{
			yyVAL.typeexprlist = []ast.TypeExpr{yyDollar[1].typeexpr}
		}
	case 205:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1134
		{
			yyVAL.typeexprlist = append(yyDollar[1].typeexprlist, yyDollar[3].typeexpr)
		}
	case 206:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1139
		{
			yyVAL.typeexprlist = []ast.TypeExpr{yyDollar[1].typeexpr, yyDollar[3].typeexpr}
		}
	case 207:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1142
		{
			yyVAL.typeexprlist = append(yyDollar[1].typeexprlist, yyDollar[3].typeexpr)
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1147
		{
		}
	case 209:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1149
		{
			yylex.(*Lexer).PendingGT = &ast.Token{
				Type: '>',
				Str:  ">",
				Pos:  ast.Position{File: yyDollar[1].token.Pos.File, Line: yyDollar[1].token.Pos.Line, Column: yyDollar[1].token.Pos.Column + 1},
			}
		}
	case 210:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1158
		{
			yyVAL.funcparam = ast.FunctionParamExpr{Name: yyDollar[1].token.Str, Type: yyDollar[3].typeexpr}
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1161
		{
			yyVAL.funcparam = ast.FunctionParamExpr{Name: "", Type: yyDollar[1].typeexpr}
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1166
		{
			yyVAL.funcparams = []ast.FunctionParamExpr{yyDollar[1].funcparam}
		}
	case 213:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1169
		{
			yyVAL.funcparams = append(yyDollar[1].funcparams, yyDollar[3].funcparam)
		}
	case 214:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1172
		{
			yyVAL.funcparams = []ast.FunctionParamExpr{{Name: "...", Type: yyDollar[2].typeexpr}}
		}
	case 215:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1175
		{
			yyVAL.funcparams = append(yyDollar[1].funcparams, ast.FunctionParamExpr{Name: "...", Type: yyDollar[4].typeexpr})
		}
	case 216:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1180
		{
			yyVAL.recordfields = []ast.RecordFieldExpr{yyDollar[1].recordfield}
		}
	case 217:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1183
		{
			yyVAL.recordfields = append(yyDollar[1].recordfields, yyDollar[3].recordfield)
		}
	case 218:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1186
		{
			yyVAL.recordfields = yyDollar[1].recordfields
		}
	case 219:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1191
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: false}
		}
	case 220:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1194
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: false, Annotations: yyDollar[4].annotations}
		}
	case 221:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1197
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: true}
		}
	case 222:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1200
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: true, Annotations: yyDollar[4].annotations}
		}
	case 223:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1203
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: false}
		}
	case 224:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1206
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: false, Annotations: yyDollar[4].annotations}
		}
	case 225:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1209
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: true}
		}
	case 226:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1212
		{
			yyVAL.recordfield = ast.RecordFieldExpr{Name: yyDollar[1].token.Str, NamePosition: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr, Optional: true, Annotations: yyDollar[4].annotations}
		}
	case 227:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1217
		{
			yyVAL.annotations = []ast.AnnotationExpr{yyDollar[1].annotation}
		}
	case 228:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1220
		{
			yyVAL.annotations = append(yyDollar[1].annotations, yyDollar[2].annotation)
		}
	case 229:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1225
		{
			yyVAL.annotation = ast.AnnotationExpr{Name: yyDollar[2].token.Str, Args: nil}
		}
	case 230:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:1228
		{
			yyVAL.annotation = ast.AnnotationExpr{Name: yyDollar[2].token.Str, Args: nil}
		}
	case 231:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:1231
		{
			yyVAL.annotation = ast.AnnotationExpr{Name: yyDollar[2].token.Str, Args: yyDollar[4].exprlist}
		}
	case 232:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1236
		{
			yyVAL.typeparams = yyDollar[2].typeparams
		}
	case 233:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1241
		{
			yyVAL.typeparams = []ast.TypeParamExpr{yyDollar[1].typeparam}
		}
	case 234:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1244
		{
			yyVAL.typeparams = append(yyDollar[1].typeparams, yyDollar[3].typeparam)
		}
	case 235:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1249
		{
			yyVAL.typeparam = ast.TypeParamExpr{Name: yyDollar[1].token.Str, Constraint: nil}
		}
	case 236:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1252
		{
			yyVAL.typeparam = ast.TypeParamExpr{Name: yyDollar[1].token.Str, Constraint: yyDollar[3].typeexpr}
		}
	case 237:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1257
		{
			yyVAL.typednames = []typedNameEntry{yyDollar[1].typedname}
		}
	case 238:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1260
		{
			yyVAL.typednames = append(yyDollar[1].typednames, yyDollar[3].typedname)
		}
	case 239:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:1265
		{
			yyVAL.typedname = typedNameEntry{Name: yyDollar[1].token.Str, Pos: yyDollar[1].token.Pos, Type: nil}
		}
	case 240:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1268
		{
			yyVAL.typedname = typedNameEntry{Name: yyDollar[1].token.Str, Pos: yyDollar[1].token.Pos, Type: yyDollar[3].typeexpr}
		}
	case 241:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:1273
		{
			yyVAL.typereflist = nil
		}
	case 242:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1276
		{
			yyVAL.typereflist = []*ast.TypeRefExpr{{Path: []string{yyDollar[2].token.Str}}}
		}
	case 243:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1279
		{
			yyVAL.typereflist = append(yyDollar[1].typereflist, &ast.TypeRefExpr{Path: []string{yyDollar[3].token.Str}})
		}
	case 244:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:1284
		{
			yyVAL.ifacemethods = nil
		}
	case 245:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:1287
		{
			yyVAL.ifacemethods = append(yyDollar[1].ifacemethods, yyDollar[2].ifacemethod)
		}
	case 246:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:1292
		{
			yyVAL.ifacemethod = ast.InterfaceMethodExpr{
				Name: yyDollar[2].token.Str,
				Type: &ast.FunctionTypeExpr{Params: []ast.FunctionParamExpr{}, Returns: yyDollar[5].typeexprlist},
			}
		}
	case 247:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:1298
		{
			yyVAL.ifacemethod = ast.InterfaceMethodExpr{
				Name: yyDollar[2].token.Str,
				Type: &ast.FunctionTypeExpr{Params: toFuncParams(yyDollar[4].typednames), Returns: yyDollar[6].typeexprlist},
			}
		}
	}
	goto yystack /* stack new state and value */
}
