package emit

import (
	"fmt"
	"strings"

	"github.com/wippyai/go-lua/analysis/schema/axis/member"
	"github.com/wippyai/go-lua/analysis/schema/axis/member/definition"
	"github.com/wippyai/go-lua/analysis/schema/rule/program"
)

// The emitted identifiers. They are fixed rather than derived from the rule
// key for one reason: a package holds one rule's family, and a stable name set
// keeps a regenerated file a diff of its declaration rather than of its
// spelling.
const (
	reducerType   = "familyReducer"
	rowType       = "familyRow"
	familyType    = "sealedFamily"
	workerType    = "familyWorker"
	installerType = "familyInstaller"
	constructor   = "NewFamilyInstaller"
)

// render writes one emission plan as Go source. The import block is rendered
// last because every qualifier is registered while the body is written.
func render(built *plan) ([]byte, error) {
	imports := built.imports
	imports.reserve(built.target.PackageName)
	var body strings.Builder
	if err := renderReducer(&body, built); err != nil {
		return nil, err
	}
	if err := renderRow(&body, built); err != nil {
		return nil, err
	}
	renderFamily(&body, built)
	if err := renderWorker(&body, built); err != nil {
		return nil, err
	}
	if err := renderInstaller(&body, built); err != nil {
		return nil, err
	}
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by the rule family emitter from the %q rule declaration; DO NOT EDIT.\n",
		string(built.target.Spec.Key))
	out.WriteString("//\n")
	out.WriteString("// The installer seals every primitive through the plane at the geometry the\n")
	out.WriteString("// declaration states, the family holds one sealed row per plan row, and the\n")
	out.WriteString("// worker performs one invocation over lane-owned scratch. The semantic fold\n")
	out.WriteString("// this file calls, and the relation derivations its joins name, remain the\n")
	out.WriteString("// owner's own source.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", built.target.PackageName)
	out.WriteString(imports.block())
	out.WriteString(body.String())
	return []byte(out.String()), nil
}

// reducerFields is the state one invocation seals into the emitted reducer:
// the candidate carrier when the fold declares one, and every fold input the
// reducer's own delivery does not carry.
func reducerFields(built *plan) []string {
	fields := make([]string, 0, len(built.fold.arguments))
	for _, argument := range built.fold.arguments {
		if argument.Role == definition.ArgumentCandidate {
			fields = append(fields, "candidate")
			continue
		}
		if argument.Role != definition.ArgumentFact && argument.Role != definition.ArgumentVector {
			continue
		}
		if _, delivered := built.deliveredFact[argument.Input]; delivered {
			continue
		}
		fields = append(fields, fmt.Sprintf("input%d", built.fold.inputs[argument.Input].position))
	}
	return fields
}

func renderReducer(out *strings.Builder, built *plan) error {
	imports := built.imports
	out.WriteString("// " + reducerType + " is the sealed semantic half of one invocation. It holds the\n")
	out.WriteString("// carriers this row's fold is indexed by, and its type is the family's, so the\n")
	out.WriteString("// call below is a static direct call rather than an interface dispatch.\n")
	if built.fold.state != nil {
		out.WriteString("//\n")
		out.WriteString("// It also carries the state the declared judgment is issued by. That state is\n")
		out.WriteString("// the family's, sealed once from the axis schemas the declaration names, so a\n")
		out.WriteString("// fold resting on cold owner knowledge still takes only carriers as arguments.\n")
	}
	fmt.Fprintf(out, "type %s struct {\n", reducerType)
	if built.fold.state != nil {
		fmt.Fprintf(out, "\tstate %s\n", imports.typeName(built.fold.state.state))
	}
	for _, argument := range built.fold.arguments {
		if argument.Role == definition.ArgumentCandidate {
			fmt.Fprintf(out, "\tcandidate %s\n", imports.typeName(argument.Type))
			continue
		}
		if argument.Role == definition.ArgumentVector {
			fmt.Fprintf(out, "\tinput%d %s[%s]\n", built.fold.inputs[argument.Input].position,
				imports.typeName(argument.Type), imports.typeName(argument.Element))
			continue
		}
		if argument.Role != definition.ArgumentFact {
			continue
		}
		if _, delivered := built.deliveredFact[argument.Input]; delivered {
			continue
		}
		fmt.Fprintf(out, "\tinput%d %s\n", built.fold.inputs[argument.Input].position, imports.typeName(argument.Type))
	}
	out.WriteString("}\n\n")

	switch built.shape {
	case shapeCarry:
		return renderCarryReduce(out, built)
	case shapeExactFold:
		return renderExactReduce(out, built)
	case shapeSelectedRoute:
		return renderRouteReduce(out, built)
	default:
		return unexpressible(built.target.Spec.Key, "an unclassified fold", "the declaration derives no emitted shape")
	}
}

func renderExactReduce(out *strings.Builder, built *plan) error {
	imports := built.imports
	structure := imports.use(structurePackagePath)
	read := built.joins[0]
	if read.read.Contract.Sparse != program.SparseExplicit {
		return unexpressible(built.target.Spec.Key, fmt.Sprintf("an exact fold read with %s sparsity", sparseName(read.read.Contract.Sparse)),
			"the heterogeneous exact fold preserves absence and never materializes a default")
	}
	if len(built.fold.results) != 2 {
		return unexpressible(built.target.Spec.Key, fmt.Sprintf("an exact fold answering %d results", len(built.fold.results)),
			"an exact fold publishes one fact and one disposition")
	}
	call, err := foldCall(built)
	if err != nil {
		return err
	}
	out.WriteString("// Reduce is the one irreducible typed judgment of this exact family. The\n")
	out.WriteString("// execution worker authenticates presence before calling it, so absence never\n")
	out.WriteString("// becomes a default fact and the fold receives only declared carriers.\n")
	fmt.Fprintf(out, "func (fold %s) Reduce(cell %s) (%s, %s.ReductionOutcome) {\n",
		reducerType, imports.typeName(read.axis.fact), imports.typeName(built.fold.results[0]), structure)
	fmt.Fprintf(out, "\treturn %s\n}\n\n", call)
	return nil
}

// foldCall spells the one direct call to the declared reducer, with the
// argument vector the declaration derives and nothing beside it.
func foldCall(built *plan) (string, error) {
	imports := built.imports
	arguments := make([]string, 0, len(built.fold.arguments))
	for _, argument := range built.fold.arguments {
		switch argument.Role {
		case definition.ArgumentCandidate:
			arguments = append(arguments, "fold.candidate")
		case definition.ArgumentFact:
			expression, present := built.deliveredFact[argument.Input]
			if !present {
				expression = fmt.Sprintf("fold.input%d", built.fold.inputs[argument.Input].position)
			}
			arguments = append(arguments, expression)
		case definition.ArgumentTag:
			expression, present := built.deliveredTag[argument.Input]
			if !present {
				return "", unexpressible(built.target.Spec.Key, "a tagged fold input outside its own selection",
					fmt.Sprintf("input %d declares a tag, and only the selection this row publishes through delivers one", argument.Input))
			}
			arguments = append(arguments, expression)
		case definition.ArgumentRoute:
			expression, present := built.deliveredRoute[argument.Input]
			if !present {
				return "", unexpressible(built.target.Spec.Key, "a routed fold input outside its own route selection",
					fmt.Sprintf("input %d declares a route carrier, and only the selected relation member owns a destination coordinate", argument.Input))
			}
			arguments = append(arguments, expression)
		case definition.ArgumentVector:
			// A many-valued input is one vector argument. The invocation fills
			// the reducer's field with the vector it delivered, so the fold
			// reads the same view every other consumer of that read does.
			arguments = append(arguments, fmt.Sprintf("fold.input%d", built.fold.inputs[argument.Input].position))
		default:
			return "", unexpressible(built.target.Spec.Key, "an unknown fold argument role", fmt.Sprintf("input %d", argument.Input))
		}
	}
	receiver := ""
	if built.fold.state != nil {
		receiver = "fold.state"
	}
	return imports.call(built.fold.reducer.Implementation, receiver, arguments...), nil
}

func renderCarryReduce(out *strings.Builder, built *plan) error {
	imports := built.imports
	structure := imports.use(structurePackagePath)
	read := built.joins[0]
	// FoldCarry delivers the exact cell to Reduce itself, so this shape has no
	// call site to seal a materialization policy at. Only an explicitly sparse
	// read is therefore expressible here: its absence is delivered unchanged,
	// which is the one reading that needs no substitution.
	if read.read.Contract.Sparse != program.SparseExplicit {
		return unexpressible(built.target.Spec.Key, fmt.Sprintf("an exact carry read with %s sparsity", sparseName(read.read.Contract.Sparse)),
			"the carry fold hands sparse absence to the domain, and the fold primitive seals no cell policy to substitute through")
	}
	if len(built.fold.results) != 2 {
		return unexpressible(built.target.Spec.Key, fmt.Sprintf("a carry fold answering %d results", len(built.fold.results)),
			"a carry fold publishes one fact and one disposition")
	}
	call, err := foldCall(built)
	if err != nil {
		return err
	}
	out.WriteString("// Reduce answers the fact this row publishes from the one exact cell it read.\n")
	out.WriteString("// The read declares explicit sparsity, so an unwritten predecessor is delivered\n")
	out.WriteString("// as absence and settles as this rule's absent candidate: nothing here invents\n")
	out.WriteString("// a world the Factor never wrote.\n")
	fmt.Fprintf(out, "func (fold %s) Reduce(cell %s, present bool) (%s, %s.ReductionOutcome) {\n",
		reducerType, imports.typeName(read.axis.fact), imports.typeName(built.fold.results[0]), structure)
	out.WriteString("\tif !present {\n")
	fmt.Fprintf(out, "\t\tvar absent %s\n", imports.typeName(built.fold.results[0]))
	fmt.Fprintf(out, "\t\treturn absent, %s.NoCandidate\n", structure)
	out.WriteString("\t}\n")
	fmt.Fprintf(out, "\treturn %s\n}\n\n", call)
	return nil
}

func renderRouteReduce(out *strings.Builder, built *plan) error {
	imports := built.imports
	structure := imports.use(structurePackagePath)
	execution := imports.use(executionPackagePath)
	route := built.route.join
	position := -1
	for index, join := range built.fold.inputs {
		if join == route {
			position = index
		}
	}
	if position < 0 {
		return unexpressible(built.target.Spec.Key, "a routed output whose route join the fold does not consume",
			"the cell a route publishes at is the fold's own input")
	}
	if len(built.fold.results) != 2 {
		return unexpressible(built.target.Spec.Key, fmt.Sprintf("a routed fold answering %d results", len(built.fold.results)),
			"a routed fold publishes one fact and one disposition")
	}
	call, err := foldCall(built)
	if err != nil {
		return err
	}
	out.WriteString("// Reduce answers one selected route. The route coordinate, cell, and tag\n")
	out.WriteString("// are the three owner-issued halves of the one member the read observed,\n")
	out.WriteString("// so the fold never re-derives a destination or correlation.\n")
	fmt.Fprintf(out, "func (fold %s) Reduce(routeCoordinate %s, cell %s.SelectedCell[%s]) (%s, %s.ReductionOutcome) {\n",
		reducerType, imports.typeName(built.route.destinationType), execution, imports.typeName(route.axis.fact), imports.typeName(built.fold.results[0]), structure)
	fmt.Fprintf(out, "\treturn %s\n}\n\n", call)

	out.WriteString("// Empty settles the row whose derived relation selected no route at all. An\n")
	out.WriteString("// empty selection is not a refusal: it is the one disposition that says the\n")
	out.WriteString("// relation was read and named nothing.\n")
	fmt.Fprintf(out, "func (%s) Empty() %s.ReductionOutcome { return %s.NoSelection }\n\n", reducerType, structure, structure)
	return nil
}

func renderRow(out *strings.Builder, built *plan) error {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	out.WriteString("// " + rowType + " is the sealed static half of one plan row: the candidate its fold\n")
	out.WriteString("// is indexed by and every primitive the installer sealed through the plane.\n")
	fmt.Fprintf(out, "type %s struct {\n", rowType)
	fmt.Fprintf(out, "\tcandidate %s\n", imports.typeName(built.candidate.subject))
	for _, join := range built.joins {
		switch join.read.Form {
		case program.Exact:
			fmt.Fprintf(out, "\t%s %s.ExactRead[%s, %s]\n", join.name, execution,
				imports.typeName(join.axis.dense), imports.typeName(join.axis.fact))
			fmt.Fprintf(out, "\t%sPolicy %s.ReadCellPolicy[%s]\n", join.name, execution, imports.typeName(join.axis.fact))
		case program.Selected:
			fmt.Fprintf(out, "\t%s %s.SelectedRead[%s, %s]\n", join.name, execution,
				imports.typeName(join.axis.dense), imports.typeName(join.axis.fact))
		case program.Summary:
			if join.memberSet == nil {
				return unexpressible(built.target.Spec.Key, "a summary read over a Factor cursor",
					fmt.Sprintf("join %d spans a partition the emitted installer opens no vector cursor over", join.position))
			}
			// One sealed exact read per declared ordinal. The set's width is
			// the candidate's own census, so it is a row-local slice rather
			// than a family-wide constant.
			fmt.Fprintf(out, "\t%s []%s.ExactRead[%s, %s]\n", join.name, execution,
				imports.typeName(join.axis.dense), imports.typeName(join.axis.fact))
			fmt.Fprintf(out, "\t%sPolicy %s.ReadCellPolicy[%s]\n", join.name, execution, imports.typeName(join.axis.fact))
		default:
			return unexpressible(built.target.Spec.Key, fmt.Sprintf("a %s read", readFormName(join.read.Form)),
				fmt.Sprintf("join %d has no sealed read primitive in the emitted vocabulary", join.position))
		}
	}
	switch built.shape {
	case shapeCarry:
		fmt.Fprintf(out, "\twrite %s.CarryWrite[%s, %s]\n", execution,
			imports.typeName(built.write.dense), imports.typeName(built.write.fact))
	case shapeExactFold:
		fmt.Fprintf(out, "\twrite %s.ExactWrite[%s, %s]\n", execution,
			imports.typeName(built.write.dense), imports.typeName(built.write.fact))
	case shapeSelectedRoute:
		fmt.Fprintf(out, "\twrite %s.RouteWrite[%s, %s]\n", execution,
			imports.typeName(built.write.dense), imports.typeName(built.write.fact))
	}
	out.WriteString("}\n\n")
	return nil
}

func renderFamily(out *strings.Builder, built *plan) {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	out.WriteString("// " + familyType + " is this rule's whole installed family: one row per plan row and\n")
	out.WriteString("// the sealed state every invocation reads. Nothing here is mutated after the\n")
	out.WriteString("// installer returns.\n")
	fmt.Fprintf(out, "type %s struct {\n", familyType)
	fmt.Fprintf(out, "\trows []%s\n", rowType)
	if built.fold.state != nil {
		fmt.Fprintf(out, "\tstate %s\n", imports.typeName(built.fold.state.state))
	}
	for _, axis := range built.familyAxes {
		fmt.Fprintf(out, "\t%s %s\n", axis.param, imports.typeName(axis.schemaType))
	}
	if built.shape == shapeSelectedRoute {
		fmt.Fprintf(out, "\tplane %s.FormPlane[%s, %s]\n", execution,
			imports.typeName(built.write.dense), imports.typeName(built.write.fact))
		out.WriteString("\twidth int\n")
	}
	for _, join := range memberSetJoins(built) {
		fmt.Fprintf(out, "\t%sWidth int\n", join.name)
	}
	out.WriteString("}\n\n")

	fmt.Fprintf(out, "func (sealed *%s) NewExecutor(run *%s.Run) %s.Executor {\n", familyType, execution, execution)
	out.WriteString("\tif sealed == nil || run == nil {\n\t\treturn nil\n\t}\n")
	for _, join := range memberSetJoins(built) {
		fmt.Fprintf(out, "\tif sealed.%sWidth < 0 {\n\t\treturn nil\n\t}\n", join.name)
	}
	if built.shape == shapeSelectedRoute {
		out.WriteString("\tif sealed.width < 0 {\n\t\treturn nil\n\t}\n")
		out.WriteString("\t// Every buffer is sized once at the sealed width of the selection this rule\n")
		out.WriteString("\t// spans, so an ordinary invocation allocates nothing.\n")
		fmt.Fprintf(out, "\treturn &%s{\n", workerType)
		out.WriteString("\t\tfamily:  sealed,\n\t\trun:     run,\n")
		fmt.Fprintf(out, "\t\tmembers: make([]%s.RouteMember, sealed.width),\n", execution)
		fmt.Fprintf(out, "\t\tcells:   make([]%s.SelectedCell[%s], sealed.width),\n", execution, imports.typeName(built.write.fact))
		fmt.Fprintf(out, "\t\troutes:  make([]%s, sealed.width),\n", imports.typeName(built.route.destinationType))
		for _, join := range memberSetJoins(built) {
			fmt.Fprintf(out, "\t\t%sCells: make([]%s.MemberCell[%s], sealed.%sWidth),\n",
				join.name, execution, imports.typeName(join.axis.fact), join.name)
		}
		out.WriteString("\t}\n}\n\n")
	} else {
		fmt.Fprintf(out, "\treturn &%s{family: sealed, run: run}\n}\n\n", workerType)
	}
	fmt.Fprintf(out, "func (*%s) InputCapacity() int  { return %d }\n", familyType, built.inputPorts)
	fmt.Fprintf(out, "func (*%s) OutputCapacity() int { return %d }\n\n", familyType, len(built.target.Spec.Program.Fold.Outputs))
}

func renderWorker(out *strings.Builder, built *plan) error {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	structure := imports.use(structurePackagePath)
	out.WriteString("// " + workerType + " is one epoch's reusable invocation lane. Every scratch lives for\n")
	out.WriteString("// the worker's lifetime, so a warm invocation opens its cursors and its write\n")
	out.WriteString("// transaction without allocating.\n")
	fmt.Fprintf(out, "type %s struct {\n", workerType)
	fmt.Fprintf(out, "\tfamily *%s\n", familyType)
	fmt.Fprintf(out, "\trun    *%s.Run\n", execution)
	for _, join := range built.joins {
		switch join.read.Form {
		case program.Exact:
			fmt.Fprintf(out, "\t%s %s.Scratch[%s, %s]\n", join.name, execution,
				imports.typeName(join.axis.dense), imports.typeName(join.axis.fact))
		case program.Selected:
			fmt.Fprintf(out, "\t%s %s.SelectedScratch[%s, %s]\n", join.name, execution,
				imports.typeName(join.axis.dense), imports.typeName(join.axis.fact))
		case program.Summary:
			// One scratch lane serves every ordinal of the set: the members are
			// read in declaration order and the lane is returned to service
			// between them, so the vector costs one cursor rather than one per
			// member.
			fmt.Fprintf(out, "\t%s %s.Scratch[%s, %s]\n", join.name, execution,
				imports.typeName(join.axis.dense), imports.typeName(join.axis.fact))
			fmt.Fprintf(out, "\t%sCells []%s.MemberCell[%s]\n", join.name, execution, imports.typeName(join.axis.fact))
		}
	}
	switch built.shape {
	case shapeCarry:
		fmt.Fprintf(out, "\twrite %s.Scratch[%s, %s]\n", execution,
			imports.typeName(built.write.dense), imports.typeName(built.write.fact))
	case shapeExactFold:
		fmt.Fprintf(out, "\twrite %s.Scratch[%s, %s]\n", execution,
			imports.typeName(built.write.dense), imports.typeName(built.write.fact))
	case shapeSelectedRoute:
		fmt.Fprintf(out, "\twrite %s.RouteScratch[%s, %s]\n", execution,
			imports.typeName(built.write.dense), imports.typeName(built.write.fact))
		fmt.Fprintf(out, "\tmembers []%s.RouteMember\n", execution)
		fmt.Fprintf(out, "\tcells   []%s.SelectedCell[%s]\n", execution, imports.typeName(built.write.fact))
		fmt.Fprintf(out, "\troutes  []%s\n", imports.typeName(built.route.destinationType))
	}
	out.WriteString("}\n\n")

	out.WriteString("// settle submits one non-publishing disposition. Every refusal path in this\n")
	out.WriteString("// worker ends here, so the ticket is settled exactly once.\n")
	fmt.Fprintf(out, "func (lane *%s) settle(ticket %s.Ticket, outcome %s.ReductionOutcome) (%s.Result, bool) {\n",
		workerType, execution, structure, execution)
	fmt.Fprintf(out, "\tif !ticket.Submit(outcome) {\n\t\treturn %s.Result{}, false\n\t}\n", execution)
	fmt.Fprintf(out, "\treturn %s.NewResult(outcome, 0)\n}\n\n", execution)

	switch built.shape {
	case shapeCarry:
		return renderCarryExecute(out, built)
	case shapeExactFold:
		return renderExactExecute(out, built)
	case shapeSelectedRoute:
		return renderRouteExecute(out, built)
	}
	return nil
}

func renderExactExecute(out *strings.Builder, built *plan) error {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	structure := imports.use(structurePackagePath)
	read := built.joins[0]
	out.WriteString("// Execute consumes the one exact existence fact, applies the typed fold, and\n")
	out.WriteString("// publishes through the consumer-owned target sealed for this candidate.\n")
	renderExecutePrologue(out, built)
	fmt.Fprintf(out, "\tswitch row.%s.Read(ticket, &lane.%s) {\n", read.name, read.name)
	fmt.Fprintf(out, "\tcase %s.ReadAvailable:\n", execution)
	fmt.Fprintf(out, "\t\tcell, available := lane.%s.Value()\n", read.name)
	fmt.Fprintf(out, "\t\tpresent := lane.%s.Present()\n", read.name)
	fmt.Fprintf(out, "\t\tregion, regionOK := lane.%s.Region()\n", read.name)
	fmt.Fprintf(out, "\t\tif !row.%s.Close(ticket, &lane.%s) {\n\t\t\t_ = lane.%s.Discard(ticket)\n\t\t\treturn lane.settle(ticket, %s.Refuse)\n\t\t}\n",
		read.name, read.name, read.name, structure)
	fmt.Fprintf(out, "\t\tif !available || !regionOK {\n\t\t\treturn lane.settle(ticket, %s.Refuse)\n\t\t}\n", structure)
	fmt.Fprintf(out, "\t\tcell, present = row.%sPolicy.Cell(cell, present)\n", read.name)
	fmt.Fprintf(out, "\t\tif !present {\n\t\t\treturn lane.settle(ticket, %s.NoCandidate)\n\t\t}\n", structure)
	fmt.Fprintf(out, "\t\tvalue, outcome := (%s{%s}).Reduce(cell)\n",
		reducerType, strings.Join(reducerLiteralFields(built, nil), ", "))
	fmt.Fprintf(out, "\t\tif outcome != %s.Concrete {\n\t\t\treturn lane.settle(ticket, outcome)\n\t\t}\n", structure)
	fmt.Fprintf(out, "\t\toutcome = %s.PublishExact(ticket, row.write, &lane.write, region, value)\n", execution)
	fmt.Fprintf(out, "\t\tif !ticket.Submit(outcome) {\n\t\t\treturn %s.Result{}, false\n\t\t}\n", execution)
	fmt.Fprintf(out, "\t\twritten := 0\n\t\tif outcome == %s.Concrete {\n\t\t\twritten = 1\n\t\t}\n", structure)
	fmt.Fprintf(out, "\t\treturn %s.NewResult(outcome, written)\n", execution)
	fmt.Fprintf(out, "\tcase %s.ReadExhausted:\n", execution)
	fmt.Fprintf(out, "\t\tif !row.%s.Close(ticket, &lane.%s) {\n\t\t\treturn lane.settle(ticket, %s.Refuse)\n\t\t}\n", read.name, read.name, structure)
	fmt.Fprintf(out, "\t\treturn lane.settle(ticket, %s.NoCandidate)\n", structure)
	out.WriteString("\tdefault:\n")
	fmt.Fprintf(out, "\t\t_ = lane.%s.Discard(ticket)\n\t\treturn lane.settle(ticket, %s.Refuse)\n", read.name, structure)
	out.WriteString("\t}\n}\n\n")
	return nil
}

func renderExecutePrologue(out *strings.Builder, built *plan) {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	fmt.Fprintf(out, "func (lane *%s) Execute(frame %s.Frame, ticket %s.Ticket) (%s.Result, bool) {\n",
		workerType, execution, execution, execution)
	fmt.Fprintf(out, "\tif lane == nil || lane.family == nil || lane.run == nil || !frame.Valid(ticket) || !lane.run.Owns(ticket) {\n\t\treturn %s.Result{}, false\n\t}\n", execution)
	out.WriteString("\tlocal, localOK := ticket.LocalOrdinal()\n")
	fmt.Fprintf(out, "\tif !localOK || uint64(local) >= uint64(len(lane.family.rows)) {\n\t\treturn %s.Result{}, false\n\t}\n", execution)
	out.WriteString("\trow := lane.family.rows[local]\n")
}

func renderExecuteEpilogue(out *strings.Builder, built *plan) {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	structure := imports.use(structurePackagePath)
	fmt.Fprintf(out, "\tif !ticket.Submit(outcome) {\n\t\treturn %s.Result{}, false\n\t}\n", execution)
	out.WriteString("\twritten := 0\n")
	fmt.Fprintf(out, "\tif outcome == %s.Concrete {\n\t\twritten = 1\n\t}\n", structure)
	fmt.Fprintf(out, "\treturn %s.NewResult(outcome, written)\n}\n\n", execution)
}

func renderCarryExecute(out *strings.Builder, built *plan) error {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	read := built.joins[0]
	out.WriteString("// Execute performs one carry invocation: the declared exact cell is reduced to\n")
	out.WriteString("// the fact this row publishes, and every carried coordinate passes through the\n")
	out.WriteString("// candidate's transition in the same patch.\n")
	renderExecutePrologue(out, built)
	fmt.Fprintf(out, "\toutcome := %s.FoldCarry(ticket, %s{%s}, row.%s, &lane.%s, row.write, &lane.write)\n",
		execution, reducerType, strings.Join(reducerLiteralFields(built, nil), ", "), read.name, read.name)
	renderExecuteEpilogue(out, built)
	return nil
}

// reducerLiteralFields spells the reducer literal the worker constructs, in
// the field order the type declares. Values supplied by the invocation are
// named by the caller; every other field takes the row's sealed carrier.
func reducerLiteralFields(built *plan, invocation map[string]string) []string {
	fields := reducerFields(built)
	spelled := make([]string, 0, len(fields)+1)
	if built.fold.state != nil {
		spelled = append(spelled, "state: lane.family.state")
	}
	for _, field := range fields {
		value := "row." + field
		if invocation != nil {
			if supplied, present := invocation[field]; present {
				value = supplied
			}
		}
		spelled = append(spelled, field+": "+value)
	}
	return spelled
}

func renderRouteExecute(out *strings.Builder, built *plan) error {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	structure := imports.use(structurePackagePath)
	route := built.route.join
	derivation := route.derivation

	invocation := map[string]string{}
	for _, join := range built.joins {
		if join == route {
			continue
		}
		switch join.read.Form {
		case program.Exact:
			invocation[fmt.Sprintf("input%d", join.position)] = fmt.Sprintf("input%d", join.position)
		case program.Summary:
			invocation[fmt.Sprintf("input%d", join.position)] = fmt.Sprintf("%sVector", join.name)
		}
	}

	out.WriteString("// Execute performs one routed invocation: the prerequisite reads are taken,\n")
	out.WriteString("// the declared relation derives this candidate's route set once, the selection\n")
	out.WriteString("// is observed at exactly those members, and one fold publishes at each.\n")
	renderExecutePrologue(out, built)

	for _, join := range built.joins {
		if join == route {
			continue
		}
		switch join.read.Form {
		case program.Exact:
			fmt.Fprintf(out, "\tvar input%d %s\n", join.position, imports.typeName(join.axis.fact))
			fmt.Fprintf(out, "\tswitch lane.%sCell(row.%s, row.%sPolicy, ticket, &input%d) {\n", join.name, join.name, join.name, join.position)
			fmt.Fprintf(out, "\tcase %s.NoCandidate:\n\t\treturn lane.settle(ticket, %s.NoCandidate)\n", structure, structure)
			fmt.Fprintf(out, "\tcase %s.Refuse:\n\t\treturn lane.settle(ticket, %s.Refuse)\n", structure, structure)
			out.WriteString("\t}\n")
		case program.Summary:
			renderMemberVector(out, built, join)
		default:
			return unexpressible(built.target.Spec.Key, fmt.Sprintf("a %s prerequisite of a routed output", readFormName(join.read.Form)),
				fmt.Sprintf("join %d is neither the route join nor a prerequisite the emitted worker delivers", join.position))
		}
	}

	arguments := make([]string, 0, len(derivation.staticAxes)+len(derivation.arguments))
	for _, axis := range derivation.staticAxes {
		arguments = append(arguments, "lane.family."+axis.param)
	}
	for _, argument := range derivation.arguments {
		switch {
		case argument.candidate:
			arguments = append(arguments, "row.candidate")
		case argument.many:
			if argument.join == nil || argument.join.memberSet == nil || argument.form != member.ReadFormSummary {
				return unexpressible(built.target.Spec.Key, "a relation derivation over a whole selection",
					fmt.Sprintf("relation %q consumes the cells of join %d, and only a whole-vector read has an emitted delivery", route.relation.Name, argument.join.position))
			}
			arguments = append(arguments, fmt.Sprintf("%sVector", argument.join.name))
		default:
			arguments = append(arguments, fmt.Sprintf("input%d", argument.join.position))
		}
	}
	out.WriteString("\t// The route set is the relation's own answer, derived once per invocation from\n")
	out.WriteString("\t// the carriers its declaration names. Nothing below re-derives it.\n")
	fmt.Fprintf(out, "\tderived, derivedOK := %s\n", imports.call(derivation.build, "", arguments...))
	fmt.Fprintf(out, "\tif !derivedOK {\n\t\treturn lane.settle(ticket, %s.Refuse)\n\t}\n", structure)
	fmt.Fprintf(out, "\tcount := %s\n", imports.call(derivation.count, "", "derived"))
	fmt.Fprintf(out, "\tif count < 0 || count > len(lane.members) || count > len(lane.cells) || count > len(lane.routes) {\n\t\treturn lane.settle(ticket, %s.Refuse)\n\t}\n", structure)
	out.WriteString("\tmembers := lane.members[:count]\n\tcells := lane.cells[:count]\n\troutes := lane.routes[:count]\n")
	out.WriteString("\tfor index := 0; index < count; index++ {\n")
	fmt.Fprintf(out, "\t\tselected, selectedOK := %s\n", imports.call(derivation.at, "", "derived", "index"))
	fmt.Fprintf(out, "\t\tif !selectedOK {\n\t\t\treturn lane.settle(ticket, %s.Refuse)\n\t\t}\n", structure)
	keyExpression, err := projectionExpression(built, route.key, "selected", "\t\t", out)
	if err != nil {
		return err
	}
	tagExpression, err := projectionExpression(built, route.predicate, "selected", "\t\t", out)
	if err != nil {
		return err
	}
	destinationExpression, err := projectionExpression(built, built.route.destination, "selected", "\t\t", out)
	if err != nil {
		return err
	}
	if route.key.Result != route.axis.source.Binding.Key.Carrier {
		return unexpressible(built.target.Spec.Key, "a route key that is not the axis's own key carrier",
			fmt.Sprintf("projection %q publishes %s", route.key.Name, route.key.Result))
	}
	fmt.Fprintf(out, "\t\tdense, denseOK := %s\n", imports.call(route.axis.normalizer, "lane.family."+route.axis.param, keyExpression))
	fmt.Fprintf(out, "\t\tif !denseOK {\n\t\t\treturn lane.settle(ticket, %s.Refuse)\n\t\t}\n", structure)
	fmt.Fprintf(out, "\t\tdestinationDense, destinationDenseOK := %s\n", imports.call(route.axis.normalizer, "lane.family."+route.axis.param, destinationExpression))
	fmt.Fprintf(out, "\t\tif !destinationDenseOK {\n\t\t\treturn lane.settle(ticket, %s.Refuse)\n\t\t}\n", structure)
	fmt.Fprintf(out, "\t\tmember, memberOK := lane.family.plane.RouteMember(uint32(dense), uint32(destinationDense), uint64(%s))\n", tagExpression)
	fmt.Fprintf(out, "\t\tif !memberOK {\n\t\t\treturn lane.settle(ticket, %s.Refuse)\n\t\t}\n", structure)
	out.WriteString("\t\tmembers[index] = member\n")
	fmt.Fprintf(out, "\t\troutes[index] = %s\n", destinationExpression)
	out.WriteString("\t}\n")

	out.WriteString("\t// An empty derived relation is a read that named nothing, which is exhausted\n")
	out.WriteString("\t// rather than available; anything else is a selection that did not observe.\n")
	fmt.Fprintf(out, "\tstatus := row.%s.Observe(ticket, &lane.%s, members, cells)\n", route.name, route.name)
	out.WriteString("\tif count == 0 {\n")
	fmt.Fprintf(out, "\t\tif status != %s.ReadExhausted {\n\t\t\treturn lane.settle(ticket, %s.Refuse)\n\t\t}\n", execution, structure)
	fmt.Fprintf(out, "\t} else if status != %s.ReadAvailable {\n\t\treturn lane.settle(ticket, %s.Refuse)\n\t}\n", execution, structure)
	fmt.Fprintf(out, "\toutcome := %s.FoldSelectedRoute(ticket, row.write, &lane.write, cells, members, routes, %s{%s})\n",
		execution, reducerType, strings.Join(reducerLiteralFields(built, invocation), ", "))
	renderExecuteEpilogue(out, built)

	for _, join := range built.joins {
		if join == route {
			continue
		}
		switch join.read.Form {
		case program.Exact:
			if err := renderExactCell(out, built, join); err != nil {
				return err
			}
		case program.Summary:
			renderMemberCell(out, built, join)
		}
	}
	return nil
}

// memberSetJoins is the declaration's ordered member-set reads: the joins whose
// relation is a self-provided nested member set, and whose Summary read is
// therefore delivered as one vector per invocation.
func memberSetJoins(built *plan) []*joinPlan {
	joins := make([]*joinPlan, 0, len(built.joins))
	for _, join := range built.joins {
		if join.memberSet != nil {
			joins = append(joins, join)
		}
	}
	return joins
}

// renderMemberVector emits one invocation's delivery of a nested member set:
// every declared ordinal is read at its own sealed coordinate into the lane's
// cell buffer, and the filled buffer is viewed as the vector its reader is
// declared to receive. Absence is carried per cell, so an unwritten member
// stays the cell its owner declared at that ordinal.
func renderMemberVector(out *strings.Builder, built *plan, join *joinPlan) {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	structure := imports.use(structurePackagePath)
	fmt.Fprintf(out, "\t%sCount := len(row.%s)\n", join.name, join.name)
	fmt.Fprintf(out, "\tif %sCount > len(lane.%sCells) {\n\t\treturn lane.settle(ticket, %s.Refuse)\n\t}\n",
		join.name, join.name, structure)
	fmt.Fprintf(out, "\t%sCells := lane.%sCells[:%sCount]\n", join.name, join.name, join.name)
	fmt.Fprintf(out, "\tfor index := 0; index < %sCount; index++ {\n", join.name)
	fmt.Fprintf(out, "\t\tif lane.%sCell(row.%s[index], row.%sPolicy, ticket, &%sCells[index]) != %s.Concrete {\n\t\t\treturn lane.settle(ticket, %s.Refuse)\n\t\t}\n",
		join.name, join.name, join.name, join.name, structure, structure)
	out.WriteString("\t}\n")
	fmt.Fprintf(out, "\t%sVector, %sVectorOK := %s.NewMemberVector(%sCells)\n", join.name, join.name, execution, join.name)
	fmt.Fprintf(out, "\tif !%sVectorOK {\n\t\treturn lane.settle(ticket, %s.Refuse)\n\t}\n", join.name, structure)
}

// renderMemberCell emits the cursor discipline one member of a nested set is
// read under: open, take the cell, close, and return the lane to service so the
// next ordinal opens on it. A member coordinate the plane never declared is not
// an absence - it is a census disagreeing with the Factor - so it refuses
// rather than settling as an absent candidate.
func renderMemberCell(out *strings.Builder, built *plan, join *joinPlan) {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	structure := imports.use(structurePackagePath)
	fmt.Fprintf(out, "// %sCell takes one member of a nested set at its own sealed coordinate.\n", join.name)
	fmt.Fprintf(out, "func (lane *%s) %sCell(read %s.ExactRead[%s, %s], policy %s.ReadCellPolicy[%s], ticket %s.Ticket, destination *%s.MemberCell[%s]) %s.ReductionOutcome {\n",
		workerType, join.name, execution, imports.typeName(join.axis.dense), imports.typeName(join.axis.fact),
		execution, imports.typeName(join.axis.fact),
		execution, execution, imports.typeName(join.axis.fact), structure)
	fmt.Fprintf(out, "\tif lane == nil || destination == nil || !read.Valid() {\n\t\treturn %s.Refuse\n\t}\n", structure)
	fmt.Fprintf(out, "\tif read.Read(ticket, &lane.%s) != %s.ReadAvailable {\n\t\t_ = lane.%s.Discard(ticket)\n\t\treturn %s.Refuse\n\t}\n",
		join.name, execution, join.name, structure)
	fmt.Fprintf(out, "\tcell, available := lane.%s.Value()\n", join.name)
	fmt.Fprintf(out, "\tpresent := lane.%s.Present()\n", join.name)
	fmt.Fprintf(out, "\tif !read.Close(ticket, &lane.%s) || !lane.%s.Reuse(ticket) {\n\t\t_ = lane.%s.Discard(ticket)\n\t\treturn %s.Refuse\n\t}\n",
		join.name, join.name, join.name, structure)
	fmt.Fprintf(out, "\tif !available {\n\t\treturn %s.Refuse\n\t}\n", structure)
	out.WriteString("\tcell, present = policy.Cell(cell, present)\n")
	fmt.Fprintf(out, "\t*destination = %s.MemberCell[%s]{Value: cell, Present: present}\n", execution, imports.typeName(join.axis.fact))
	fmt.Fprintf(out, "\treturn %s.Concrete\n}\n\n", structure)
}

// projectionExpression emits the destructuring of one owner projection
// accessor and answers the expression its declared result index names. The
// result convention is the owner's: a sole-result accessor binds one name, a
// paired one binds both and the index selects.
func projectionExpression(built *plan, projection definition.Projection, receiver, indent string, out *strings.Builder) (string, error) {
	return projectionExpressionRefusing(built, projection, receiver, indent,
		"return lane.settle(ticket, "+built.imports.use(structurePackagePath)+".Refuse)", out)
}

// projectionExpressionRefusing is projectionExpression under a caller-supplied
// refusal. The destructuring is the owner's convention either way; only the
// statement a failed projection returns through belongs to the surface it is
// emitted into.
func projectionExpressionRefusing(built *plan, projection definition.Projection, receiver, indent, refusal string, out *strings.Builder) (string, error) {
	imports := built.imports
	call := imports.call(projection.Accessor, receiver)
	prefix := strings.ToLower(projection.Name[:1]) + projection.Name[1:]
	switch projection.Accessor.ResultIndex {
	case -1:
		fmt.Fprintf(out, "%s%s, %sOK := %s\n", indent, prefix, prefix, call)
		fmt.Fprintf(out, "%sif !%sOK {\n%s\t%s\n%s}\n", indent, prefix, indent, refusal, indent)
		return prefix, nil
	case 0:
		fmt.Fprintf(out, "%s%s, %sPaired, %sOK := %s\n", indent, prefix, prefix, prefix, call)
		fmt.Fprintf(out, "%s_ = %sPaired\n", indent, prefix)
	case 1:
		fmt.Fprintf(out, "%s%sPaired, %s, %sOK := %s\n", indent, prefix, prefix, prefix, call)
		fmt.Fprintf(out, "%s_ = %sPaired\n", indent, prefix)
	default:
		return "", unexpressible(built.target.Spec.Key, "a projection accessor with an unreachable result index",
			fmt.Sprintf("projection %q names result %d", projection.Name, projection.Accessor.ResultIndex))
	}
	fmt.Fprintf(out, "%sif !%sOK {\n%s\t%s\n%s}\n", indent, prefix, indent, refusal, indent)
	return prefix, nil
}

// renderExactCell emits the one cursor discipline an exact prerequisite read
// follows: open, close, and answer the cell under this read's own sealed
// materialization policy. An exact cursor delivers the observed coordinate
// unchanged and leaves the substitution to its caller, so the row's policy -
// derived by the execution layer from the declared contract and the Factor the
// read is sealed against - is what says whether an unwritten coordinate is this
// rule's absent candidate or the Factor's declared default.
func renderExactCell(out *strings.Builder, built *plan, join *joinPlan) error {
	imports := built.imports
	execution := imports.use(executionPackagePath)
	structure := imports.use(structurePackagePath)
	fmt.Fprintf(out, "// %sCell takes one exact prerequisite cell. The cursor is closed before the\n", join.name)
	out.WriteString("// value is used, and the row's sealed policy settles what an unwritten\n")
	out.WriteString("// coordinate delivers.\n")
	fmt.Fprintf(out, "func (lane *%s) %sCell(read %s.ExactRead[%s, %s], policy %s.ReadCellPolicy[%s], ticket %s.Ticket, destination *%s) %s.ReductionOutcome {\n",
		workerType, join.name, execution, imports.typeName(join.axis.dense), imports.typeName(join.axis.fact),
		execution, imports.typeName(join.axis.fact),
		execution, imports.typeName(join.axis.fact), structure)
	fmt.Fprintf(out, "\tif lane == nil || destination == nil || !read.Valid() {\n\t\treturn %s.Refuse\n\t}\n", structure)
	fmt.Fprintf(out, "\tswitch read.Read(ticket, &lane.%s) {\n", join.name)
	fmt.Fprintf(out, "\tcase %s.ReadAvailable:\n", execution)
	fmt.Fprintf(out, "\t\tcell, available := lane.%s.Value()\n", join.name)
	fmt.Fprintf(out, "\t\tpresent := lane.%s.Present()\n", join.name)
	fmt.Fprintf(out, "\t\tif !read.Close(ticket, &lane.%s) {\n\t\t\t_ = lane.%s.Discard(ticket)\n\t\t\treturn %s.Refuse\n\t\t}\n",
		join.name, join.name, structure)
	fmt.Fprintf(out, "\t\tif !available {\n\t\t\treturn %s.Refuse\n\t\t}\n", structure)
	fmt.Fprintf(out, "\t\tcell, present = policy.Cell(cell, present)\n")
	fmt.Fprintf(out, "\t\tif !present {\n\t\t\treturn %s.NoCandidate\n\t\t}\n", structure)
	out.WriteString("\t\t*destination = cell\n")
	fmt.Fprintf(out, "\t\treturn %s.Concrete\n", structure)
	fmt.Fprintf(out, "\tcase %s.ReadExhausted:\n", execution)
	fmt.Fprintf(out, "\t\tif !read.Close(ticket, &lane.%s) {\n\t\t\treturn %s.Refuse\n\t\t}\n", join.name, structure)
	fmt.Fprintf(out, "\t\treturn %s.NoCandidate\n", structure)
	out.WriteString("\tdefault:\n")
	fmt.Fprintf(out, "\t\t_ = lane.%s.Discard(ticket)\n\t\treturn %s.Refuse\n", join.name, structure)
	out.WriteString("\t}\n}\n\n")
	return nil
}
