package outputowners

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

// Generate rebuilds or checks the cold Program output-owner evidence source.
func Generate(out string, check bool) error {
	evidence, err := Build()
	if err != nil {
		return err
	}
	rendered, err := render(evidence)
	if err != nil {
		return err
	}
	current, readErr := os.ReadFile(out)
	if check {
		if readErr != nil || !bytes.Equal(current, rendered) {
			return fmt.Errorf("Program output owners: evidence is stale")
		}
		return nil
	}
	if err := os.WriteFile(out, rendered, 0o644); err != nil {
		return fmt.Errorf("Program output owners: write evidence: %w", err)
	}
	return nil
}

func render(e Evidence) ([]byte, error) {
	var out strings.Builder
	out.WriteString("// Code generated by Program output-owner evidence; DO NOT EDIT.\n\npackage outputowners\n\n")
	out.WriteString("import \"github.com/wippyai/go-lua/program/internal/schema/relations\"\n\n")
	fmt.Fprintf(&out, "func init() {\n\tGenerated = Evidence{\n\t\tSchemaDigest: %q,\n\t\tDigest: %q,\n\t\tRows: []Row{\n", e.SchemaDigest, e.Digest)
	for _, row := range e.Rows {
		fmt.Fprintf(&out, "\t\t\t{Output: %q, Owner: relations.Owner(%d)},\n", row.Output, row.Owner)
	}
	out.WriteString("\t\t},\n\t}\n}\n")
	return format.Source([]byte(out.String()))
}
