// Code generated by axis member definition generator; DO NOT EDIT.

package static

//go:generate go run ../../analysis/schema/axis/member/generator/cmd -source static-type -cold rule_members.go -relations generated_relation_owner.go

import (
	schemaapi "github.com/wippyai/go-lua/analysis/schema"
	"github.com/wippyai/go-lua/analysis/schema/axis/member"
)

const (
	TypeFactTransfers       schemaapi.Key  = "static-type/storage-transfer/candidates"
	TypeFactSources         schemaapi.Key  = "static-type/storage-transfer/sources"
	TypeFactSourceKey       schemaapi.Key  = "static-type/storage-transfer/source-key"
	IdentityTypeFactReducer schemaapi.Key  = "static-type/reducer/identity"
	CoordinateCarrier       member.Carrier = "carrier/value/coordinate"
	TypeFactCarrier         member.Carrier = "carrier/static-type/fact"
	StorageTransferCarrier  member.Carrier = "carrier/value/storage-transfer"
)

// AxisMemberCatalog is static-type's declaration-only member vocabulary.
func AxisMemberCatalog() member.Catalog {
	valueAxis := schemaapi.EntryReference{Surface: schemaapi.SurfaceKindAxis, Key: "static-type"}
	catalog, ok := member.NewCatalog(
		[]member.Relation{
			{Key: TypeFactTransfers, Subject: StorageTransferCarrier, CandidateProvider: member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "static-type"}, Member: "static-type/storage-transfer/candidates"}},
			{Key: TypeFactSources, Subject: TypeFactCarrier, CandidateProvider: member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "static-type"}, Member: "static-type/storage-transfer/candidates"}, Inputs: []member.Carrier{StorageTransferCarrier}},
		},
		[]member.Projection{
			{Key: TypeFactSourceKey, Relation: TypeFactSources, Role: member.Key, Result: CoordinateCarrier, CandidateProvider: member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "static-type"}, Member: "static-type/storage-transfer/candidates"}},
		},
		[]member.Reducer{
			{Key: IdentityTypeFactReducer, Inputs: []member.ReducerInput{
				{Axis: valueAxis, Carrier: TypeFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: TypeFactCarrier},
			}},
		},
		[]member.CarryTransform{},
	)
	if !ok {
		panic("static: invalid axis member catalog")
	}
	return catalog
}
