// Code generated by axis member definition generator; DO NOT EDIT.
// This file is the immutable bind-time relation owner for the axis.

package value

import (
	"github.com/wippyai/go-lua/analysis/identity"
	memberrelation "github.com/wippyai/go-lua/analysis/schema/axis/member/relation"
	structure "github.com/wippyai/go-lua/analysis/schema/structure"
)

// RelationOwner is the generated bind-time owner for value's member relations.
type RelationOwner struct {
	schema        *Schema
	sourceColumn2 memberrelation.SourceColumn[Value]
}

var _ memberrelation.Owner = (*RelationOwner)(nil)

var _ memberrelation.SourceColumns[Value] = (*RelationOwner)(nil)

// NewRelationOwner binds the generated relation owner to one immutable axis schema.
func NewRelationOwner(schema *Schema) *RelationOwner {
	if schema == nil {
		return nil
	}
	owner := &RelationOwner{schema: schema}
	if !owner.materializeSourceColumns() {
		return nil
	}
	return owner
}

// Candidate resolves one mounted occurrence to the owner-issued dense candidate ordinal.
func (owner *RelationOwner) Candidate(relationOrdinal uint32, mount, occurrence identity.ContentID) (uint32, bool) {
	if owner == nil || owner.schema == nil || !mount.Available() || !occurrence.Available() {
		return 0, false
	}
	switch relationOrdinal {
	case 0:
		candidate, candidateOK := owner.schema.StorageTransferForArtifactOccurrence(mount, occurrence)
		if !candidateOK {
			return 0, false
		}
		return owner.schema.StorageTransferOrdinal(candidate)
	case 2:
		candidate, candidateOK := owner.schema.SourceSeedForMountedOccurrence(mount, occurrence)
		if !candidateOK {
			return 0, false
		}
		return owner.schema.SourceSeedOrdinal(candidate)
	default:
		return 0, false
	}
}

// Project projects one dense candidate through one relation/projection pair to a local coordinate ordinal.
func (owner *RelationOwner) Project(relationOrdinal, projectionOrdinal, candidateOrdinal uint32) (uint32, bool) {
	if owner == nil || owner.schema == nil {
		return 0, false
	}
	switch relationOrdinal {
	case 0:
		switch projectionOrdinal {
		case 1:
			candidate, candidateOK := owner.schema.StorageTransferAt(int(candidateOrdinal))
			if !candidateOK {
				return 0, false
			}
			first, second, projectionOK := candidate.Endpoints()
			if !projectionOK {
				return 0, false
			}
			_ = first
			projected := second
			return owner.schema.CoordinateIndex(projected)
		default:
			return 0, false
		}
	case 1:
		switch projectionOrdinal {
		case 0:
			candidate, candidateOK := owner.schema.StorageTransferAt(int(candidateOrdinal))
			if !candidateOK {
				return 0, false
			}
			first, second, projectionOK := candidate.Endpoints()
			if !projectionOK {
				return 0, false
			}
			_ = second
			projected := first
			return owner.schema.CoordinateIndex(projected)
		default:
			return 0, false
		}
	case 2:
		switch projectionOrdinal {
		case 2:
			candidate, candidateOK := owner.schema.SourceSeedAt(int(candidateOrdinal))
			if !candidateOK {
				return 0, false
			}
			first, second, projectionOK := candidate.Result()
			if !projectionOK {
				return 0, false
			}
			_ = second
			projected := first
			return owner.schema.CoordinateIndex(projected)
		default:
			return 0, false
		}
	default:
		return 0, false
	}
}

// materializeSourceColumns seals each owner-issued source fact column once.
func (owner *RelationOwner) materializeSourceColumns() bool {
	if owner == nil || owner.schema == nil {
		return false
	}
	count2 := owner.schema.SourceSeedCount()
	if count2 < 0 {
		return false
	}
	facts2 := make([]Value, count2)
	for index := 0; index < count2; index++ {
		candidate, candidateOK := owner.schema.SourceSeedAt(index)
		if !candidateOK {
			return false
		}
		fact, outcome := SourceFact(candidate)
		if outcome != structure.Concrete {
			return false
		}
		facts2[index] = fact
	}
	owner.sourceColumn2 = memberrelation.NewSourceColumn(facts2)
	return true
}

// SourceFactColumn returns the immutable typed source fact column for one relation.
// RelationCount is the sealed relation-ordinal extent. It preserves absent
// materializations separately from a valid empty source column.
func (*RelationOwner) RelationCount() int { return 3 }

func (owner *RelationOwner) SourceFactColumn(relationOrdinal uint32) (memberrelation.SourceColumn[Value], bool) {
	if owner == nil || owner.schema == nil {
		return memberrelation.SourceColumn[Value]{}, false
	}
	switch relationOrdinal {
	case 2:
		return owner.sourceColumn2, true
	default:
		return memberrelation.SourceColumn[Value]{}, false
	}
}
