// Code generated by axis member definition generator; DO NOT EDIT.

package value

//go:generate go run ../../analysis/schema/axis/member/generator/cmd -source value -cold rule_members.go -relations generated_relation_owner.go

import (
	schemaapi "github.com/wippyai/go-lua/analysis/schema"
	"github.com/wippyai/go-lua/analysis/schema/axis/member"
)

const (
	StorageTransferCandidates          schemaapi.Key  = "value/storage-transfer/candidates"
	BinaryArithmeticCandidates         schemaapi.Key  = "value/binary-arithmetic/candidates"
	BinaryEqualityCandidates           schemaapi.Key  = "value/binary-equality/candidates"
	BinaryOrderCandidates              schemaapi.Key  = "value/binary-order/candidates"
	PresenceRefinementCandidates       schemaapi.Key  = "value/presence-refinement/candidates"
	StorageTransferSources             schemaapi.Key  = "value/storage-transfer/sources"
	SourceSeeds                        schemaapi.Key  = "value/source/candidates"
	GlobalBootstrapResults             schemaapi.Key  = "value/global-bootstrap/candidates"
	MountedCallArgumentCandidates      schemaapi.Key  = "value/mounted-call/argument-candidates"
	MountedCallArguments               schemaapi.Key  = "value/mounted-call/arguments"
	AllocationResults                  schemaapi.Key  = "value/allocation/candidates"
	FreshResultCalls                   schemaapi.Key  = "value/fresh-result/candidates"
	ReturnBoundaryCandidates           schemaapi.Key  = "value/return-boundary/candidates"
	ReturnBoundaryRoots                schemaapi.Key  = "value/return-boundary/roots"
	ReturnBoundaryMembers              schemaapi.Key  = "value/return-boundary/members"
	MountedCallParents                 schemaapi.Key  = "value/mounted-call/parents"
	MountedCallActualMembers           schemaapi.Key  = "value/mounted-call/actual-members"
	FreshResultRoutes                  schemaapi.Key  = "value/fresh-result/routes"
	BinaryArithmeticSources            schemaapi.Key  = "value/binary-arithmetic/sources"
	BinaryEqualitySources              schemaapi.Key  = "value/binary-equality/sources"
	PresenceRefinementSources          schemaapi.Key  = "value/presence-refinement/sources"
	BinaryOrderSources                 schemaapi.Key  = "value/binary-order/sources"
	ModuleLoadCallCandidates           schemaapi.Key  = "value/module-load/candidates"
	ModuleLoadArguments                schemaapi.Key  = "value/module-load/arguments"
	RuntimeKindCallCandidates          schemaapi.Key  = "value/runtime-kind/candidates"
	RuntimeKindSubjects                schemaapi.Key  = "value/runtime-kind/subjects"
	RuntimeKindComparisons             schemaapi.Key  = "value/runtime-kind/comparisons"
	MountedCallResultSlotCandidates    schemaapi.Key  = "value/mounted-call-result/candidates"
	ResultAliasRoutes                  schemaapi.Key  = "value/result-alias/routes"
	BodyReturnRoutes                   schemaapi.Key  = "value/body-result/routes"
	ClosedOperandParents               schemaapi.Key  = "value/closed-allocation/parents"
	ClosedOperandCells                 schemaapi.Key  = "value/closed-allocation/operands"
	StorageTransferSourceKey           schemaapi.Key  = "value/storage-transfer/source-key"
	StorageTransferTarget              schemaapi.Key  = "value/storage-transfer/target"
	SourceCoordinate                   schemaapi.Key  = "value/source/coordinate"
	GlobalBootstrapCoordinate          schemaapi.Key  = "value/global-bootstrap/coordinate"
	MountedCallArgumentKey             schemaapi.Key  = "value/mounted-call/argument-key"
	AllocationResultCoordinate         schemaapi.Key  = "value/allocation/coordinate"
	FreshResultCoordinate              schemaapi.Key  = "value/fresh-result/coordinate"
	ReturnBoundaryRootKey              schemaapi.Key  = "value/return-boundary/root-key"
	ReturnBoundaryMemberKey            schemaapi.Key  = "value/return-boundary/member-key"
	MountedCallCalleeKey               schemaapi.Key  = "value/mounted-call/callee-key"
	MountedCallActualKey               schemaapi.Key  = "value/mounted-call/actual-key"
	MountedCallActualTag               schemaapi.Key  = "value/mounted-call/actual-tag"
	FreshResultRouteKey                schemaapi.Key  = "value/fresh-result/route-key"
	FreshResultRouteDestination        schemaapi.Key  = "value/fresh-result/route-destination"
	FreshResultRouteTag                schemaapi.Key  = "value/fresh-result/route-tag"
	BinaryArithmeticLeft               schemaapi.Key  = "value/binary-arithmetic/left"
	BinaryArithmeticRight              schemaapi.Key  = "value/binary-arithmetic/right"
	BinaryArithmeticWrite              schemaapi.Key  = "value/binary-arithmetic/write"
	BinaryEqualityLeft                 schemaapi.Key  = "value/binary-equality/left"
	BinaryEqualityRight                schemaapi.Key  = "value/binary-equality/right"
	BinaryEqualityWrite                schemaapi.Key  = "value/binary-equality/write"
	PresenceRefinementSourceKey        schemaapi.Key  = "value/presence-refinement/source-key"
	PresenceRefinementWrite            schemaapi.Key  = "value/presence-refinement/write"
	BinaryOrderLeft                    schemaapi.Key  = "value/binary-order/left"
	BinaryOrderRight                   schemaapi.Key  = "value/binary-order/right"
	BinaryOrderWrite                   schemaapi.Key  = "value/binary-order/write"
	ModuleLoadArgumentKey              schemaapi.Key  = "value/module-load/argument-key"
	ModuleLoadResultCoordinate         schemaapi.Key  = "value/module-load/coordinate"
	RuntimeKindSubjectKey              schemaapi.Key  = "value/runtime-kind/subject-key"
	RuntimeKindComparisonKey           schemaapi.Key  = "value/runtime-kind/comparison-key"
	RuntimeKindWriteCoordinate         schemaapi.Key  = "value/runtime-kind/coordinate"
	RuntimeKindCallOccurrence          schemaapi.Key  = "value/runtime-kind/call-occurrence"
	MountedCallResultSlotCoordinate    schemaapi.Key  = "value/mounted-call-result/coordinate"
	ResultAliasRouteKey                schemaapi.Key  = "value/result-alias/route-key"
	ResultAliasRouteTag                schemaapi.Key  = "value/result-alias/route-tag"
	BodyReturnRouteKey                 schemaapi.Key  = "value/body-result/route-key"
	BodyReturnRouteTag                 schemaapi.Key  = "value/body-result/route-tag"
	ClosedOperandKey                   schemaapi.Key  = "value/closed-allocation/operand-key"
	IdentityReducer                    schemaapi.Key  = "value/reducer/identity"
	SourceReducer                      schemaapi.Key  = "value/reducer/source"
	GlobalBootstrapReducer             schemaapi.Key  = "value/reducer/global-bootstrap"
	FreshResultReducer                 schemaapi.Key  = "value/reducer/fresh-result"
	BinaryArithmeticReducer            schemaapi.Key  = "value/binary-arithmetic/reducer"
	BinaryEqualityReducer              schemaapi.Key  = "value/binary-equality/reducer"
	PresenceRefinementReducer          schemaapi.Key  = "value/presence-refinement/reducer"
	BinaryOrderReducer                 schemaapi.Key  = "value/binary-order/reducer"
	ModuleLoadCallReducer              schemaapi.Key  = "value/module-load/reducer"
	RuntimeKindCallReducer             schemaapi.Key  = "value/runtime-kind/reducer"
	AllocationResultReducer            schemaapi.Key  = "value/allocation/reducer"
	ResultAliasReducer                 schemaapi.Key  = "value/result-alias/reducer"
	BodyResultReducer                  schemaapi.Key  = "value/body-result/reducer"
	AllocationCarryTransform           schemaapi.Key  = "transform/value/allocation"
	FreshResultRouteCarryTransform     schemaapi.Key  = "transform/value/fresh-result-route"
	ValueCoordinateCarrier             member.Carrier = "carrier/value/coordinate"
	ValueFactCarrier                   member.Carrier = "carrier/value/fact"
	ValueAtomCarrier                   member.Carrier = "carrier/value/atom"
	StorageTransferCarrier             member.Carrier = "carrier/value/storage-transfer"
	BinaryArithmeticCarrier            member.Carrier = "carrier/value/binary-arithmetic"
	BinaryEqualityCarrier              member.Carrier = "carrier/value/binary-equality"
	BinaryOrderCarrier                 member.Carrier = "carrier/value/binary-order"
	PresenceRefinementCarrier          member.Carrier = "carrier/value/presence-refinement"
	SourceSeedCarrier                  member.Carrier = "carrier/value/source-seed"
	GlobalBootstrapResultCarrier       member.Carrier = "carrier/value/global-bootstrap-result"
	AllocationResultCarrier            member.Carrier = "carrier/value/allocation-result"
	FreshResultCallCarrier             member.Carrier = "carrier/value/fresh-result-call"
	MountedCallArgumentCarrier         member.Carrier = "carrier/value/mounted-call-argument"
	ReturnBoundaryCarrier              member.Carrier = "carrier/value/return-boundary"
	ReturnBoundaryMemberCarrier        member.Carrier = "carrier/value/return-boundary-member"
	ReturnBoundaryMemberOrdinalCarrier member.Carrier = "carrier/value/return-boundary-member-ordinal"
	MountedCallActualsCarrier          member.Carrier = "carrier/value/mounted-call-actuals"
	MountedCallActualTagCarrier        member.Carrier = "carrier/value/mounted-call-actual-tag"
	FreshResultTagCarrier              member.Carrier = "carrier/value/fresh-result-tag"
	FreshResultRouteCarrier            member.Carrier = "carrier/value/fresh-result-route"
	CallCoordinateCarrier              member.Carrier = "carrier/call/mounted-call"
	CallFactCarrier                    member.Carrier = "carrier/call/fact"
	FreshResultRouteTagCarrier         member.Carrier = "carrier/value/fresh-result-route-tag"
	ModuleLoadCallCarrier              member.Carrier = "carrier/value/module-load-call"
	RuntimeKindCallCarrier             member.Carrier = "carrier/value/runtime-kind-call"
	RuntimeKindCallOccurrenceCarrier   member.Carrier = "carrier/value/runtime-kind-call-occurrence"
	MountedCallResultSlotCarrier       member.Carrier = "carrier/value/mounted-call-result-slot"
	ResultAliasRouteCarrier            member.Carrier = "carrier/value/result-alias-route"
	ResultAliasRouteTagCarrier         member.Carrier = "carrier/value/result-alias-route-tag"
	BodyReturnRouteCarrier             member.Carrier = "carrier/value/body-return-route"
	BodyReturnRouteTagCarrier          member.Carrier = "carrier/value/body-return-route-tag"
	ClosedOperandsCarrier              member.Carrier = "carrier/value/closed-operands"
	ClosedOperandCarrier               member.Carrier = "carrier/value/closed-operand"
	HeapKeyCarrier                     member.Carrier = "carrier/heap/key"
)

// AxisMemberCatalog is value's declaration-only member vocabulary.
func AxisMemberCatalog() member.Catalog {
	valueAxis := schemaapi.EntryReference{Surface: schemaapi.SurfaceKindAxis, Key: "value"}
	catalog, ok := member.NewCatalog(
		[]member.Relation{
			{Key: StorageTransferCandidates, Subject: StorageTransferCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/storage-transfer/candidates"})},
			{Key: BinaryArithmeticCandidates, Subject: BinaryArithmeticCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-arithmetic/candidates"})},
			{Key: BinaryEqualityCandidates, Subject: BinaryEqualityCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-equality/candidates"})},
			{Key: BinaryOrderCandidates, Subject: BinaryOrderCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-order/candidates"})},
			{Key: PresenceRefinementCandidates, Subject: PresenceRefinementCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/presence-refinement/candidates"})},
			{Key: StorageTransferSources, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/storage-transfer/candidates"}), Inputs: []member.Carrier{StorageTransferCarrier}},
			{Key: SourceSeeds, Subject: SourceSeedCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/source/candidates"})},
			{Key: GlobalBootstrapResults, Subject: GlobalBootstrapResultCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/global-bootstrap/candidates"})},
			{Key: MountedCallArgumentCandidates, Subject: MountedCallArgumentCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/argument-candidates"})},
			{Key: MountedCallArguments, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/argument-candidates"}), Inputs: []member.Carrier{MountedCallArgumentCarrier}},
			{Key: AllocationResults, Subject: AllocationResultCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/allocation/candidates"})},
			{Key: FreshResultCalls, Subject: FreshResultCallCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/fresh-result/candidates"}), Inputs: []member.Carrier{CallCoordinateCarrier}, Parent: member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/parents"}, Ordinal: FreshResultTagCarrier},
			{Key: ReturnBoundaryCandidates, Subject: ReturnBoundaryCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/return-boundary/candidates"})},
			{Key: ReturnBoundaryRoots, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/return-boundary/candidates"}), Inputs: []member.Carrier{ReturnBoundaryCarrier}},
			{Key: ReturnBoundaryMembers, Subject: ReturnBoundaryMemberCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/return-boundary/members"}), Inputs: []member.Carrier{ReturnBoundaryCarrier}, Parent: member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/return-boundary/candidates"}, Ordinal: ReturnBoundaryMemberOrdinalCarrier},
			{Key: MountedCallParents, Subject: MountedCallActualsCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/parents"}), Inputs: []member.Carrier{CallCoordinateCarrier}, Correspondences: []member.RelationRef{member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/candidates"}}},
			{Key: MountedCallActualMembers, Subject: MountedCallArgumentCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/actual-members"}), Inputs: []member.Carrier{CallCoordinateCarrier}, Parent: member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/parents"}, Ordinal: MountedCallActualTagCarrier},
			{Key: FreshResultRoutes, Subject: FreshResultRouteCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/candidates"}), Inputs: []member.Carrier{CallCoordinateCarrier, CallFactCarrier}},
			{Key: BinaryArithmeticSources, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-arithmetic/candidates"}), Inputs: []member.Carrier{BinaryArithmeticCarrier}},
			{Key: BinaryEqualitySources, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-equality/candidates"}), Inputs: []member.Carrier{BinaryEqualityCarrier}},
			{Key: PresenceRefinementSources, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/presence-refinement/candidates"}), Inputs: []member.Carrier{PresenceRefinementCarrier}},
			{Key: BinaryOrderSources, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-order/candidates"}), Inputs: []member.Carrier{BinaryOrderCarrier}},
			{Key: ModuleLoadCallCandidates, Subject: ModuleLoadCallCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/module-load/candidates"})},
			{Key: ModuleLoadArguments, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/module-load/candidates"}), Inputs: []member.Carrier{ModuleLoadCallCarrier}},
			{Key: RuntimeKindCallCandidates, Subject: RuntimeKindCallCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/runtime-kind/candidates"})},
			{Key: RuntimeKindSubjects, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/runtime-kind/candidates"}), Inputs: []member.Carrier{RuntimeKindCallCarrier}},
			{Key: RuntimeKindComparisons, Subject: ValueFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/runtime-kind/candidates"}), Inputs: []member.Carrier{RuntimeKindCallCarrier}},
			{Key: MountedCallResultSlotCandidates, Subject: MountedCallResultSlotCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call-result/candidates"})},
			{Key: ResultAliasRoutes, Subject: ResultAliasRouteCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call-result/candidates"}), Inputs: []member.Carrier{MountedCallResultSlotCarrier, CallFactCarrier}},
			{Key: BodyReturnRoutes, Subject: BodyReturnRouteCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call-result/candidates"}), Inputs: []member.Carrier{MountedCallResultSlotCarrier, CallFactCarrier}},
			{Key: ClosedOperandParents, Subject: ClosedOperandsCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/closed-allocation/parents"}), Correspondences: []member.RelationRef{member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "heap"}, Member: "heap/closed-allocation/candidates"}}, PublishesKeyVector: true},
			{Key: ClosedOperandCells, Subject: ClosedOperandCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "heap"}, Member: "heap/closed-allocation/candidates"}), Inputs: []member.Carrier{HeapKeyCarrier}},
		},
		[]member.Projection{
			{Key: StorageTransferSourceKey, Relation: StorageTransferSources, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/storage-transfer/candidates"})},
			{Key: StorageTransferTarget, Relation: StorageTransferCandidates, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/storage-transfer/candidates"})},
			{Key: SourceCoordinate, Relation: SourceSeeds, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/source/candidates"})},
			{Key: GlobalBootstrapCoordinate, Relation: GlobalBootstrapResults, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/global-bootstrap/candidates"})},
			{Key: MountedCallArgumentKey, Relation: MountedCallArguments, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/argument-candidates"})},
			{Key: AllocationResultCoordinate, Relation: AllocationResults, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/allocation/candidates"})},
			{Key: FreshResultCoordinate, Relation: FreshResultCalls, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/fresh-result/candidates"})},
			{Key: ReturnBoundaryRootKey, Relation: ReturnBoundaryRoots, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/return-boundary/candidates"})},
			{Key: ReturnBoundaryMemberKey, Relation: ReturnBoundaryMembers, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/return-boundary/members"})},
			{Key: MountedCallCalleeKey, Relation: MountedCallParents, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/parents"})},
			{Key: MountedCallActualKey, Relation: MountedCallActualMembers, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/actual-members"})},
			{Key: MountedCallActualTag, Relation: MountedCallActualMembers, Role: member.Predicate, Result: MountedCallActualTagCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call/actual-members"})},
			{Key: FreshResultRouteKey, Relation: FreshResultRoutes, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/candidates"})},
			{Key: FreshResultRouteDestination, Relation: FreshResultRoutes, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/candidates"})},
			{Key: FreshResultRouteTag, Relation: FreshResultRoutes, Role: member.Predicate, Result: FreshResultRouteTagCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/candidates"})},
			{Key: BinaryArithmeticLeft, Relation: BinaryArithmeticSources, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-arithmetic/candidates"})},
			{Key: BinaryArithmeticRight, Relation: BinaryArithmeticSources, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-arithmetic/candidates"})},
			{Key: BinaryArithmeticWrite, Relation: BinaryArithmeticCandidates, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-arithmetic/candidates"})},
			{Key: BinaryEqualityLeft, Relation: BinaryEqualitySources, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-equality/candidates"})},
			{Key: BinaryEqualityRight, Relation: BinaryEqualitySources, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-equality/candidates"})},
			{Key: BinaryEqualityWrite, Relation: BinaryEqualityCandidates, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-equality/candidates"})},
			{Key: PresenceRefinementSourceKey, Relation: PresenceRefinementSources, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/presence-refinement/candidates"})},
			{Key: PresenceRefinementWrite, Relation: PresenceRefinementCandidates, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/presence-refinement/candidates"})},
			{Key: BinaryOrderLeft, Relation: BinaryOrderSources, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-order/candidates"})},
			{Key: BinaryOrderRight, Relation: BinaryOrderSources, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-order/candidates"})},
			{Key: BinaryOrderWrite, Relation: BinaryOrderCandidates, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/binary-order/candidates"})},
			{Key: ModuleLoadArgumentKey, Relation: ModuleLoadArguments, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/module-load/candidates"})},
			{Key: ModuleLoadResultCoordinate, Relation: ModuleLoadCallCandidates, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/module-load/candidates"})},
			{Key: RuntimeKindSubjectKey, Relation: RuntimeKindSubjects, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/runtime-kind/candidates"})},
			{Key: RuntimeKindComparisonKey, Relation: RuntimeKindComparisons, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/runtime-kind/candidates"})},
			{Key: RuntimeKindWriteCoordinate, Relation: RuntimeKindCallCandidates, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/runtime-kind/candidates"})},
			{Key: RuntimeKindCallOccurrence, Relation: RuntimeKindCallCandidates, Role: member.Identity, Result: RuntimeKindCallOccurrenceCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/runtime-kind/candidates"})},
			{Key: MountedCallResultSlotCoordinate, Relation: MountedCallResultSlotCandidates, Role: member.Destination, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call-result/candidates"})},
			{Key: ResultAliasRouteKey, Relation: ResultAliasRoutes, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call-result/candidates"})},
			{Key: ResultAliasRouteTag, Relation: ResultAliasRoutes, Role: member.Predicate, Result: ResultAliasRouteTagCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call-result/candidates"})},
			{Key: BodyReturnRouteKey, Relation: BodyReturnRoutes, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call-result/candidates"})},
			{Key: BodyReturnRouteTag, Relation: BodyReturnRoutes, Role: member.Predicate, Result: BodyReturnRouteTagCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "value"}, Member: "value/mounted-call-result/candidates"})},
			{Key: ClosedOperandKey, Relation: ClosedOperandCells, Role: member.Key, Result: ValueCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "heap"}, Member: "heap/closed-allocation/candidates"})},
		},
		[]member.Reducer{
			{Key: IdentityReducer, Inputs: []member.ReducerInput{
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: SourceReducer, Inputs: []member.ReducerInput{}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: GlobalBootstrapReducer, Inputs: []member.ReducerInput{}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: FreshResultReducer, Inputs: []member.ReducerInput{
				{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKindAxis, Key: "call"}, Carrier: CallFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormSelected, Multiplicity: member.MultiplicityOne, Tag: FreshResultRouteTagCarrier, Route: ValueCoordinateCarrier},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: BinaryArithmeticReducer, Inputs: []member.ReducerInput{
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: BinaryEqualityReducer, Inputs: []member.ReducerInput{
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: PresenceRefinementReducer, Inputs: []member.ReducerInput{
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: BinaryOrderReducer, Inputs: []member.ReducerInput{
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: ModuleLoadCallReducer, Inputs: []member.ReducerInput{
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
				{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKindAxis, Key: "call"}, Carrier: CallFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: RuntimeKindCallReducer, Inputs: []member.ReducerInput{
				{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKindAxis, Key: "call"}, Carrier: CallFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: AllocationResultReducer, Inputs: []member.ReducerInput{}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: ResultAliasReducer, Inputs: []member.ReducerInput{
				{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKindAxis, Key: "call"}, Carrier: CallFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormSelected, Multiplicity: member.MultiplicityMany, Tag: ResultAliasRouteTagCarrier},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
			{Key: BodyResultReducer, Inputs: []member.ReducerInput{
				{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKindAxis, Key: "call"}, Carrier: CallFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
				{Axis: valueAxis, Carrier: ValueFactCarrier, Form: member.ReadFormSelected, Multiplicity: member.MultiplicityMany, Tag: BodyReturnRouteTagCarrier},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: ValueFactCarrier},
			}},
		},
		[]member.CarryTransform{
			{Key: AllocationCarryTransform, Candidate: AllocationResultCarrier, Input: ValueFactCarrier, Output: ValueFactCarrier},
			{Key: FreshResultRouteCarryTransform, Candidate: FreshResultRouteCarrier, Input: ValueFactCarrier, Output: ValueFactCarrier},
		},
	)
	if !ok {
		panic("value: invalid axis member catalog")
	}
	return catalog
}
