// Code generated by analysis/semantic/inventory; DO NOT EDIT.
package product

import (
	"github.com/wippyai/go-lua/analysis/domain/value/axis"
	assertion "github.com/wippyai/go-lua/analysis/domain/value/axis/assertion"
	escape "github.com/wippyai/go-lua/analysis/domain/value/axis/escape"
	evidence "github.com/wippyai/go-lua/analysis/domain/value/axis/evidence"
	identity "github.com/wippyai/go-lua/analysis/domain/value/axis/identity"
	runtimekind "github.com/wippyai/go-lua/analysis/domain/value/axis/runtimekind"
	typewitness "github.com/wippyai/go-lua/analysis/domain/value/axis/typewitness"
	variantorigin "github.com/wippyai/go-lua/analysis/domain/value/axis/variantorigin"
)

var canonicalRegistry = mustCanonicalRegistry()

// CanonicalRegistry returns the frozen analyzer-owned value-axis registry.
// Its sparse-axis order is generated from the reviewed semantic inventory.
func CanonicalRegistry() *axis.Registry { return canonicalRegistry }

// RegistryWithCanonicalAxes returns a fresh frozen registry containing the
// canonical sparse axes followed by caller-provided sparse axes.
func RegistryWithCanonicalAxes(specs ...axis.ErasedSpec) (*axis.Registry, error) {
	canonical := []axis.ErasedSpec{
		variantorigin.Spec().Erase(),
		identity.Spec().Erase(),
		runtimekind.Spec().Erase(),
		typewitness.Spec().Erase(),
		escape.Spec().Erase(),
		evidence.Spec().Erase(),
		assertion.Spec().Erase(),
	}
	canonical = append(canonical, specs...)
	return RegistryWithAxes(canonical...)
}

func mustCanonicalRegistry() *axis.Registry {
	registry, err := RegistryWithCanonicalAxes()
	if err != nil {
		panic(err)
	}
	return registry
}
