package relbind

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"

	"github.com/wippyai/go-lua/analysis/relation/semantic/signature"
)

const header = "// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.\n\n"

// BindingFile is the file name one family's binding artifact is written under.
func BindingFile(family Family) string { return Prefix + snake(family.Stem) + ".go" }

// PayloadFile is the file name one axis's owner-column artifact is written
// under.
const PayloadFile = Prefix + "payload.go"

// Artifact is one emitted file: the axis directory it belongs to, the name it
// is written under, and its bytes.
type Artifact struct {
	Dir   string
	Name  string
	Bytes []byte
}

// Path is the module-relative path of one artifact.
func (artifact Artifact) Path() string { return artifact.Dir + "/" + artifact.Name }

// Emit renders every artifact the corpus admits: one owner-column publisher
// per axis that publishes a payload, and one binding per emitted family,
// each beside the owner whose mathematics it carries.
func Emit(corpus Corpus) ([]Artifact, error) {
	if err := corpus.Validate(); err != nil {
		return nil, err
	}
	artifacts := make([]Artifact, 0, len(corpus.Families)+len(corpus.Axes))
	for _, axis := range corpus.Axes {
		owned := corpus.AxisPayloads(axis.Key)
		if len(owned) == 0 {
			continue
		}
		rendered, err := emitPayloads(axis, owned)
		if err != nil {
			return nil, err
		}
		artifacts = append(artifacts, Artifact{Dir: axis.Dir, Name: PayloadFile, Bytes: rendered})
	}
	for _, family := range corpus.Families {
		if !family.Emitted() {
			continue
		}
		axis, _ := corpus.Axis(family.Axis)
		rendered, err := emitBinding(corpus, axis, family)
		if err != nil {
			return nil, err
		}
		artifacts = append(artifacts, Artifact{Dir: axis.Dir, Name: BindingFile(family), Bytes: rendered})
	}
	sort.Slice(artifacts, func(left, right int) bool { return artifacts[left].Path() < artifacts[right].Path() })
	return artifacts, nil
}

// emitBinding renders one family's thin typed semantic-operation binding: the
// columns it decodes through, the argument its decoder assembles, the contract
// its owner judgment answers, and the one substrate call that admits them.
func emitBinding(corpus Corpus, axis Axis, family Family) ([]byte, error) {
	used, err := familyPayloads(corpus, family)
	if err != nil {
		return nil, err
	}
	result, _ := corpus.Payload(family.Result)
	resultType := result.Type
	if !family.Publishes() {
		// A family that publishes no fact still instantiates the substrate's
		// result parameter, and the type it instantiates it with is the one
		// that can hold nothing.
		resultType = "struct{}"
	}

	var body bytes.Buffer
	fmt.Fprintf(&body, "package %s\n\n", axis.Package)
	writeImports(&body, imports([]string{
		`"github.com/wippyai/go-lua/analysis/relation/schema/model"`,
		`"github.com/wippyai/go-lua/analysis/relation/semantic/binding"`,
		`"github.com/wippyai/go-lua/analysis/relation/semantic/signature"`,
		`"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"`,
	}, used, axis))

	fmt.Fprintf(&body, "// %sColumns are the owner column codecs of the\n// %s binding.\ntype %sColumns struct {\n", family.Stem, family.Label(), family.Stem)
	for _, payload := range used {
		fmt.Fprintf(&body, "\t%s *relbindgen.Column[%s]\n", payload.Field, payload.Type)
	}
	body.WriteString("}\n\n")

	fmt.Fprintf(&body, "// New%sColumns names this family's own owner columns. A column an axis\n// other than this one publishes is handed in, never reached for.\nfunc New%sColumns(", family.Stem, family.Stem)
	for index, payload := range used {
		if index != 0 {
			body.WriteString(", ")
		}
		fmt.Fprintf(&body, "%s *relbindgen.Column[%s]", lower(payload.Field), payload.Type)
	}
	fmt.Fprintf(&body, ") (%sColumns, bool) {\n\tcolumns := %sColumns{", family.Stem, family.Stem)
	for index, payload := range used {
		if index != 0 {
			body.WriteString(", ")
		}
		fmt.Fprintf(&body, "%s: %s", payload.Field, lower(payload.Field))
	}
	fmt.Fprintf(&body, "}\n\tif !columns.Available() {\n\t\treturn %sColumns{}, false\n\t}\n\treturn columns, true\n}\n\n", family.Stem)

	fmt.Fprintf(&body, "// Available reports whether every column this binding needs carries an\n// owner-issued type and live storage.\nfunc (columns %sColumns) Available() bool {\n\treturn ", family.Stem)
	for index, payload := range used {
		if index != 0 {
			body.WriteString(" && ")
		}
		fmt.Fprintf(&body, "columns.%s.Available()", payload.Field)
	}
	body.WriteString("\n}\n\n")

	fmt.Fprintf(&body, "// %sArgument is the decoded frame of one\n// %s invocation.\ntype %sArgument struct {\n", family.Stem, family.Label(), family.Stem)
	for _, slot := range family.Inputs {
		payload, _ := corpus.Payload(slot.Payload)
		if slot.Delivery == signature.ScalarDelivery {
			fmt.Fprintf(&body, "\t%s %s\n", slot.Field, payload.Type)
			continue
		}
		fmt.Fprintf(&body, "\t%s relbindgen.Span[%s]\n", slot.Field, payload.Type)
	}
	body.WriteString("}\n\n")

	fmt.Fprintf(&body, "// %sJudgment is the owner mathematics this binding carries. The axis\n// states it by hand: nothing in this file can name a relation, a cell, a\n// buffer or an engine value, so the mathematics stays where its owner wrote\n// it and this artifact stays free of it.\ntype %sJudgment interface {\n\trelbindgen.Operation[%sArgument, %s]\n\tAvailable() bool\n}\n\n", family.Stem, family.Stem, family.Stem, resultType)

	fmt.Fprintf(&body, "// The hand-authored judgment answers this family's own contract, and the\n// assertion is what makes the two halves one binding.\nvar _ %sJudgment = %s{}\n\n", family.Stem, family.Judgment)

	address := fmt.Sprintf("%d", family.Address)
	switch family.Address {
	case KeyedDestination:
		address = "relbindgen.KeyedDestination"
	case NoDestination:
		address = "relbindgen.NoDestination"
	}
	encoder := fmt.Sprintf("\n\t\tEncoder:   %sEncoder{columns: columns},", lower(family.Stem))
	if !family.Publishes() {
		encoder = ""
	}
	fmt.Fprintf(&body, "// Bind%s admits the %s family\n// under its sealed signature.\nfunc Bind%s(operation signature.Signature, judgment %sJudgment, columns %sColumns, refusal model.RefusalID) (binding.Factory, bool) {\n\tif judgment == nil || !judgment.Available() || !columns.Available() {\n\t\treturn nil, false\n\t}\n\treturn relbindgen.Bind(relbindgen.Spec[%sArgument, %s]{\n\t\tSignature: operation,\n\t\tDecoder:   %sDecoder{columns: columns},%s\n\t\tOperation: judgment,\n\t\tAddress:   %s,\n\t\tRefusal:   refusal,\n\t})\n}\n\n",
		family.Stem, family.Label(), family.Stem, family.Stem, family.Stem, family.Stem, resultType, lower(family.Stem), encoder, address)

	fmt.Fprintf(&body, "type %sDecoder struct {\n\tcolumns %sColumns\n}\n\n", lower(family.Stem), family.Stem)
	fmt.Fprintf(&body, "func (decoder %sDecoder) Decode(inputs relbindgen.Inputs) (%sArgument, bool) {\n", lower(family.Stem), family.Stem)
	for index, slot := range family.Inputs {
		payload, _ := corpus.Payload(slot.Payload)
		reader := "ScalarAt"
		if slot.Delivery != signature.ScalarDelivery {
			reader = "SpanAt"
		}
		fmt.Fprintf(&body, "\t%s, ok := relbindgen.%s(inputs, %d, decoder.columns.%s)\n\tif !ok {\n\t\treturn %sArgument{}, false\n\t}\n", lower(slot.Field), reader, index, payload.Field, family.Stem)
	}
	fmt.Fprintf(&body, "\treturn %sArgument{", family.Stem)
	for index, slot := range family.Inputs {
		if index != 0 {
			body.WriteString(", ")
		}
		fmt.Fprintf(&body, "%s: %s", slot.Field, lower(slot.Field))
	}
	body.WriteString("}, true\n}\n\n")

	if !family.Publishes() {
		return render(body.Bytes())
	}
	fmt.Fprintf(&body, "type %sEncoder struct {\n\tcolumns %sColumns\n}\n\n", lower(family.Stem), family.Stem)
	fmt.Fprintf(&body, "func (encoder %sEncoder) Encode(outputs relbindgen.Outputs, value %s) bool {\n", lower(family.Stem), resultType)
	for index, column := range family.Outputs {
		payload, _ := corpus.Payload(column.Payload)
		carried := "value"
		if column.Field != "" {
			carried = "value." + column.Field
		}
		if index == len(family.Outputs)-1 {
			fmt.Fprintf(&body, "\treturn relbindgen.PutColumn(outputs, %d, encoder.columns.%s, %s)\n", index, payload.Field, carried)
			continue
		}
		fmt.Fprintf(&body, "\tif !relbindgen.PutColumn(outputs, %d, encoder.columns.%s, %s) {\n\t\treturn false\n\t}\n", index, payload.Field, carried)
	}
	body.WriteString("}\n")

	return render(body.Bytes())
}

// emitPayloads renders one axis's thin typed owner-column publisher: a Column
// per payload the axis declares, over its own solve-local store, and one
// ascent authority per TypeID that states an order.
func emitPayloads(axis Axis, owned []Payload) ([]byte, error) {
	var body bytes.Buffer
	fmt.Fprintf(&body, "package %s\n\n", axis.Package)
	writeImports(&body, imports([]string{
		`"github.com/wippyai/go-lua/analysis/identity"`,
		`"github.com/wippyai/go-lua/analysis/relation/schema/model"`,
		`"github.com/wippyai/go-lua/analysis/relation/semantic/binding"`,
		`"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"`,
	}, owned, axis))

	body.WriteString("// PayloadTypes names the owner-issued TypeID each column of this axis\n// carries.\ntype PayloadTypes struct {\n")
	for _, payload := range owned {
		fmt.Fprintf(&body, "\t%s model.TypeID\n", payload.Field)
	}
	body.WriteString("}\n\n// Available reports whether every column has an owner-issued type.\nfunc (types PayloadTypes) Available() bool {\n\treturn ")
	writeConjunction(&body, owned, "types.%s.Available()")
	body.WriteString("\n}\n\n")

	body.WriteString("// PayloadTags names the store fence each column of this axis interns under.\ntype PayloadTags struct {\n")
	for _, payload := range owned {
		fmt.Fprintf(&body, "\t%s identity.ContentID\n", payload.Field)
	}
	body.WriteString("}\n\n// Available reports whether every column has a store fence.\nfunc (tags PayloadTags) Available() bool {\n\treturn ")
	writeConjunction(&body, owned, "tags.%s.Available()")
	body.WriteString("\n}\n\n")

	body.WriteString("// Payloads is this axis's thin typed owner-column publisher: one Column per\n// payload type the axis declares, each over its own solve-local store, and\n// the only place one of its domain values crosses into a value token.\ntype Payloads struct {\n")
	for _, payload := range owned {
		fmt.Fprintf(&body, "\t%s *relbindgen.Column[%s]\n", payload.Field, payload.Type)
	}
	body.WriteString("}\n\n")

	body.WriteString("// NewPayloads installs one column per declared payload over a store fenced\n// by that payload's own tag. Reserve is the interning reservation each store\n// starts with; a store grows past it, so it is a caller's sizing and never a\n// bound on what an owner may intern.\nfunc NewPayloads(types PayloadTypes, tags PayloadTags, reserve int) (Payloads, bool) {\n\tif !types.Available() || !tags.Available() || reserve < 0 {\n\t\treturn Payloads{}, false\n\t}\n\tvar payloads Payloads\n")
	for _, payload := range owned {
		store := lower(payload.Field) + "Store"
		fmt.Fprintf(&body, "\t%s, ok := relbindgen.NewStore[%s](tags.%s, reserve)\n\tif !ok {\n\t\treturn Payloads{}, false\n\t}\n\tif payloads.%s, ok = relbindgen.NewColumn(types.%s, %s); !ok {\n\t\treturn Payloads{}, false\n\t}\n", store, payload.Type, payload.Field, payload.Field, payload.Field, store)
	}
	body.WriteString("\treturn payloads, true\n}\n\n")

	body.WriteString("// Available reports whether every column carries live storage.\nfunc (payloads Payloads) Available() bool {\n\treturn ")
	writeConjunction(&body, owned, "payloads.%s.Available()")
	body.WriteString("\n}\n\n")

	ascending := make([]Payload, 0, len(owned))
	for _, payload := range owned {
		if payload.Ascends() {
			ascending = append(ascending, payload)
		}
	}
	if len(ascending) == 0 {
		return render(body.Bytes())
	}

	body.WriteString("// Lattices are this axis's ascent witnesses. Each names the owner's own\n// API, so this layer never guesses a method name and never carries a\n// function value.\ntype Lattices struct {\n")
	for _, payload := range ascending {
		fmt.Fprintf(&body, "\t%s %s\n", payload.Field, payload.Lattice)
	}
	body.WriteString("}\n\n")

	fmt.Fprintf(&body, "// Algebras states one ascent authority per TypeID that declares an order.\n// The state layer resolves a proposal's order by TypeID alone, never by the\n// operation that produced it.\nfunc (payloads Payloads) Algebras(issuer binding.Issuer, lattices Lattices) ([]binding.ValueAlgebra, bool) {\n\tif !payloads.Available() || !issuer.Available() {\n\t\treturn nil, false\n\t}\n\talgebras := make([]binding.ValueAlgebra, 0, %d)\n", len(ascending))
	for _, payload := range ascending {
		name := lower(payload.Field) + "Algebra"
		fmt.Fprintf(&body, "\t%s, ok := relbindgen.NewAlgebra[%s, %s](payloads.%s, issuer, lattices.%s)\n\tif !ok {\n\t\treturn nil, false\n\t}\n\talgebras = append(algebras, %s)\n", name, payload.Type, payload.Lattice, payload.Field, payload.Field, name)
	}
	body.WriteString("\treturn algebras, true\n}\n")

	return render(body.Bytes())
}

func writeConjunction(body *bytes.Buffer, payloads []Payload, format string) {
	for index, payload := range payloads {
		if index != 0 {
			body.WriteString(" && ")
		}
		fmt.Fprintf(body, format, payload.Field)
	}
}

// familyPayloads collects the distinct owner columns one family names, in
// declaration order so the emission is stable.
func familyPayloads(corpus Corpus, family Family) ([]Payload, error) {
	named := map[string]bool{}
	for _, slot := range family.Inputs {
		named[slot.Payload] = true
	}
	for _, column := range family.Outputs {
		named[column.Payload] = true
	}
	if family.Publishes() {
		named[family.Result] = true
	}
	used := make([]Payload, 0, len(named))
	for _, payload := range corpus.Payloads {
		if named[payload.Key] {
			used = append(used, payload)
		}
	}
	if len(used) != len(named) {
		return nil, fmt.Errorf("family %s names a payload the corpus does not declare", family.Stem)
	}
	return used, nil
}

func writeImports(body *bytes.Buffer, lines []string) {
	body.WriteString("import (\n")
	for _, line := range lines {
		fmt.Fprintf(body, "\t%s\n", line)
	}
	body.WriteString(")\n\n")
}

func render(body []byte) ([]byte, error) {
	source := append([]byte(header), body...)
	formatted, err := format.Source(source)
	if err != nil {
		return nil, fmt.Errorf("emitted source does not parse: %w", err)
	}
	return formatted, nil
}
