// Code generated by axis member definition generator; DO NOT EDIT.
// This file is the immutable bind-time relation owner for the axis.

package call

import (
	"github.com/wippyai/go-lua/analysis/engine/execution"
	"github.com/wippyai/go-lua/analysis/identity"
	memberrelation "github.com/wippyai/go-lua/analysis/schema/axis/member/relation"
)

// DenseCoordinate is call's dense Factor coordinate: the position a key of this
// axis occupies in the Factor its owner binds. It is published here rather
// than hand-exported by an owner, so one axis has exactly one coordinate
// type and a family of another axis names this one instead of erasing it to
// a builtin width. It carries no capability: it is an index, and every value
// of it an owner hands out is one that owner minted.
type DenseCoordinate uint32

// ForeignRead seals one exact read of a bound call Factor at this axis's own
// coordinate and fact types. It is the read handle a rule family of another
// axis holds: that family may not name this pair, and this handle is why it
// never has to erase one to reach the read. The coordinate is the one the
// reading rule's own selection derived, and a handle bound at any other
// pair of types is refused rather than reinterpreted.
func ForeignRead(foreign execution.ForeignFactor, coordinate execution.SelectedCoordinate, input uint16) (execution.ExactRead[DenseCoordinate, Value], bool) {
	return execution.ForeignExactRead[DenseCoordinate, Value](foreign, coordinate.Unit, input)
}

// RelationOwner is the generated bind-time owner for call's member relations.
type RelationOwner struct {
	schema *Algebra
}

var _ memberrelation.Owner = (*RelationOwner)(nil)

// NewRelationOwner binds the generated relation owner to one immutable axis schema.
func NewRelationOwner(schema *Algebra) *RelationOwner {
	if schema == nil {
		return nil
	}
	owner := &RelationOwner{schema: schema}
	return owner
}

// candidate resolves one occurrence to the owner-issued dense candidate ordinal.
// A mounted relation requires the mount that qualifies the occurrence; a global
// relation owns the occurrence directory itself and refuses one.
func (owner *RelationOwner) candidate(relationOrdinal uint32, mount, occurrence identity.ContentID) (uint32, bool) {
	if owner == nil || owner.schema == nil || !occurrence.Available() {
		return 0, false
	}
	switch relationOrdinal {
	case 0:
		if !mount.Available() {
			return 0, false
		}
		candidate, candidateOK := owner.schema.CallCoordinateForOccurrence(mount, occurrence)
		if !candidateOK {
			return 0, false
		}
		return owner.schema.CallCoordinateOrdinal(candidate)
	default:
		return 0, false
	}
}

// CandidateCount is the census of the candidate set one occurrence carries.
// Every relation this axis declares is keyed: one occurrence names one row, so
// the census is one wherever the keyed resolution succeeds and no row at all
// where it does not.
func (owner *RelationOwner) CandidateCount(relationOrdinal uint32, mount, occurrence identity.ContentID) (int, bool) {
	if _, ok := owner.candidate(relationOrdinal, mount, occurrence); !ok {
		return 0, false
	}
	return 1, true
}

// CandidateAt indexes that set. A keyed relation admits index zero only.
func (owner *RelationOwner) CandidateAt(relationOrdinal uint32, mount, occurrence identity.ContentID, index int) (uint32, bool) {
	if index != 0 {
		return 0, false
	}
	return owner.candidate(relationOrdinal, mount, occurrence)
}

// MemberCount is the census of one nested ordered member set under one parent
// candidate. This axis declares no nested set, so it holds no members.
func (owner *RelationOwner) MemberCount(relationOrdinal, parentCandidateOrdinal uint32) (int, bool) {
	return 0, false
}

// MemberAt addresses one row of a nested ordered member set by its ordinal.
func (owner *RelationOwner) MemberAt(relationOrdinal, parentCandidateOrdinal uint32, ordinal int) (uint32, bool) {
	return 0, false
}

// Project projects one dense candidate through one relation/projection pair to a local coordinate ordinal.
func (owner *RelationOwner) Project(relationOrdinal, projectionOrdinal, candidateOrdinal uint32) (uint32, bool) {
	if owner == nil || owner.schema == nil {
		return 0, false
	}
	switch relationOrdinal {
	case 0:
		switch projectionOrdinal {
		case 0:
			candidate, candidateOK := owner.schema.CallCoordinateAt(int(candidateOrdinal))
			if !candidateOK {
				return 0, false
			}
			first, projectionOK := candidate.Key()
			if !projectionOK {
				return 0, false
			}
			projected := first
			return owner.schema.DenseKeyIndex(projected)
		default:
			return 0, false
		}
	default:
		return 0, false
	}
}
