// Code generated by axis member definition generator; DO NOT EDIT.

package call

//go:generate go run ../../analysis/schema/axis/member/generator/cmd -source call -cold rule_members.go -relations generated_relation_owner.go

import (
	schemaapi "github.com/wippyai/go-lua/analysis/schema"
	"github.com/wippyai/go-lua/analysis/schema/axis/member"
)

const (
	MountedCallCandidates    schemaapi.Key  = "call/mounted-call/candidates"
	MountedCallFacts         schemaapi.Key  = "call/mounted-call/facts"
	MountedEffectCallSites   schemaapi.Key  = "call/mounted-call/effect-sites"
	MountedCallCoordinate    schemaapi.Key  = "call/mounted-call/coordinate"
	MountedCallFactKey       schemaapi.Key  = "call/mounted-call/fact-key"
	MountedEffectCallSiteKey schemaapi.Key  = "call/mounted-call/effect-site-key"
	DispatchReducer          schemaapi.Key  = "call/dispatch/reducer"
	CallKeyCarrier           member.Carrier = "carrier/call/key"
	CallFactCarrier          member.Carrier = "carrier/call/fact"
	CallCoordinateCarrier    member.Carrier = "carrier/call/mounted-call"
	ValueFactCarrier         member.Carrier = "carrier/value/fact"
	EffectMountedCallCarrier member.Carrier = "carrier/effect/mounted-call"
)

// AxisMemberCatalog is call's declaration-only member vocabulary.
func AxisMemberCatalog() member.Catalog {
	valueAxis := schemaapi.EntryReference{Surface: schemaapi.SurfaceKindAxis, Key: "call"}
	catalog, ok := member.NewCatalog(
		[]member.Relation{
			{Key: MountedCallCandidates, Subject: CallCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/candidates"})},
			{Key: MountedCallFacts, Subject: CallFactCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/candidates"}), Inputs: []member.Carrier{CallCoordinateCarrier}},
			{Key: MountedEffectCallSites, Subject: CallCoordinateCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/effect-sites"}), Inputs: []member.Carrier{EffectMountedCallCarrier}, Correspondences: []member.RelationRef{member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "effect"}, Member: "effect/mounted-call/candidates"}}},
		},
		[]member.Projection{
			{Key: MountedCallCoordinate, Relation: MountedCallCandidates, Role: member.Destination, Result: CallKeyCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/candidates"})},
			{Key: MountedCallFactKey, Relation: MountedCallFacts, Role: member.Key, Result: CallKeyCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/candidates"})},
			{Key: MountedEffectCallSiteKey, Relation: MountedEffectCallSites, Role: member.Key, Result: CallKeyCarrier, CandidateProvider: member.AxisRelationCandidate(member.RelationRef{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKind(2), Key: "call"}, Member: "call/mounted-call/effect-sites"})},
		},
		[]member.Reducer{
			{Key: DispatchReducer, Inputs: []member.ReducerInput{
				{Axis: schemaapi.EntryReference{Surface: schemaapi.SurfaceKindAxis, Key: "value"}, Carrier: ValueFactCarrier, Form: member.ReadFormExact, Multiplicity: member.MultiplicityOne},
			}, Outputs: []member.ReducerOutput{
				{Axis: valueAxis, Carrier: CallFactCarrier},
			}},
		},
		[]member.CarryTransform{},
	)
	if !ok {
		panic("call: invalid axis member catalog")
	}
	return catalog
}
