// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.

package relation

import (
	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
	"github.com/wippyai/go-lua/analysis/relation/semantic/signature"
	"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"
	heapdomain "github.com/wippyai/go-lua/domain/heap"
	placementdomain "github.com/wippyai/go-lua/domain/placement"
)

// PlacementContainmentColumns are the owner column codecs of the
// placement/containment binding.
type PlacementContainmentColumns struct {
	Heap              *relbindgen.Column[heapdomain.Value]
	Placement         *relbindgen.Column[placementdomain.Fact]
	HeapCandidate     *relbindgen.Column[heapdomain.Key]
	PlacementRouteTag *relbindgen.Column[uint64]
}

// NewPlacementContainmentColumns names this family's own owner columns. A column an axis
// other than this one publishes is handed in, never reached for.
func NewPlacementContainmentColumns(heap *relbindgen.Column[heapdomain.Value], placement *relbindgen.Column[placementdomain.Fact], heapCandidate *relbindgen.Column[heapdomain.Key], placementRouteTag *relbindgen.Column[uint64]) (PlacementContainmentColumns, bool) {
	columns := PlacementContainmentColumns{Heap: heap, Placement: placement, HeapCandidate: heapCandidate, PlacementRouteTag: placementRouteTag}
	if !columns.Available() {
		return PlacementContainmentColumns{}, false
	}
	return columns, true
}

// Available reports whether every column this binding needs carries an
// owner-issued type and live storage.
func (columns PlacementContainmentColumns) Available() bool {
	return columns.Heap.Available() && columns.Placement.Available() && columns.HeapCandidate.Available() && columns.PlacementRouteTag.Available()
}

// PlacementContainmentArgument is the decoded frame of one
// placement/containment invocation.
type PlacementContainmentArgument struct {
	Placements relbindgen.Span[placementdomain.Fact]
	Heaps      relbindgen.Span[heapdomain.Value]
	Route      heapdomain.Key
	Tag        uint64
	Current    placementdomain.Fact
}

// PlacementContainmentJudgment is the owner mathematics this binding carries. The axis
// states it by hand: nothing in this file can name a relation, a cell, a
// buffer or an engine value, so the mathematics stays where its owner wrote
// it and this artifact stays free of it.
type PlacementContainmentJudgment interface {
	relbindgen.Operation[PlacementContainmentArgument, placementdomain.Fact]
	Available() bool
}

// The hand-authored judgment answers this family's own contract, and the
// assertion is what makes the two halves one binding.
var _ PlacementContainmentJudgment = PlacementContainmentOperation{}

// BindPlacementContainment admits the placement/containment family
// under its sealed signature.
func BindPlacementContainment(operation signature.Signature, judgment PlacementContainmentJudgment, columns PlacementContainmentColumns, refusal model.RefusalID) (binding.Factory, bool) {
	if judgment == nil || !judgment.Available() || !columns.Available() {
		return nil, false
	}
	return relbindgen.Bind(relbindgen.Spec[PlacementContainmentArgument, placementdomain.Fact]{
		Signature: operation,
		Decoder:   placementContainmentDecoder{columns: columns},
		Encoder:   placementContainmentEncoder{columns: columns},
		Operation: judgment,
		Address:   4,
		Refusal:   refusal,
	})
}

type placementContainmentDecoder struct {
	columns PlacementContainmentColumns
}

func (decoder placementContainmentDecoder) Decode(inputs relbindgen.Inputs) (PlacementContainmentArgument, bool) {
	placements, ok := relbindgen.SpanAt(inputs, 0, decoder.columns.Placement)
	if !ok {
		return PlacementContainmentArgument{}, false
	}
	heaps, ok := relbindgen.SpanAt(inputs, 1, decoder.columns.Heap)
	if !ok {
		return PlacementContainmentArgument{}, false
	}
	route, ok := relbindgen.ScalarAt(inputs, 2, decoder.columns.HeapCandidate)
	if !ok {
		return PlacementContainmentArgument{}, false
	}
	tag, ok := relbindgen.ScalarAt(inputs, 3, decoder.columns.PlacementRouteTag)
	if !ok {
		return PlacementContainmentArgument{}, false
	}
	current, ok := relbindgen.ScalarAt(inputs, 4, decoder.columns.Placement)
	if !ok {
		return PlacementContainmentArgument{}, false
	}
	return PlacementContainmentArgument{Placements: placements, Heaps: heaps, Route: route, Tag: tag, Current: current}, true
}

type placementContainmentEncoder struct {
	columns PlacementContainmentColumns
}

func (encoder placementContainmentEncoder) Encode(outputs relbindgen.Outputs, value placementdomain.Fact) bool {
	return relbindgen.PutColumn(outputs, 0, encoder.columns.Placement, value)
}
