package emitlaw

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// importSet collects the imports the emitted suite spells, so a vocabulary a
// declaration does not reach is never imported.
type importSet struct {
	paths map[string]string
	local string
}

func newImportSet(local string) *importSet {
	return &importSet{paths: map[string]string{}, local: local}
}

// use registers one import under an alias and answers the qualifier the
// emitted source spells its symbols with. A symbol already in the emitted
// package is spelled unqualified.
func (set *importSet) use(path, alias string) string {
	if path == set.local {
		return ""
	}
	set.paths[path] = alias
	return alias + "."
}

func (set *importSet) render(out *strings.Builder) {
	out.WriteString("import (\n\t\"testing\"\n")
	if len(set.paths) == 0 {
		out.WriteString(")\n\n")
		return
	}
	paths := make([]string, 0, len(set.paths))
	for path := range set.paths {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	out.WriteString("\n")
	for _, path := range paths {
		fmt.Fprintf(out, "\t%s %q\n", set.paths[path], path)
	}
	out.WriteString(")\n\n")
}

func render(built *suite) ([]byte, error) {
	var out strings.Builder
	imports := newImportSet(built.target.PackagePath)
	var body strings.Builder

	renderGeometry(&body, built, imports)
	renderCallShape(&body, built, imports)
	renderFreshDeclaration(&body, built, imports)
	renderRuleEntry(&body, built, imports)
	if err := renderMutations(&body, built, imports); err != nil {
		return nil, err
	}
	renderAdmissions(&body, built, imports)

	out.WriteString("// Code generated by analysis/schema/rule/emitlaw; DO NOT EDIT.\n")
	out.WriteString("//\n")
	out.WriteString("// These are the laws every rule declaration owes by construction. They are\n")
	out.WriteString("// derived from the declaration itself, so a family authors beside them only\n")
	out.WriteString("// the laws that state what its fold means.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", built.target.PackageName)
	imports.render(&out)
	out.WriteString(body.String())
	return []byte(out.String()), nil
}

func renderGeometry(out *strings.Builder, built *suite, imports *importSet) {
	law := imports.use(emitlawPackagePath, emitlawPackage)
	constant := lowerFirst(built.symbol) + "Geometry"

	out.WriteString("// " + constant + " is the whole geometry the declaration carries, in the one\n")
	out.WriteString("// canonical form every emitted law suite states a declaration in. It is total\n")
	out.WriteString("// over the cold ABI: every join clause, contract term, fold argument, output\n")
	out.WriteString("// clause, carry, and transport row appears on exactly one line.\n")
	fmt.Fprintf(out, "const %s = %s\n\n", constant, backquote(built.geometry))

	fmt.Fprintf(out, "// Test%sGeometryIsTheOneItsLawSuiteWasEmittedFrom holds the declaration to the\n", built.symbol)
	out.WriteString("// geometry above. The rendering is checked in beside the declaration and the\n")
	out.WriteString("// freshness law re-derives it, so a declaration that moves without\n")
	out.WriteString("// regeneration fails the build and one that moves with it is a reviewable\n")
	out.WriteString("// diff of exactly what changed.\n")
	fmt.Fprintf(out, "func Test%sGeometryIsTheOneItsLawSuiteWasEmittedFrom(t *testing.T) {\n", built.symbol)
	fmt.Fprintf(out, "\tif got := %sCanonical(%s()); got != %s {\n", law, built.target.Declaration, constant)
	fmt.Fprintf(out, "\t\tt.Fatalf(\"declared geometry has moved away from its law suite:\\ngot:\\n%%s\\nwant:\\n%%s\", got, %s)\n", constant)
	out.WriteString("\t}\n}\n\n")
}

func renderCallShape(out *strings.Builder, built *suite, imports *importSet) {
	catalog := imports.use(built.reducerAxisPackage, catalogPackage)
	key := imports.use(schemaPackagePath, "schemaapi")

	fmt.Fprintf(out, "// Test%sAgreesWithTheCallShapeOfTheReducerItNames is the one structural law a\n", built.symbol)
	out.WriteString("// Program cannot settle alone. Check sees only the declaration, so a fold that\n")
	out.WriteString("// hands its reducer a join the owner does not take is well formed in isolation\n")
	out.WriteString("// and wrong against the row it names. The reducer's call shape is the owner\n")
	out.WriteString("// axis's statement, and this law is where the two are held together.\n")
	fmt.Fprintf(out, "func Test%sAgreesWithTheCallShapeOfTheReducerItNames(t *testing.T) {\n", built.symbol)
	fmt.Fprintf(out, "\tdeclaration := %s()\n", built.target.Declaration)
	out.WriteString("\tif problem, valid := declaration.Check(); !valid {\n")
	out.WriteString("\t\tt.Fatalf(\"declaration is malformed: %+v\", problem)\n\t}\n")
	fmt.Fprintf(out, "\treducer, reducerOK := %s%s().Reducer(%sKey(%q))\n",
		catalog, axisCatalogAccessor, key, string(built.reducerKey))
	fmt.Fprintf(out, "\tif !reducerOK {\n\t\tt.Fatal(\"the reducer axis publishes no reducer named %s\")\n\t}\n", string(built.reducerKey))
	out.WriteString("\tif problem, valid := declaration.CheckAgainst(reducer); !valid {\n")
	out.WriteString("\t\tt.Fatalf(\"declaration disagrees with its reducer's call shape: %+v\", problem)\n\t}\n}\n\n")
}

func renderFreshDeclaration(out *strings.Builder, built *suite, imports *importSet) {
	law := imports.use(emitlawPackagePath, emitlawPackage)
	constant := lowerFirst(built.symbol) + "Geometry"

	fmt.Fprintf(out, "// Test%sIsHandedOutFresh states that the accessor yields a declaration a caller\n", built.symbol)
	out.WriteString("// owns. Every law that probes a malformed edit mutates what it is handed, and a\n")
	out.WriteString("// declaration backed by shared storage would carry one law's edit into the next\n")
	out.WriteString("// reader - including the composition that seals it.\n")
	fmt.Fprintf(out, "func Test%sIsHandedOutFresh(t *testing.T) {\n", built.symbol)
	fmt.Fprintf(out, "\tfirst := %s()\n", built.target.Declaration)
	out.WriteString("\tfirst.OperandRole = \"law/mutation/operand\"\n")
	out.WriteString("\tfor index := range first.Joins {\n")
	out.WriteString("\t\tfirst.Joins[index].Relation.Member = \"law/mutation/relation\"\n")
	out.WriteString("\t\tfor source := range first.Joins[index].Sources {\n")
	out.WriteString("\t\t\tfirst.Joins[index].Sources[source] = " + qualified(imports, programPackagePath, programPackage) + "PriorSource(0)\n")
	out.WriteString("\t\t}\n\t}\n")
	out.WriteString("\tfor index := range first.Fold.Outputs {\n")
	out.WriteString("\t\tfirst.Fold.Outputs[index].Destination.Member = \"law/mutation/destination\"\n\t}\n")
	out.WriteString("\tfor index := range first.Fold.Inputs {\n")
	out.WriteString("\t\tfirst.Fold.Inputs[index] = " + qualified(imports, programPackagePath, programPackage) + "JoinRef(0)\n\t}\n")
	out.WriteString("\tif first.Carry != nil {\n")
	out.WriteString("\t\tfirst.Carry.Mode = " + qualified(imports, programPackagePath, programPackage) + "CarryModeInvalid\n\t}\n")
	out.WriteString("\tif first.Activation != nil {\n")
	out.WriteString("\t\tfor index := range first.Activation.Transport {\n")
	out.WriteString("\t\t\tfirst.Activation.Transport[index].Exported = !first.Activation.Transport[index].Exported\n\t\t}\n\t}\n")
	fmt.Fprintf(out, "\tif got := %sCanonical(%s()); got != %s {\n", law, built.target.Declaration, constant)
	out.WriteString("\t\tt.Fatalf(\"a caller's edits reached the next declaration:\\n%s\", got)\n")
	out.WriteString("\t}\n}\n\n")
}

func renderRuleEntry(out *strings.Builder, built *suite, imports *importSet) {
	law := imports.use(emitlawPackagePath, emitlawPackage)
	geometry := lowerFirst(built.symbol) + "Geometry"
	constant := lowerFirst(built.symbol) + "Identity"

	out.WriteString("// " + constant + " is the rule identity this declaration is sealed under.\n")
	fmt.Fprintf(out, "const %s = %s\n\n", constant, backquote(built.identity))

	fmt.Fprintf(out, "// Test%sRuleEntryIsTheSealedDeclaration holds the rule entry to its identity, to\n", built.symbol)
	out.WriteString("// the declaration this suite was emitted from, and to handing out issuance a\n")
	out.WriteString("// caller owns. An entry that shared its issuance storage would let one reader's\n")
	out.WriteString("// edit become every later reader's declaration.\n")
	fmt.Fprintf(out, "func Test%sRuleEntryIsTheSealedDeclaration(t *testing.T) {\n", built.symbol)
	fmt.Fprintf(out, "\tentry := %s()\n", built.target.Entry)
	fmt.Fprintf(out, "\tif got := %sCanonicalEntry(entry); got != %s {\n", law, constant)
	fmt.Fprintf(out, "\t\tt.Fatalf(\"rule identity has moved away from its law suite:\\ngot:\\n%%s\\nwant:\\n%%s\", got, %s)\n", constant)
	out.WriteString("\t}\n")
	fmt.Fprintf(out, "\tif got := %sCanonical(entry.Program); got != %s {\n", law, geometry)
	fmt.Fprintf(out, "\t\tt.Fatalf(\"the entry carries a different declaration than the one it is sealed over:\\n%%s\", got)\n")
	out.WriteString("\t}\n")
	out.WriteString("\tfor index := range entry.Issues {\n")
	out.WriteString("\t\tentry.Issues[index].Occurrence = \"law/mutation/occurrence\"\n")
	out.WriteString("\t\tentry.Issues[index].Form = \"law/mutation/form\"\n")
	out.WriteString("\t\tentry.Issues[index].Requirement = \"law/mutation/requirement\"\n\t}\n")
	out.WriteString("\tfor index := range entry.Roles {\n")
	out.WriteString("\t\tentry.Roles[index] = \"law/mutation/role\"\n\t}\n")
	fmt.Fprintf(out, "\tif got := %sCanonicalEntry(%s()); got != %s {\n", law, built.target.Entry, constant)
	out.WriteString("\t\tt.Fatalf(\"a caller's edits reached the next rule entry:\\n%s\", got)\n")
	out.WriteString("\t}\n}\n\n")
}

func renderMutations(out *strings.Builder, built *suite, imports *importSet) error {
	rows := built.refusals()
	if len(rows) == 0 {
		return unexpressible(built.target.Spec.Key, "a declaration Check refuses no edit of",
			"a structural law suite with no refusal states nothing about the checker that admits the declaration")
	}
	program := qualified(imports, programPackagePath, programPackage)
	for _, row := range rows {
		if strings.Contains(row.statement, memberPackage+".") {
			imports.use(memberPackagePath, memberPackage)
		}
	}

	fmt.Fprintf(out, "// Test%sRefusesEveryStructuralMutation is the negative half of the declaration's\n", built.symbol)
	out.WriteString("// structure: for every term the cold ABI carries, the edit that removes or\n")
	out.WriteString("// corrupts it, and the verdict Check gives it. The table is total over the\n")
	out.WriteString("// declaration rather than a sample of it, which is the whole reason it is\n")
	out.WriteString("// derived: an authored suite states the three edits its author thought of.\n")
	out.WriteString("//\n")
	out.WriteString("// Each verdict is the one this suite's emitter watched Check give while\n")
	out.WriteString("// deriving. Check runs for real here, so a checker that stops refusing an edit\n")
	out.WriteString("// fails this law, and a checker that refuses it differently shows up as a\n")
	out.WriteString("// regeneration diff.\n")
	fmt.Fprintf(out, "func Test%sRefusesEveryStructuralMutation(t *testing.T) {\n", built.symbol)
	out.WriteString("\tfor _, law := range []struct {\n")
	out.WriteString("\t\tmutation string\n")
	fmt.Fprintf(out, "\t\tapply    func(declaration *%sProgram)\n", program)
	fmt.Fprintf(out, "\t\tkind     %sProblemKind\n", program)
	out.WriteString("\t\tjoin     int\n")
	out.WriteString("\t\tinput    int\n")
	out.WriteString("\t\toutput   int\n")
	out.WriteString("\t}{\n")
	for _, row := range rows {
		kind := problemKindName(row.problem.Kind)
		if kind == "" {
			return unexpressible(built.target.Spec.Key, "an edit Check refuses without naming a problem",
				row.name)
		}
		fmt.Fprintf(out, "\t\t{mutation: %q, apply: func(declaration *%sProgram) { %s }, kind: %s%s",
			row.name, program, row.statement, program, kind)
		if row.problem.Join != 0 {
			fmt.Fprintf(out, ", join: %d", row.problem.Join)
		}
		if row.problem.Input != 0 {
			fmt.Fprintf(out, ", input: %d", row.problem.Input)
		}
		if row.problem.Output != 0 {
			fmt.Fprintf(out, ", output: %d", row.problem.Output)
		}
		out.WriteString("},\n")
	}
	out.WriteString("\t} {\n")
	fmt.Fprintf(out, "\t\tdeclaration := %s().Clone()\n", built.target.Declaration)
	out.WriteString("\t\tlaw.apply(&declaration)\n")
	out.WriteString("\t\tproblem, valid := declaration.Check()\n")
	out.WriteString("\t\tif valid {\n")
	out.WriteString("\t\t\tt.Fatalf(\"Check admits a declaration where %s\", law.mutation)\n\t\t}\n")
	out.WriteString("\t\tif problem.Kind != law.kind || problem.Join != law.join || problem.Input != law.input || problem.Output != law.output {\n")
	out.WriteString("\t\t\tt.Fatalf(\"where %s, Check refused with %+v\", law.mutation, problem)\n\t\t}\n")
	out.WriteString("\t}\n}\n\n")
	return nil
}

func renderAdmissions(out *strings.Builder, built *suite, imports *importSet) {
	rows := built.admissions()
	if len(rows) == 0 {
		return
	}
	program := qualified(imports, programPackagePath, programPackage)
	for _, row := range rows {
		if strings.Contains(row.statement, memberPackage+".") {
			imports.use(memberPackagePath, memberPackage)
		}
	}

	fmt.Fprintf(out, "// Test%sAdmitsTheseEditsAtDeclarationLevel states where Check's authority ends.\n", built.symbol)
	out.WriteString("// Check is data-local: it seals ordering, the normal forms, fold connectivity,\n")
	out.WriteString("// and output arity without reopening any owner schema. The edits below are\n")
	out.WriteString("// therefore well formed to it and are refused, if at all, by the seal that\n")
	out.WriteString("// resolves them against the complete catalog.\n")
	out.WriteString("//\n")
	out.WriteString("// This law exists so that boundary is on record rather than implied by absence.\n")
	out.WriteString("// An edit that starts being refused here is a checker that grew, and it shows\n")
	out.WriteString("// up as a regeneration diff instead of passing unnoticed.\n")
	fmt.Fprintf(out, "func Test%sAdmitsTheseEditsAtDeclarationLevel(t *testing.T) {\n", built.symbol)
	out.WriteString("\tfor _, law := range []struct {\n")
	out.WriteString("\t\tmutation string\n")
	fmt.Fprintf(out, "\t\tapply    func(declaration *%sProgram)\n", program)
	out.WriteString("\t}{\n")
	for _, row := range rows {
		fmt.Fprintf(out, "\t\t{mutation: %q, apply: func(declaration *%sProgram) { %s }},\n",
			row.name, program, row.statement)
	}
	out.WriteString("\t} {\n")
	fmt.Fprintf(out, "\t\tdeclaration := %s().Clone()\n", built.target.Declaration)
	out.WriteString("\t\tlaw.apply(&declaration)\n")
	out.WriteString("\t\tif problem, valid := declaration.Check(); !valid {\n")
	out.WriteString("\t\t\tt.Fatalf(\"Check has grown to refuse a declaration where %s: %+v\", law.mutation, problem)\n\t\t}\n")
	out.WriteString("\t}\n}\n\n")
}

// qualified registers an import and answers its qualifier prefix.
func qualified(imports *importSet, path, alias string) string {
	return imports.use(path, alias)
}

// backquote renders one canonical form as a raw Go string literal. A canonical
// rendering carries no backquote, so the raw form is always available; the
// guard states that rather than assuming it.
func backquote(value string) string {
	if !strings.Contains(value, "`") {
		return "`" + value + "`"
	}
	return strconv.Quote(value)
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}
