package contribution

import (
	"bytes"

	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/schema/semantic/output"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
)

// Key is one exact producer contribution address. The schema-issued output
// port is the sole source of operation and output-column identity; state does
// not expose or reconstruct an output ordinal.
type Key struct {
	Invocation  Handle
	Port        output.OutputPort
	Destination model.RowID
}

// Target is one exact output destination.  A target is deliberately separate
// from Key: several invocation producers may contribute to the same output
// port and row, while each producer remains a distinct State row.  Reduction
// therefore groups by (port,row), never by RowID alone.
type Target struct {
	Port        output.OutputPort
	Destination model.RowID
}

// NewTarget adopts one schema-issued output port and owner-issued row.
// Nothing in a target is generated by the contribution store.
func NewTarget(port output.OutputPort, destination model.RowID) (Target, bool) {
	value := Target{Port: port, Destination: destination}
	if !value.Available() {
		return Target{}, false
	}
	return value, true
}

// Available reports whether the target's port and row name the same relation.
func (target Target) Available() bool {
	return target.Port.Available() && target.Destination.Available() && target.Port.Column.Relation() == target.Destination.Relation()
}

// Same compares exact target identity.  Scope and producer provenance are not
// part of target identity; they remain on Row as the authenticated geometry.
func (target Target) Same(other Target) bool {
	return target.Available() && other.Available() && target.Port == other.Port && target.Destination == other.Destination
}

// Available reports whether all nominal components are present and the
// destination belongs to the relation named by the schema port column.
func (key Key) Available() bool {
	return key.Invocation.Available() && key.Port.Available() && key.Destination.Available() && key.Port.Column.Relation() == key.Destination.Relation()
}

// ValidFor redeems the invocation handle against one exact runtime fence.
func (key Key) ValidFor(fence binding.Fence) bool {
	return key.Available() && key.Invocation.ValidFor(fence)
}

// NewKey adopts one already-issued invocation handle, sealed output port, and
// destination. No identity is generated or derived by this constructor.
func NewKey(handle Handle, port output.OutputPort, destination model.RowID) (Key, bool) {
	value := Key{Invocation: handle, Port: port, Destination: destination}
	if !value.Available() {
		return Key{}, false
	}
	return value, true
}

// Row is one immutable contribution payload at an exact producer key. Value
// remains a fenced owner-issued token. Presence preserves ProvenAbsent and
// other canonical semantic statuses, while Lineage retains the proof needed
// by a later aggregate recomputation. No aggregate cell is stored here.
type Row struct {
	Key         Key
	Destination binding.CellToken
	Value       binding.ValueToken
	Presence    model.Presence
	Lineage     model.LineageRef
}

// Available reports whether the row carries a complete key and canonical
// value/presence/lineage payload. Fence redemption is performed by ValidFor.
func (row Row) Available() bool {
	return row.Key.Available() && row.Destination.Available() && row.Destination.Column() == row.Key.Port.Column && row.Destination.Row() == row.Key.Destination && payloadAvailable(row.Value, row.Presence, row.Lineage)
}

// ValidFor redeems the key and any present/opaque value against one state
// fence. Non-value statuses must retain the canonical zero value token.
func (row Row) ValidFor(fence binding.Fence) bool {
	if !row.Available() || !row.Key.ValidFor(fence) || !row.Destination.ValidFor(fence) || !row.Lineage.Available() {
		return false
	}
	if row.Presence.Is(model.Present) || row.Presence.Is(model.AuthenticatedOpaque) {
		return row.Value.ValidFor(fence)
	}
	return !row.Value.Available()
}

// NewRow adopts one exact key and complete semantic payload. It does not
// derive invocation, value, presence, or lineage identities.
func NewRow(key Key, destination binding.CellToken, value binding.ValueToken, presence model.Presence, lineage model.LineageRef) (Row, bool) {
	result := Row{Key: key, Destination: destination, Value: value, Presence: presence, Lineage: lineage}
	if !result.Available() {
		return Row{}, false
	}
	return result, true
}

// Target returns the exact output port and row owned by this contribution.
func (row Row) Target() Target {
	if !row.Available() {
		return Target{}
	}
	return Target{Port: row.Key.Port, Destination: row.Key.Destination}
}

// Cell returns the retained owner-issued destination geometry.  In
// particular, it preserves scope and denominator witness for later
// retraction; callers must not reconstruct a CellToken from RowID.
func (row Row) Cell() binding.CellToken {
	if !row.Available() {
		return binding.CellToken{}
	}
	return row.Destination
}

func payloadAvailable(value binding.ValueToken, presence model.Presence, lineage model.LineageRef) bool {
	if !presence.Available() || presence.Is(model.Refused) || !lineage.Available() {
		return false
	}
	if presence.Is(model.Present) || presence.Is(model.AuthenticatedOpaque) {
		return value.Available()
	}
	return !value.Available()
}

func sameKey(left, right Key) bool {
	return left.Port == right.Port && left.Destination == right.Destination && left.Invocation.Same(right.Invocation)
}

func samePayload(left, right Row) bool {
	if left.Presence != right.Presence || left.Lineage != right.Lineage {
		return false
	}
	if left.Value.Available() || right.Value.Available() {
		return left.Value.Same(right.Value)
	}
	return true
}

func compareKey(left, right Key) int {
	if result := compareRowID(left.Destination, right.Destination); result != 0 {
		return result
	}
	if result := comparePort(left.Port, right.Port); result != 0 {
		return result
	}
	if result, ok := CompareHandles(left.Invocation, right.Invocation); ok {
		return result
	}
	return 0
}

func compareTarget(left, right Target) int {
	if result := compareRowID(left.Destination, right.Destination); result != 0 {
		return result
	}
	return comparePort(left.Port, right.Port)
}

func comparePort(left, right output.OutputPort) int {
	leftOperation, rightOperation := left.Operation.Operation, right.Operation.Operation
	if result := compareOperationID(leftOperation, rightOperation); result != 0 {
		return result
	}
	if left.Operation.Version < right.Operation.Version {
		return -1
	}
	if left.Operation.Version > right.Operation.Version {
		return 1
	}
	return compareColumnID(left.Column, right.Column)
}

func compareRowID(left, right model.RowID) int {
	leftRelation, rightRelation := left.Relation(), right.Relation()
	if result := compareOwner(leftRelation.Owner(), rightRelation.Owner()); result != 0 {
		return result
	}
	leftRelationContent, rightRelationContent := leftRelation.Content(), rightRelation.Content()
	if result := bytes.Compare(leftRelationContent[:], rightRelationContent[:]); result != 0 {
		return result
	}
	leftContent, rightContent := left.Content(), right.Content()
	return bytes.Compare(leftContent[:], rightContent[:])
}

func compareColumnID(left, right model.ColumnID) int {
	if result := compareRowIDForColumns(left.Relation(), right.Relation()); result != 0 {
		return result
	}
	leftContent, rightContent := left.Content(), right.Content()
	return bytes.Compare(leftContent[:], rightContent[:])
}

func compareRowIDForColumns(left, right model.RelationID) int {
	if result := compareOwner(left.Owner(), right.Owner()); result != 0 {
		return result
	}
	leftContent, rightContent := left.Content(), right.Content()
	return bytes.Compare(leftContent[:], rightContent[:])
}

func compareOperationID(left, right model.OperationID) int {
	if result := compareOwner(left.Owner(), right.Owner()); result != 0 {
		return result
	}
	leftContent, rightContent := left.Content(), right.Content()
	return bytes.Compare(leftContent[:], rightContent[:])
}

func compareOwner(left, right model.OwnerID) int {
	leftContent, rightContent := left.Content(), right.Content()
	return bytes.Compare(leftContent[:], rightContent[:])
}
