package pathevidence

import (
	"sort"

	"github.com/wippyai/go-lua/__legacy/analysis/internal/mapedit"
	pathdom "github.com/wippyai/go-lua/analysis/domain/path"
	"github.com/wippyai/go-lua/analysis/domain/path/keyspace"
	"github.com/wippyai/go-lua/analysis/domain/path/segment"
	"github.com/wippyai/go-lua/analysis/domain/value/axis/presence"
)

type BranchProofKind uint8

const (
	BranchProofPathPresence BranchProofKind = iota + 1
	BranchProofPathEqual
	BranchProofPathNotEqual
	BranchProofIndexInRange
)

type BranchProof struct {
	Kind     BranchProofKind
	Path     keyspace.Key
	Presence presence.Value
	Other    keyspace.Key
}

// AddBranchProof records a must fact that survived onto this control-flow edge.
func (l Lane) AddBranchProof(proof BranchProof) (Lane, bool) {
	return l.AddBranchProofs([]BranchProof{proof})
}

// AddBranchProofs records each valid must proof with a single copy-on-write
// update. It is equivalent to repeated AddBranchProof calls.
func (l Lane) AddBranchProofs(additions []BranchProof) (Lane, bool) {
	if len(additions) == 0 {
		return l, false
	}
	var proofs map[BranchProof]struct{}
	changed := false
	for _, proof := range additions {
		if proof.Kind == 0 {
			continue
		}
		if !l.proofsBottom {
			if _, ok := l.proofs[proof]; ok {
				continue
			}
		}
		if proofs == nil {
			proofs = cloneBranchProofSet(l.proofs)
			if proofs == nil {
				proofs = make(map[BranchProof]struct{}, len(additions))
			}
		}
		if _, ok := proofs[proof]; ok {
			continue
		}
		proofs[proof] = struct{}{}
		changed = true
	}
	if !changed {
		return l, false
	}
	out := l.Reachable()
	out.proofs = proofs
	for _, proof := range additions {
		out.equalityRootMask.merge(equalityProofRootMask(proof))
	}
	return out, true
}

func (l Lane) HasBranchProof(proof BranchProof) bool {
	if l.proofsBottom {
		return false
	}
	_, ok := l.proofs[proof]
	return ok
}

// CloseProofsAcrossTransientEquality derives every proof implied by a
// point-local value equality without retaining that equality as an aliasing
// equation. Lua __eq can prove equal values without proving heap/path
// identity, so making the synthetic edge persistent would be unsound.
func (l Lane) CloseProofsAcrossTransientEquality(keys *keyspace.KeySpace, left, right keyspace.Key) (Lane, bool) {
	if keys == nil || !keys.Valid() || left == right || left.Kind == keyspace.KindInvalid || right.Kind == keyspace.KindInvalid {
		return l, false
	}
	proofs := make([]BranchProof, 0, len(l.proofs)+1)
	for proof := range l.proofs {
		proofs = append(proofs, proof)
	}
	synthetic := BranchProof{Kind: BranchProofPathEqual, Path: left, Other: right}
	proofs = append(proofs, synthetic)
	closed := CloseBranchProofsAcrossKnownEqualities(keys, proofs)
	out := l
	changed := false
	for _, proof := range closed {
		if proof == synthetic {
			continue
		}
		var added bool
		out, added = out.AddBranchProof(proof)
		changed = changed || added
	}
	return out, changed
}

// CloseProofsAcrossKnownEqualities computes and publishes the least finite
// proof closure induced by the lane's retained equality equations.
func (l Lane) CloseProofsAcrossKnownEqualities(keys *keyspace.KeySpace) (Lane, bool) {
	if keys == nil || !keys.Valid() || l.proofsBottom || len(l.proofs) == 0 {
		return l, false
	}
	proofs := make([]BranchProof, 0, len(l.proofs))
	for proof := range l.proofs {
		proofs = append(proofs, proof)
	}
	return l.AddBranchProofs(CloseBranchProofsAcrossKnownEqualities(keys, proofs))
}

func (l Lane) HasBranchProofKind(kind BranchProofKind) bool {
	if l.proofsBottom || kind == 0 {
		return false
	}
	for proof := range l.proofs {
		if proof.Kind == kind {
			return true
		}
	}
	return false
}

// BranchProofPresence returns the unique path-presence proof for key. It
// reports false when no proof exists or when conflicting presence proofs make
// the result unusable.
func (l Lane) BranchProofPresence(key keyspace.Key) (presence.Value, bool) {
	if l.proofsBottom || key.Kind == keyspace.KindInvalid {
		return presence.Bottom(), false
	}
	var value presence.Value
	found := false
	for proof := range l.proofs {
		if proof.Kind != BranchProofPathPresence || proof.Path != key {
			continue
		}
		if found && !presence.Equal(value, proof.Presence) {
			return presence.Bottom(), false
		}
		value = proof.Presence
		found = true
	}
	return value, found
}

func (l Lane) EquivalentPathKeys(ks *keyspace.KeySpace, pathKey pathdom.PathKey) []pathdom.PathKey {
	if pathKey == "" || l.proofsBottom || len(l.proofs) == 0 {
		return nil
	}
	start, ok := ks.FromStateKey(pathKey)
	if !ok {
		return nil
	}
	keys := l.EquivalentKeyspaceKeys(ks, start)
	if len(keys) == 0 {
		return nil
	}
	out := make([]pathdom.PathKey, len(keys))
	for i, key := range keys {
		out[i] = ks.Format(key)
	}
	return out
}

// EquivalentKeyspaceKeys returns the finite, already-tracked keys proven equal
// to start. Equality is the exact ground congruence generated by path-equality
// proofs: a segment is a unary constructor, so equal parents with the same
// segment have equal children. The result is in stable keyspace order and
// excludes start itself.
//
// The equality theory may have an infinite class (for example a=b.x, b=a.x),
// but a []Key result cannot represent one. Enumeration therefore ranges over
// the finite terms already carried by this lane plus start. Callers testing a
// particular key must use HasEquivalentKeyspaceKey, which adds that key and its
// subterms to the finite ground problem and is complete for the query.
func (l Lane) EquivalentKeyspaceKeys(ks *keyspace.KeySpace, start keyspace.Key) []keyspace.Key {
	if ks == nil || start.Kind == keyspace.KindInvalid || l.proofsBottom || len(l.proofs) == 0 {
		return nil
	}
	if !l.equalityRootMask.empty() && !l.equalityRootMask.matches(start) {
		return nil
	}
	closure := newPathCongruence(ks, l)
	startNormal, ok := closure.normal(start)
	if !ok {
		return nil
	}
	var out []keyspace.Key
	var seen map[keyspace.Key]struct{}
	l.forEachCongruenceObservation(func(key keyspace.Key) {
		if key == start {
			return
		}
		normal, valid := closure.normal(key)
		if !valid || !pathCongruenceNormalsEqual(startNormal, normal) {
			return
		}
		if seen == nil {
			seen = make(map[keyspace.Key]struct{})
		}
		if _, duplicate := seen[key]; duplicate {
			return
		}
		seen[key] = struct{}{}
		out = append(out, key)
	})
	if len(out) == 0 {
		return nil
	}
	sort.Slice(out, func(i, j int) bool { return ks.Less(out[i], out[j]) })
	return out
}

// forEachCongruenceObservation visits exactly the finite terms that the old
// explicit ground-term DAG exposed for enumeration. Only PathEqual facts are
// equations; every other key is an observation whose normal form may be
// compared without inserting all of its prefixes into the equation closure.
func (l Lane) forEachCongruenceObservation(visit func(keyspace.Key)) {
	for key := range l.refinements {
		visit(key)
	}
	for key := range l.staticMembers {
		visit(key)
	}
	for proof := range l.proofs {
		visit(proof.Path)
		switch proof.Kind {
		case BranchProofPathEqual, BranchProofPathNotEqual, BranchProofIndexInRange:
			visit(proof.Other)
		}
	}
	for implication := range l.pathPresenceImplications {
		visit(implication.Trigger)
		if implication.HasTriggerPathEqual {
			visit(implication.TriggerOther)
		}
		visit(implication.Target)
	}
}

// pathCongruenceNormal is the canonical spelling of an arbitrary ground path
// against the finite quotient generated by equality endpoints. Once a path
// leaves the endpoint DAG, free-constructor injectivity means no later suffix
// can re-enter it; the unmatched suffix is therefore an exact normal form.
type pathCongruenceNormal struct {
	class  int
	root   pathCongruenceRoot
	kind   keyspace.KeyKind
	suffix []segment.Segment
}

func pathCongruenceNormalsEqual(left, right pathCongruenceNormal) bool {
	if left.class != right.class {
		return false
	}
	if left.class < 0 && left.root != right.root {
		return false
	}
	if len(left.suffix) != len(right.suffix) {
		return false
	}
	for index := range left.suffix {
		if pathConstructor(left.kind, left.suffix[index]) != pathConstructor(right.kind, right.suffix[index]) {
			return false
		}
	}
	return true
}

// HasEquivalentKeyspaceKey reports whether target is reachable from start
// through equality proofs and path-constructor congruence. The finite equation
// DAG contains equality endpoints and their prefixes; arbitrary queries are
// normalized against its quotient as a canonical class/root plus unmatched
// constructor suffix. No semantic depth or work budget is involved.
func (l Lane) HasEquivalentKeyspaceKey(ks *keyspace.KeySpace, start, target keyspace.Key) bool {
	if ks == nil || start.Kind == keyspace.KindInvalid || target.Kind == keyspace.KindInvalid ||
		start == target || l.proofsBottom || len(l.proofs) == 0 {
		return false
	}
	if !l.equalityRootMask.empty() && !l.equalityRootMask.matches(start) {
		return false
	}
	closure := newPathCongruence(ks, l)
	startNormal, startOK := closure.normal(start)
	targetNormal, targetOK := closure.normal(target)
	return startOK && targetOK && pathCongruenceNormalsEqual(startNormal, targetNormal)
}

// equalityProofMayRebaseFrom is a necessary, allocation-free prefilter for
// KeySpace.Rebase. A structural prefix can only share its root address space
// with the key being rebased; keys outside that root cannot contribute to the
// equality closure.
func equalityProofMayRebaseFrom(current, from keyspace.Key) bool {
	if current.Kind != from.Kind {
		return false
	}
	switch current.Kind {
	case keyspace.KindResolverSym:
		return current.Sym == from.Sym && current.Ver == from.Ver
	case keyspace.KindStableSym:
		return current.Sym == from.Sym
	case keyspace.KindNamed, keyspace.KindPlaceholder, keyspace.KindRetSlot:
		return current.Root == from.Root
	default:
		// Non-structural keys are rejected by Rebase. Leave those to the
		// authoritative KeySpace check instead of duplicating its validation.
		return true
	}
}

type pathCongruenceRoot struct {
	Kind keyspace.KeyKind
	Sym  uint64
	Ver  uint32
	Root uint32
}

type pathCongruenceConstructor struct {
	Kind  segment.SegmentKind
	Name  string
	Index int
}

type pathCongruenceNode struct {
	parent      int
	constructor pathCongruenceConstructor
}

type pathCongruenceChild struct {
	parent      int
	constructor pathCongruenceConstructor
}

// pathCongruence is the finite ground congruence closure of equality endpoints.
// nodes is their shared prefix DAG, parent/rank are the union-find equality
// classes, and classes is the closed constructor transition table used to
// normalize arbitrary observed terms without materializing them.
type pathCongruence struct {
	ks       *keyspace.KeySpace
	nodes    []pathCongruenceNode
	parent   []int
	rank     []uint8
	roots    map[pathCongruenceRoot]int
	children map[pathCongruenceChild]int
	explicit map[keyspace.Key]int
	classes  map[pathCongruenceChild]int
}

func newPathCongruence(ks *keyspace.KeySpace, lane Lane) *pathCongruence {
	c := &pathCongruence{ks: ks}
	for proof := range lane.proofs {
		if proof.Kind == BranchProofPathEqual {
			c.add(proof.Path)
			c.add(proof.Other)
		}
	}
	for proof := range lane.proofs {
		if proof.Kind != BranchProofPathEqual {
			continue
		}
		left, leftOK := c.term(proof.Path)
		right, rightOK := c.term(proof.Other)
		if leftOK && rightOK {
			c.union(left, right)
		}
	}
	c.close()
	c.sealClasses()
	return c
}

func (c *pathCongruence) add(key keyspace.Key) (int, bool) {
	if c == nil || !pathCongruenceGroundTermValid(c.ks, key) {
		return 0, false
	}
	if existing, ok := c.explicit[key]; ok {
		return existing, true
	}
	if c.roots == nil {
		c.roots = make(map[pathCongruenceRoot]int)
		c.children = make(map[pathCongruenceChild]int)
		c.explicit = make(map[keyspace.Key]int)
	}
	root := pathCongruenceRoot{Kind: key.Kind, Sym: uint64(key.Sym), Ver: key.Ver, Root: key.Root}
	current, ok := c.roots[root]
	if !ok {
		current = c.appendNode(pathCongruenceNode{parent: -1})
		c.roots[root] = current
	}
	segments, ok := c.ks.SegmentsView(key)
	if !ok {
		return 0, false
	}
	for _, part := range segments {
		constructor := pathConstructor(key.Kind, part)
		child := pathCongruenceChild{parent: current, constructor: constructor}
		next, exists := c.children[child]
		if !exists {
			next = c.appendNode(pathCongruenceNode{parent: current, constructor: constructor})
			c.children[child] = next
		}
		current = next
	}
	c.explicit[key] = current
	return current, true
}

func pathConstructor(kind keyspace.KeyKind, part segment.Segment) pathCongruenceConstructor {
	// Resolver-local structural paths deliberately identify .field and
	// ["field"], matching KeySpace.HasPrefix/Rebase semantics. Stable address
	// spaces retain the exact segment constructor.
	if kind == keyspace.KindResolverSym &&
		(part.Kind == segment.SegmentField || part.Kind == segment.SegmentIndexString) {
		part.Kind = segment.SegmentField
	}
	return pathCongruenceConstructor{Kind: part.Kind, Name: part.Name, Index: part.Index}
}

func (c *pathCongruence) appendNode(node pathCongruenceNode) int {
	index := len(c.nodes)
	c.nodes = append(c.nodes, node)
	c.parent = append(c.parent, index)
	c.rank = append(c.rank, 0)
	return index
}

func (c *pathCongruence) term(key keyspace.Key) (int, bool) {
	term, ok := c.explicit[key]
	if ok {
		return term, true
	}
	return c.add(key)
}

func (c *pathCongruence) normal(key keyspace.Key) (pathCongruenceNormal, bool) {
	if c == nil || !pathCongruenceGroundTermValid(c.ks, key) {
		return pathCongruenceNormal{}, false
	}
	segments, ok := c.ks.SegmentsView(key)
	if !ok {
		return pathCongruenceNormal{}, false
	}
	root := pathCongruenceRoot{Kind: key.Kind, Sym: uint64(key.Sym), Ver: key.Ver, Root: key.Root}
	term, exists := c.roots[root]
	if !exists {
		return pathCongruenceNormal{class: -1, root: root, kind: key.Kind, suffix: segments}, true
	}
	class := c.find(term)
	for index, part := range segments {
		next, found := c.classes[pathCongruenceChild{parent: class, constructor: pathConstructor(key.Kind, part)}]
		if !found {
			return pathCongruenceNormal{class: class, kind: key.Kind, suffix: segments[index:]}, true
		}
		class = next
	}
	return pathCongruenceNormal{class: class, kind: key.Kind}, true
}

// pathCongruenceGroundTermValid admits every keyspace-owned rooted ground
// term, including a bare unversioned lexical root. KeySpace.HasPrefix is
// intentionally narrower: it excludes syntax roots from mutation/rebase
// operations. Equality is different—an explicit proof may identify that
// ground value with a structural boundary existential. Rootless suffixes have
// no value root and therefore remain outside the congruence algebra.
func pathCongruenceGroundTermValid(ks *keyspace.KeySpace, key keyspace.Key) bool {
	if ks == nil || !ks.Valid() || key.Kind == keyspace.KindInvalid || key.Kind == keyspace.KindRootlessSuffix {
		return false
	}
	_, ok := ks.SegmentsView(key)
	return ok
}

func (c *pathCongruence) find(term int) int {
	root := term
	for c.parent[root] != root {
		root = c.parent[root]
	}
	return root
}

func (c *pathCongruence) union(left, right int) bool {
	left = c.find(left)
	right = c.find(right)
	if left == right {
		return false
	}
	if c.rank[left] < c.rank[right] || (c.rank[left] == c.rank[right] && right < left) {
		left, right = right, left
	}
	c.parent[right] = left
	if c.rank[left] == c.rank[right] {
		c.rank[left]++
	}
	return true
}

func (c *pathCongruence) close() {
	for {
		changed := false
		classes := make(map[pathCongruenceChild]int, len(c.nodes))
		for term, node := range c.nodes {
			if node.parent < 0 {
				continue
			}
			signature := pathCongruenceChild{
				parent:      c.find(node.parent),
				constructor: node.constructor,
			}
			if previous, ok := classes[signature]; ok {
				changed = c.union(previous, term) || changed
				continue
			}
			classes[signature] = term
		}
		if !changed {
			return
		}
	}
}

func (c *pathCongruence) sealClasses() {
	if len(c.nodes) == 0 {
		return
	}
	c.classes = make(map[pathCongruenceChild]int, len(c.nodes))
	for term, node := range c.nodes {
		if node.parent < 0 {
			continue
		}
		signature := pathCongruenceChild{parent: c.find(node.parent), constructor: node.constructor}
		class := c.find(term)
		if prior, exists := c.classes[signature]; exists && prior != class {
			panic("pathevidence: unsealed congruence class")
		}
		c.classes[signature] = class
	}
}

func equalityProofRootMask(proof BranchProof) equalityRootMask {
	if proof.Kind != BranchProofPathEqual {
		return equalityRootMask{}
	}
	mask := equalityRootMaskForKey(proof.Path)
	mask.merge(equalityRootMaskForKey(proof.Other))
	return mask
}

func equalityRootMaskForKey(key keyspace.Key) equalityRootMask {
	root := uint64(key.Kind)<<56 | uint64(key.Sym)<<24 | uint64(key.Ver)
	root ^= uint64(key.Root) * 0x9e3779b97f4a7c15
	root ^= root >> 30
	root *= 0xbf58476d1ce4e5b9
	root ^= root >> 27
	var mask equalityRootMask
	bit := root & 255
	mask[bit>>6] = uint64(1) << (bit & 63)
	return mask
}

func (m *equalityRootMask) merge(other equalityRootMask) {
	for i := range m {
		m[i] |= other[i]
	}
}

func (m equalityRootMask) empty() bool {
	return m == equalityRootMask{}
}

func (m equalityRootMask) matches(key keyspace.Key) bool {
	needle := equalityRootMaskForKey(key)
	for i := range m {
		if m[i]&needle[i] != 0 {
			return true
		}
	}
	return false
}

// EquivalentRootKeys returns root-symbol keys proven equal to pathKey by exact
// equality endpoints. It is intentionally narrower than EquivalentPathKeys:
// root-value refinement only consumes root aliases, so following descendant
// rebases and formatting every intermediate path creates large allocation
// spikes while producing values the caller immediately discards.
func (l Lane) EquivalentRootKeys(ks *keyspace.KeySpace, pathKey pathdom.PathKey) []keyspace.Key {
	if pathKey == "" || l.proofsBottom || len(l.proofs) == 0 {
		return nil
	}
	start, ok := ks.FromStateKey(pathKey)
	if !ok {
		return nil
	}
	seen := map[keyspace.Key]struct{}{start: {}}
	queue := []keyspace.Key{start}
	var out []keyspace.Key
	for len(queue) != 0 {
		current := queue[0]
		queue = queue[1:]
		for proof := range l.proofs {
			if proof.Kind != BranchProofPathEqual {
				continue
			}
			next, ok := exactEquivalentEndpoint(ks, current, proof)
			if !ok {
				continue
			}
			if _, ok := seen[next]; ok {
				continue
			}
			seen[next] = struct{}{}
			if next.Segs == 0 {
				out = append(out, next)
			}
			queue = append(queue, next)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		return ks.Format(out[i]) < ks.Format(out[j])
	})
	return out
}

func exactEquivalentEndpoint(ks *keyspace.KeySpace, current keyspace.Key, proof BranchProof) (keyspace.Key, bool) {
	if structuralKeysEquivalent(ks, current, proof.Path) {
		return proof.Other, true
	}
	if structuralKeysEquivalent(ks, current, proof.Other) {
		return proof.Path, true
	}
	return keyspace.Key{}, false
}

func structuralKeysEquivalent(ks *keyspace.KeySpace, a, b keyspace.Key) bool {
	return ks.HasPrefix(a, b) && ks.HasPrefix(b, a)
}

func rebaseEquivalentPathKey(ks *keyspace.KeySpace, pathKey, from, to keyspace.Key) (keyspace.Key, bool) {
	if cyclicDescendantExpansion(ks, pathKey, from, to) {
		return keyspace.Key{}, false
	}
	rebased, ok := ks.Rebase(pathKey, from, to)
	if !ok || !ks.HasPrefix(rebased, to) {
		return keyspace.Key{}, false
	}
	return rebased, true
}

func cyclicDescendantExpansion(ks *keyspace.KeySpace, pathKey, from, to keyspace.Key) bool {
	return ks.HasStrictPrefix(to, from) && ks.HasPrefix(pathKey, to)
}

func cloneBranchProofSet(in map[BranchProof]struct{}) map[BranchProof]struct{} {
	if len(in) == 0 {
		return nil
	}
	out := make(map[BranchProof]struct{}, len(in))
	for k := range in {
		out[k] = struct{}{}
	}
	return out
}

func deleteBranchProofsWhere(
	in map[BranchProof]struct{},
	matches func(BranchProof) bool,
) (map[BranchProof]struct{}, bool) {
	return mapedit.DeleteMatching(in, func(proof BranchProof, _ struct{}) bool {
		return matches(proof)
	})
}

func branchProofMatchesPath(proof BranchProof, matches func(keyspace.Key) bool) bool {
	if matches == nil {
		return false
	}
	if matches(proof.Path) {
		return true
	}
	switch proof.Kind {
	case BranchProofPathEqual, BranchProofPathNotEqual, BranchProofIndexInRange:
		return matches(proof.Other)
	default:
		return false
	}
}

func branchProofsFromSet(ks *keyspace.KeySpace, in map[BranchProof]struct{}) []BranchProof {
	if len(in) == 0 {
		return nil
	}
	out := make([]BranchProof, 0, len(in))
	for proof := range in {
		out = append(out, proof)
	}
	sort.Slice(out, func(i, j int) bool {
		return branchProofLess(ks, out[i], out[j])
	})
	return out
}

func branchProofLess(ks *keyspace.KeySpace, a, b BranchProof) bool {
	if a.Kind != b.Kind {
		return a.Kind < b.Kind
	}
	if a.Path != b.Path {
		return ks.Less(a.Path, b.Path)
	}
	if a.Other != b.Other {
		return ks.Less(a.Other, b.Other)
	}
	return a.Presence.String() < b.Presence.String()
}
