// Code generated by the rule family emitter from the "placement-return-escape" rule declaration; DO NOT EDIT.
//
// The installer seals every primitive through the plane at the geometry the
// declaration states, the family holds one sealed row per plan row, and the
// worker performs one invocation over lane-owned scratch. The semantic fold
// this file calls, and the relation derivations its joins name, remain the
// owner's own source.

package returnescape

import (
	"github.com/wippyai/go-lua/analysis/engine/execution"
	"github.com/wippyai/go-lua/analysis/schema/rule/program"
	"github.com/wippyai/go-lua/analysis/schema/structure"
	"github.com/wippyai/go-lua/domain/heap"
	"github.com/wippyai/go-lua/domain/placement"
	"github.com/wippyai/go-lua/domain/value"
)

// familyReducer is the sealed semantic half of one invocation. It holds the
// carriers this row's fold is indexed by, and its type is the family's, so the
// call below is a static direct call rather than an interface dispatch.
type familyReducer struct {
}

// Reduce answers one selected route. The route coordinate, cell, and tag
// are the three owner-issued halves of the one member the read observed,
// so the fold never re-derives a destination or correlation.
func (fold familyReducer) Reduce(routeCoordinate heap.Key, cell execution.SelectedCell[placement.Fact]) (placement.Fact, structure.ReductionOutcome) {
	return ReturnEscapeFold(cell.Tag, cell.Value)
}

// Empty settles the row whose derived relation selected no route at all. An
// empty selection is not a refusal: it is the one disposition that says the
// relation was read and named nothing.
func (familyReducer) Empty() structure.ReductionOutcome { return structure.NoSelection }

// familyRow is the sealed static half of one plan row: the candidate its fold
// is indexed by and every primitive the installer sealed through the plane.
type familyRow struct {
	candidate   value.ReturnBoundary
	read0       execution.ExactRead[value.DenseCoordinate, value.Value]
	read0Policy execution.ReadCellPolicy[value.Value]
	read1       []execution.ExactRead[value.DenseCoordinate, value.Value]
	read1Policy execution.ReadCellPolicy[value.Value]
	read2       execution.SelectedRead[placement.DenseCoordinate, placement.Fact]
	write       execution.RouteWrite[placement.DenseCoordinate, placement.Fact]
}

// sealedFamily is this rule's whole installed family: one row per plan row and
// the sealed state every invocation reads. Nothing here is mutated after the
// installer returns.
type sealedFamily struct {
	rows            []familyRow
	placementSchema placement.Schema
	valueSchema     *value.Schema
	plane           execution.FormPlane[placement.DenseCoordinate, placement.Fact]
	width           int
	read1Width      int
}

func (sealed *sealedFamily) NewExecutor(run *execution.Run) execution.Executor {
	if sealed == nil || run == nil {
		return nil
	}
	if sealed.read1Width < 0 {
		return nil
	}
	if sealed.width < 0 {
		return nil
	}
	// Every buffer is sized once at the sealed width of the selection this rule
	// spans, so an ordinary invocation allocates nothing.
	return &familyWorker{
		family:     sealed,
		run:        run,
		members:    make([]execution.RouteMember, sealed.width),
		cells:      make([]execution.SelectedCell[placement.Fact], sealed.width),
		routes:     make([]heap.Key, sealed.width),
		read1Cells: make([]execution.MemberCell[value.Value], sealed.read1Width),
	}
}

func (*sealedFamily) InputCapacity() int  { return 1 }
func (*sealedFamily) OutputCapacity() int { return 1 }

// familyWorker is one epoch's reusable invocation lane. Every scratch lives for
// the worker's lifetime, so a warm invocation opens its cursors and its write
// transaction without allocating.
type familyWorker struct {
	family     *sealedFamily
	run        *execution.Run
	read0      execution.Scratch[value.DenseCoordinate, value.Value]
	read1      execution.Scratch[value.DenseCoordinate, value.Value]
	read1Cells []execution.MemberCell[value.Value]
	read2      execution.SelectedScratch[placement.DenseCoordinate, placement.Fact]
	write      execution.RouteScratch[placement.DenseCoordinate, placement.Fact]
	members    []execution.RouteMember
	cells      []execution.SelectedCell[placement.Fact]
	routes     []heap.Key
}

// settle submits one non-publishing disposition. Every refusal path in this
// worker ends here, so the ticket is settled exactly once.
func (lane *familyWorker) settle(ticket execution.Ticket, outcome structure.ReductionOutcome) (execution.Result, bool) {
	if !ticket.Submit(outcome) {
		return execution.Result{}, false
	}
	return execution.NewResult(outcome, 0)
}

// Execute performs one routed invocation: the prerequisite reads are taken,
// the declared relation derives this candidate's route set once, the selection
// is observed at exactly those members, and one fold publishes at each.
func (lane *familyWorker) Execute(frame execution.Frame, ticket execution.Ticket) (execution.Result, bool) {
	if lane == nil || lane.family == nil || lane.run == nil || !frame.Valid(ticket) || !lane.run.Owns(ticket) {
		return execution.Result{}, false
	}
	local, localOK := ticket.LocalOrdinal()
	if !localOK || uint64(local) >= uint64(len(lane.family.rows)) {
		return execution.Result{}, false
	}
	row := lane.family.rows[local]
	var input0 value.Value
	switch lane.read0Cell(row.read0, row.read0Policy, ticket, &input0) {
	case structure.NoCandidate:
		return lane.settle(ticket, structure.NoCandidate)
	case structure.Refuse:
		return lane.settle(ticket, structure.Refuse)
	}
	read1Count := len(row.read1)
	if read1Count > len(lane.read1Cells) {
		return lane.settle(ticket, structure.Refuse)
	}
	read1Cells := lane.read1Cells[:read1Count]
	for index := 0; index < read1Count; index++ {
		if lane.read1Cell(row.read1[index], row.read1Policy, ticket, &read1Cells[index]) != structure.Concrete {
			return lane.settle(ticket, structure.Refuse)
		}
	}
	read1Vector, read1VectorOK := execution.NewMemberVector(read1Cells)
	if !read1VectorOK {
		return lane.settle(ticket, structure.Refuse)
	}
	// The route set is the relation's own answer, derived once per invocation from
	// the carriers its declaration names. Nothing below re-derives it.
	derived, derivedOK := DeriveReturnRoutes(lane.family.placementSchema, lane.family.valueSchema, row.candidate, input0, read1Vector)
	if !derivedOK {
		return lane.settle(ticket, structure.Refuse)
	}
	count := ReturnRouteCount(derived)
	if count < 0 || count > len(lane.members) || count > len(lane.cells) || count > len(lane.routes) {
		return lane.settle(ticket, structure.Refuse)
	}
	members := lane.members[:count]
	cells := lane.cells[:count]
	routes := lane.routes[:count]
	for index := 0; index < count; index++ {
		selected, selectedOK := ReturnRouteAt(derived, index)
		if !selectedOK {
			return lane.settle(ticket, structure.Refuse)
		}
		returnRouteKey, returnRouteKeyPaired, returnRouteKeyOK := selected.Coordinates()
		_ = returnRouteKeyPaired
		if !returnRouteKeyOK {
			return lane.settle(ticket, structure.Refuse)
		}
		returnRouteTag, returnRouteTagOK := selected.Predicate()
		if !returnRouteTagOK {
			return lane.settle(ticket, structure.Refuse)
		}
		returnRouteDestinationPaired, returnRouteDestination, returnRouteDestinationOK := selected.Coordinates()
		_ = returnRouteDestinationPaired
		if !returnRouteDestinationOK {
			return lane.settle(ticket, structure.Refuse)
		}
		dense, denseOK := lane.family.placementSchema.KeyIndex(returnRouteKey)
		if !denseOK {
			return lane.settle(ticket, structure.Refuse)
		}
		destinationDense, destinationDenseOK := lane.family.placementSchema.KeyIndex(returnRouteDestination)
		if !destinationDenseOK {
			return lane.settle(ticket, structure.Refuse)
		}
		member, memberOK := lane.family.plane.RouteMember(uint32(dense), uint32(destinationDense), uint64(returnRouteTag))
		if !memberOK {
			return lane.settle(ticket, structure.Refuse)
		}
		members[index] = member
		routes[index] = returnRouteDestination
	}
	// An empty derived relation is a read that named nothing, which is exhausted
	// rather than available; anything else is a selection that did not observe.
	status := row.read2.Observe(ticket, &lane.read2, members, cells)
	if count == 0 {
		if status != execution.ReadExhausted {
			return lane.settle(ticket, structure.Refuse)
		}
	} else if status != execution.ReadAvailable {
		return lane.settle(ticket, structure.Refuse)
	}
	outcome := execution.FoldSelectedRoute(ticket, row.write, &lane.write, cells, members, routes, familyReducer{})
	if !ticket.Submit(outcome) {
		return execution.Result{}, false
	}
	written := 0
	if outcome == structure.Concrete {
		written = 1
	}
	return execution.NewResult(outcome, written)
}

// read0Cell takes one exact prerequisite cell. The cursor is closed before the
// value is used, and the row's sealed policy settles what an unwritten
// coordinate delivers.
func (lane *familyWorker) read0Cell(read execution.ExactRead[value.DenseCoordinate, value.Value], policy execution.ReadCellPolicy[value.Value], ticket execution.Ticket, destination *value.Value) structure.ReductionOutcome {
	if lane == nil || destination == nil || !read.Valid() {
		return structure.Refuse
	}
	switch read.Read(ticket, &lane.read0) {
	case execution.ReadAvailable:
		cell, available := lane.read0.Value()
		present := lane.read0.Present()
		if !read.Close(ticket, &lane.read0) {
			_ = lane.read0.Discard(ticket)
			return structure.Refuse
		}
		if !available {
			return structure.Refuse
		}
		cell, present = policy.Cell(cell, present)
		if !present {
			return structure.NoCandidate
		}
		*destination = cell
		return structure.Concrete
	case execution.ReadExhausted:
		if !read.Close(ticket, &lane.read0) {
			return structure.Refuse
		}
		return structure.NoCandidate
	default:
		_ = lane.read0.Discard(ticket)
		return structure.Refuse
	}
}

// read1Cell takes one member of a nested set at its own sealed coordinate.
func (lane *familyWorker) read1Cell(read execution.ExactRead[value.DenseCoordinate, value.Value], policy execution.ReadCellPolicy[value.Value], ticket execution.Ticket, destination *execution.MemberCell[value.Value]) structure.ReductionOutcome {
	if lane == nil || destination == nil || !read.Valid() {
		return structure.Refuse
	}
	if read.Read(ticket, &lane.read1) != execution.ReadAvailable {
		_ = lane.read1.Discard(ticket)
		return structure.Refuse
	}
	cell, available := lane.read1.Value()
	present := lane.read1.Present()
	if !read.Close(ticket, &lane.read1) || !lane.read1.Reuse(ticket) {
		_ = lane.read1.Discard(ticket)
		return structure.Refuse
	}
	if !available {
		return structure.Refuse
	}
	cell, present = policy.Cell(cell, present)
	*destination = execution.MemberCell[value.Value]{Value: cell, Present: present}
	return structure.Concrete
}

// familyInstaller authors this rule's execution family. The axis schemas it
// holds are the ones the declaration names: the candidate directory it resolves
// dense candidates through, and every static axis a declared relation derives
// against. It reaches no owner callback and no runtime capability.
//
// It holds NO rule ordinal. Which rule an installer authors is the claim it
// was installed under, and the family table resolves an installer only for
// that claim; a copy kept here would be a second answer to a question the
// table already answers, and one that goes stale on its own.
type familyInstaller struct {
	placementSchema placement.Schema
	valueSchema     *value.Schema
}

// NewFamilyInstaller seals this rule's family installer against the axis schemas
// its declaration names. The bind arm that resolves those schemas from its
// composition's authorities is the owner's own, because how an authority
// record is reached is that composition's knowledge and not this rule's.
func NewFamilyInstaller(placementSchema placement.Schema, valueSchema *value.Schema) (execution.RuleFamilyInstaller[placement.DenseCoordinate, placement.Fact], bool) {
	install := familyInstaller{placementSchema: placementSchema, valueSchema: valueSchema}
	if !install.available() {
		return nil, false
	}
	return install, true
}

// available proves every schema this installer seals against was supplied.
// Whether a supplied schema is itself admissible is that schema's own answer,
// given below when a candidate or a projection is resolved through it.
func (install familyInstaller) available() bool {
	return install.valueSchema != nil
}

func (install familyInstaller) InstallRuleFamily(plane execution.FormPlane[placement.DenseCoordinate, placement.Fact], _ uint32, rows []execution.FormRow) (execution.Family, []execution.FormAddress, bool) {
	if !install.available() || !plane.Valid() || len(rows) == 0 {
		return nil, nil, false
	}
	sealed := &sealedFamily{rows: make([]familyRow, 0, len(rows)), placementSchema: install.placementSchema, valueSchema: install.valueSchema}
	width := plane.RouteWidth()
	if width < 0 {
		return nil, nil, false
	}
	sealed.plane, sealed.width = plane, width
	read1Width := 0
	addresses := make([]execution.FormAddress, 0, len(rows))
	for _, planRow := range rows {
		if planRow.Form != execution.FormSelectedRoute || !planRow.Rule.Available() || planRow.Rule.ReadCount() != 3 || planRow.Rule.OutputCount() != 1 {
			return nil, nil, false
		}
		output, outputOK := planRow.Rule.OutputAt(0)
		if !outputOK || output.Mode != program.ModeRoute || !output.RouteJoinPresent || output.RouteJoin != 2 || output.Slot != 0 {
			return nil, nil, false
		}
		plan0, plan0OK := planRow.Rule.ReadAt(0)
		if !plan0OK || plan0.Form != program.Exact || plan0.Input != 0 || plan0.PointBound != program.PointBound {
			return nil, nil, false
		}
		plan1, plan1OK := planRow.Rule.ReadAt(1)
		if !plan1OK || plan1.Form != program.Summary || plan1.Input != 0 || plan1.PointBound != program.PointBound {
			return nil, nil, false
		}
		plan2, plan2OK := planRow.Rule.ReadAt(2)
		if !plan2OK || plan2.Form != program.Selected || plan2.Input != 0 || plan2.PointBound != program.PointBound || plan2.Factor != output.Factor {
			return nil, nil, false
		}
		candidate, candidateOK := install.valueSchema.ReturnBoundaryAt(int(planRow.Candidate))
		if !candidateOK {
			return nil, nil, false
		}
		foreign0, foreign0OK := plane.Foreign(plan0.Factor)
		if !foreign0OK {
			return nil, nil, false
		}
		read0Sealed, read0SealedOK := execution.ForeignRowExactRead[value.DenseCoordinate, value.Value](foreign0, planRow, 0)
		read0Policy, read0PolicyOK := execution.ForeignReadCellPolicy[value.DenseCoordinate, value.Value](foreign0, plan0.Contract)
		if !read0PolicyOK {
			return nil, nil, false
		}
		foreign1, foreign1OK := plane.Foreign(plan1.Factor)
		if !foreign1OK {
			return nil, nil, false
		}
		read1Count, read1CountOK := planRow.MemberCount(1)
		if !read1CountOK {
			return nil, nil, false
		}
		read1Sealed := make([]execution.ExactRead[value.DenseCoordinate, value.Value], read1Count)
		for index := 0; index < read1Count; index++ {
			memberDense, memberDenseOK := planRow.MemberAt(1, index)
			if !memberDenseOK {
				return nil, nil, false
			}
			memberRead, memberReadOK := execution.ForeignMemberExactRead[value.DenseCoordinate, value.Value](foreign1, memberDense, uint16(plan1.Input))
			if !memberReadOK {
				return nil, nil, false
			}
			read1Sealed[index] = memberRead
		}
		if read1Count > read1Width {
			read1Width = read1Count
		}
		read1Policy, read1PolicyOK := execution.ForeignReadCellPolicy[value.DenseCoordinate, value.Value](foreign1, plan1.Contract)
		if !read1PolicyOK {
			return nil, nil, false
		}
		read2Sealed, read2SealedOK := plane.SelectedRead(uint16(plan2.Input), plan2.Contract, execution.ReadCellPolicy[placement.Fact]{})
		writeSealed, writeSealedOK := plane.RouteWrite(uint16(output.Slot))
		if !writeSealedOK || !read0SealedOK || !read2SealedOK {
			return nil, nil, false
		}
		addresses = append(addresses, execution.FormAddress{Member: planRow.Member, Local: uint32(len(sealed.rows))})
		sealed.rows = append(sealed.rows, familyRow{candidate: candidate, read0: read0Sealed, read0Policy: read0Policy, read1: read1Sealed, read1Policy: read1Policy, read2: read2Sealed, write: writeSealed})
	}
	sealed.read1Width = read1Width
	return sealed, addresses, true
}
