// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.

package relation

import (
	"github.com/wippyai/go-lua/analysis/identity"
	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
	"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"
	valuedomain "github.com/wippyai/go-lua/domain/value"
)

// PayloadTypes names the owner-issued TypeID each column of this axis
// carries.
type PayloadTypes struct {
	Value                    model.TypeID
	ArithmeticCandidate      model.TypeID
	EqualityCandidate        model.TypeID
	OrderCandidate           model.TypeID
	RefinementCandidate      model.TypeID
	RuntimeKindCandidate     model.TypeID
	ModuleLoadCandidate      model.TypeID
	AllocationCandidate      model.TypeID
	GlobalBootstrapCandidate model.TypeID
	ValueSourceCandidate     model.TypeID
	ValueSummary             model.TypeID
	FreshResultCandidate     model.TypeID
	StorageTransferCandidate model.TypeID
	ValueCoordinate          model.TypeID
	ValueRouteTag            model.TypeID
}

// Available reports whether every column has an owner-issued type.
func (types PayloadTypes) Available() bool {
	return types.Value.Available() && types.ArithmeticCandidate.Available() && types.EqualityCandidate.Available() && types.OrderCandidate.Available() && types.RefinementCandidate.Available() && types.RuntimeKindCandidate.Available() && types.ModuleLoadCandidate.Available() && types.AllocationCandidate.Available() && types.GlobalBootstrapCandidate.Available() && types.ValueSourceCandidate.Available() && types.ValueSummary.Available() && types.FreshResultCandidate.Available() && types.StorageTransferCandidate.Available() && types.ValueCoordinate.Available() && types.ValueRouteTag.Available()
}

// PayloadTags names the store fence each column of this axis interns under.
type PayloadTags struct {
	Value                    identity.ContentID
	ArithmeticCandidate      identity.ContentID
	EqualityCandidate        identity.ContentID
	OrderCandidate           identity.ContentID
	RefinementCandidate      identity.ContentID
	RuntimeKindCandidate     identity.ContentID
	ModuleLoadCandidate      identity.ContentID
	AllocationCandidate      identity.ContentID
	GlobalBootstrapCandidate identity.ContentID
	ValueSourceCandidate     identity.ContentID
	ValueSummary             identity.ContentID
	FreshResultCandidate     identity.ContentID
	StorageTransferCandidate identity.ContentID
	ValueCoordinate          identity.ContentID
	ValueRouteTag            identity.ContentID
}

// Available reports whether every column has a store fence.
func (tags PayloadTags) Available() bool {
	return tags.Value.Available() && tags.ArithmeticCandidate.Available() && tags.EqualityCandidate.Available() && tags.OrderCandidate.Available() && tags.RefinementCandidate.Available() && tags.RuntimeKindCandidate.Available() && tags.ModuleLoadCandidate.Available() && tags.AllocationCandidate.Available() && tags.GlobalBootstrapCandidate.Available() && tags.ValueSourceCandidate.Available() && tags.ValueSummary.Available() && tags.FreshResultCandidate.Available() && tags.StorageTransferCandidate.Available() && tags.ValueCoordinate.Available() && tags.ValueRouteTag.Available()
}

// Payloads is this axis's thin typed owner-column publisher: one Column per
// payload type the axis declares, each over its own solve-local store, and
// the only place one of its domain values crosses into a value token.
type Payloads struct {
	Value                    *relbindgen.Column[valuedomain.Value]
	ArithmeticCandidate      *relbindgen.Column[valuedomain.BinaryArithmetic]
	EqualityCandidate        *relbindgen.Column[valuedomain.BinaryEquality]
	OrderCandidate           *relbindgen.Column[valuedomain.BinaryOrder]
	RefinementCandidate      *relbindgen.Column[valuedomain.PresenceRefinement]
	RuntimeKindCandidate     *relbindgen.Column[valuedomain.RuntimeKindCall]
	ModuleLoadCandidate      *relbindgen.Column[valuedomain.ModuleLoadCall]
	AllocationCandidate      *relbindgen.Column[*valuedomain.AllocationResult]
	GlobalBootstrapCandidate *relbindgen.Column[*valuedomain.GlobalBootstrapResult]
	ValueSourceCandidate     *relbindgen.Column[valuedomain.SourceSeed]
	ValueSummary             *relbindgen.Column[valuedomain.ValueSummaryObservation]
	FreshResultCandidate     *relbindgen.Column[valuedomain.FreshResultCall]
	StorageTransferCandidate *relbindgen.Column[valuedomain.StorageTransfer]
	ValueCoordinate          *relbindgen.Column[valuedomain.Coordinate]
	ValueRouteTag            *relbindgen.Column[uint64]
}

// NewPayloads installs one column per declared payload over a store fenced
// by that payload's own tag. Reserve is the interning reservation each store
// starts with; a store grows past it, so it is a caller's sizing and never a
// bound on what an owner may intern.
func NewPayloads(types PayloadTypes, tags PayloadTags, reserve int) (Payloads, bool) {
	if !types.Available() || !tags.Available() || reserve < 0 {
		return Payloads{}, false
	}
	var payloads Payloads
	valueStore, ok := relbindgen.NewStore[valuedomain.Value](tags.Value, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.Value, ok = relbindgen.NewColumn(types.Value, valueStore); !ok {
		return Payloads{}, false
	}
	arithmeticCandidateStore, ok := relbindgen.NewStore[valuedomain.BinaryArithmetic](tags.ArithmeticCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.ArithmeticCandidate, ok = relbindgen.NewColumn(types.ArithmeticCandidate, arithmeticCandidateStore); !ok {
		return Payloads{}, false
	}
	equalityCandidateStore, ok := relbindgen.NewStore[valuedomain.BinaryEquality](tags.EqualityCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.EqualityCandidate, ok = relbindgen.NewColumn(types.EqualityCandidate, equalityCandidateStore); !ok {
		return Payloads{}, false
	}
	orderCandidateStore, ok := relbindgen.NewStore[valuedomain.BinaryOrder](tags.OrderCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.OrderCandidate, ok = relbindgen.NewColumn(types.OrderCandidate, orderCandidateStore); !ok {
		return Payloads{}, false
	}
	refinementCandidateStore, ok := relbindgen.NewStore[valuedomain.PresenceRefinement](tags.RefinementCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.RefinementCandidate, ok = relbindgen.NewColumn(types.RefinementCandidate, refinementCandidateStore); !ok {
		return Payloads{}, false
	}
	runtimeKindCandidateStore, ok := relbindgen.NewStore[valuedomain.RuntimeKindCall](tags.RuntimeKindCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.RuntimeKindCandidate, ok = relbindgen.NewColumn(types.RuntimeKindCandidate, runtimeKindCandidateStore); !ok {
		return Payloads{}, false
	}
	moduleLoadCandidateStore, ok := relbindgen.NewStore[valuedomain.ModuleLoadCall](tags.ModuleLoadCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.ModuleLoadCandidate, ok = relbindgen.NewColumn(types.ModuleLoadCandidate, moduleLoadCandidateStore); !ok {
		return Payloads{}, false
	}
	allocationCandidateStore, ok := relbindgen.NewStore[*valuedomain.AllocationResult](tags.AllocationCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.AllocationCandidate, ok = relbindgen.NewColumn(types.AllocationCandidate, allocationCandidateStore); !ok {
		return Payloads{}, false
	}
	globalBootstrapCandidateStore, ok := relbindgen.NewStore[*valuedomain.GlobalBootstrapResult](tags.GlobalBootstrapCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.GlobalBootstrapCandidate, ok = relbindgen.NewColumn(types.GlobalBootstrapCandidate, globalBootstrapCandidateStore); !ok {
		return Payloads{}, false
	}
	valueSourceCandidateStore, ok := relbindgen.NewStore[valuedomain.SourceSeed](tags.ValueSourceCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.ValueSourceCandidate, ok = relbindgen.NewColumn(types.ValueSourceCandidate, valueSourceCandidateStore); !ok {
		return Payloads{}, false
	}
	valueSummaryStore, ok := relbindgen.NewStore[valuedomain.ValueSummaryObservation](tags.ValueSummary, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.ValueSummary, ok = relbindgen.NewColumn(types.ValueSummary, valueSummaryStore); !ok {
		return Payloads{}, false
	}
	freshResultCandidateStore, ok := relbindgen.NewStore[valuedomain.FreshResultCall](tags.FreshResultCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.FreshResultCandidate, ok = relbindgen.NewColumn(types.FreshResultCandidate, freshResultCandidateStore); !ok {
		return Payloads{}, false
	}
	storageTransferCandidateStore, ok := relbindgen.NewStore[valuedomain.StorageTransfer](tags.StorageTransferCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.StorageTransferCandidate, ok = relbindgen.NewColumn(types.StorageTransferCandidate, storageTransferCandidateStore); !ok {
		return Payloads{}, false
	}
	valueCoordinateStore, ok := relbindgen.NewStore[valuedomain.Coordinate](tags.ValueCoordinate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.ValueCoordinate, ok = relbindgen.NewColumn(types.ValueCoordinate, valueCoordinateStore); !ok {
		return Payloads{}, false
	}
	valueRouteTagStore, ok := relbindgen.NewStore[uint64](tags.ValueRouteTag, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.ValueRouteTag, ok = relbindgen.NewColumn(types.ValueRouteTag, valueRouteTagStore); !ok {
		return Payloads{}, false
	}
	return payloads, true
}

// Available reports whether every column carries live storage.
func (payloads Payloads) Available() bool {
	return payloads.Value.Available() && payloads.ArithmeticCandidate.Available() && payloads.EqualityCandidate.Available() && payloads.OrderCandidate.Available() && payloads.RefinementCandidate.Available() && payloads.RuntimeKindCandidate.Available() && payloads.ModuleLoadCandidate.Available() && payloads.AllocationCandidate.Available() && payloads.GlobalBootstrapCandidate.Available() && payloads.ValueSourceCandidate.Available() && payloads.ValueSummary.Available() && payloads.FreshResultCandidate.Available() && payloads.StorageTransferCandidate.Available() && payloads.ValueCoordinate.Available() && payloads.ValueRouteTag.Available()
}

// Lattices are this axis's ascent witnesses. Each names the owner's own
// API, so this layer never guesses a method name and never carries a
// function value.
type Lattices struct {
	Value ValueLattice
}

// Algebras states one ascent authority per TypeID that declares an order.
// The state layer resolves a proposal's order by TypeID alone, never by the
// operation that produced it.
func (payloads Payloads) Algebras(issuer binding.Issuer, lattices Lattices) ([]binding.ValueAlgebra, bool) {
	if !payloads.Available() || !issuer.Available() {
		return nil, false
	}
	algebras := make([]binding.ValueAlgebra, 0, 1)
	valueAlgebra, ok := relbindgen.NewAlgebra[valuedomain.Value, ValueLattice](payloads.Value, issuer, lattices.Value)
	if !ok {
		return nil, false
	}
	algebras = append(algebras, valueAlgebra)
	return algebras, true
}
