// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.

package relation

import (
	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
	"github.com/wippyai/go-lua/analysis/relation/semantic/signature"
	"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"
	valuedomain "github.com/wippyai/go-lua/domain/value"
)

// ValueOrderColumns are the owner column codecs of the
// value/order binding.
type ValueOrderColumns struct {
	Value          *relbindgen.Column[valuedomain.Value]
	OrderCandidate *relbindgen.Column[valuedomain.BinaryOrder]
}

// NewValueOrderColumns names this family's own owner columns. A column an axis
// other than this one publishes is handed in, never reached for.
func NewValueOrderColumns(value *relbindgen.Column[valuedomain.Value], orderCandidate *relbindgen.Column[valuedomain.BinaryOrder]) (ValueOrderColumns, bool) {
	columns := ValueOrderColumns{Value: value, OrderCandidate: orderCandidate}
	if !columns.Available() {
		return ValueOrderColumns{}, false
	}
	return columns, true
}

// Available reports whether every column this binding needs carries an
// owner-issued type and live storage.
func (columns ValueOrderColumns) Available() bool {
	return columns.Value.Available() && columns.OrderCandidate.Available()
}

// ValueOrderArgument is the decoded frame of one
// value/order invocation.
type ValueOrderArgument struct {
	Candidate valuedomain.BinaryOrder
	Left      valuedomain.Value
	Right     valuedomain.Value
}

// ValueOrderJudgment is the owner mathematics this binding carries. The axis
// states it by hand: nothing in this file can name a relation, a cell, a
// buffer or an engine value, so the mathematics stays where its owner wrote
// it and this artifact stays free of it.
type ValueOrderJudgment interface {
	relbindgen.Operation[ValueOrderArgument, valuedomain.Value]
	Available() bool
}

// The hand-authored judgment answers this family's own contract, and the
// assertion is what makes the two halves one binding.
var _ ValueOrderJudgment = ValueOrderOperation{}

// BindValueOrder admits the value/order family
// under its sealed signature.
func BindValueOrder(operation signature.Signature, judgment ValueOrderJudgment, columns ValueOrderColumns, refusal model.RefusalID) (binding.Factory, bool) {
	if judgment == nil || !judgment.Available() || !columns.Available() {
		return nil, false
	}
	return relbindgen.Bind(relbindgen.Spec[ValueOrderArgument, valuedomain.Value]{
		Signature: operation,
		Decoder:   valueOrderDecoder{columns: columns},
		Encoder:   valueOrderEncoder{columns: columns},
		Operation: judgment,
		Address:   0,
		Refusal:   refusal,
	})
}

type valueOrderDecoder struct {
	columns ValueOrderColumns
}

func (decoder valueOrderDecoder) Decode(inputs relbindgen.Inputs) (ValueOrderArgument, bool) {
	candidate, ok := relbindgen.ScalarAt(inputs, 0, decoder.columns.OrderCandidate)
	if !ok {
		return ValueOrderArgument{}, false
	}
	left, ok := relbindgen.ScalarAt(inputs, 1, decoder.columns.Value)
	if !ok {
		return ValueOrderArgument{}, false
	}
	right, ok := relbindgen.ScalarAt(inputs, 2, decoder.columns.Value)
	if !ok {
		return ValueOrderArgument{}, false
	}
	return ValueOrderArgument{Candidate: candidate, Left: left, Right: right}, true
}

type valueOrderEncoder struct {
	columns ValueOrderColumns
}

func (encoder valueOrderEncoder) Encode(outputs relbindgen.Outputs, value valuedomain.Value) bool {
	return relbindgen.PutColumn(outputs, 0, encoder.columns.Value, value)
}
