// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.

package relation

import (
	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
	"github.com/wippyai/go-lua/analysis/relation/semantic/signature"
	"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"
	calldomain "github.com/wippyai/go-lua/domain/call"
	valuedomain "github.com/wippyai/go-lua/domain/value"
)

// ValueRuntimeKindColumns are the owner column codecs of the
// value/runtimekind binding.
type ValueRuntimeKindColumns struct {
	Value                *relbindgen.Column[valuedomain.Value]
	Call                 *relbindgen.Column[calldomain.Value]
	RuntimeKindCandidate *relbindgen.Column[valuedomain.RuntimeKindCall]
}

// NewValueRuntimeKindColumns names this family's own owner columns. A column an axis
// other than this one publishes is handed in, never reached for.
func NewValueRuntimeKindColumns(value *relbindgen.Column[valuedomain.Value], call *relbindgen.Column[calldomain.Value], runtimeKindCandidate *relbindgen.Column[valuedomain.RuntimeKindCall]) (ValueRuntimeKindColumns, bool) {
	columns := ValueRuntimeKindColumns{Value: value, Call: call, RuntimeKindCandidate: runtimeKindCandidate}
	if !columns.Available() {
		return ValueRuntimeKindColumns{}, false
	}
	return columns, true
}

// Available reports whether every column this binding needs carries an
// owner-issued type and live storage.
func (columns ValueRuntimeKindColumns) Available() bool {
	return columns.Value.Available() && columns.Call.Available() && columns.RuntimeKindCandidate.Available()
}

// ValueRuntimeKindArgument is the decoded frame of one
// value/runtimekind invocation.
type ValueRuntimeKindArgument struct {
	Candidate  valuedomain.RuntimeKindCall
	Dispatched calldomain.Value
	Subject    valuedomain.Value
	Comparison valuedomain.Value
}

// ValueRuntimeKindJudgment is the owner mathematics this binding carries. The axis
// states it by hand: nothing in this file can name a relation, a cell, a
// buffer or an engine value, so the mathematics stays where its owner wrote
// it and this artifact stays free of it.
type ValueRuntimeKindJudgment interface {
	relbindgen.Operation[ValueRuntimeKindArgument, valuedomain.Value]
	Available() bool
}

// The hand-authored judgment answers this family's own contract, and the
// assertion is what makes the two halves one binding.
var _ ValueRuntimeKindJudgment = ValueRuntimeKindOperation{}

// BindValueRuntimeKind admits the value/runtimekind family
// under its sealed signature.
func BindValueRuntimeKind(operation signature.Signature, judgment ValueRuntimeKindJudgment, columns ValueRuntimeKindColumns, refusal model.RefusalID) (binding.Factory, bool) {
	if judgment == nil || !judgment.Available() || !columns.Available() {
		return nil, false
	}
	return relbindgen.Bind(relbindgen.Spec[ValueRuntimeKindArgument, valuedomain.Value]{
		Signature: operation,
		Decoder:   valueRuntimeKindDecoder{columns: columns},
		Encoder:   valueRuntimeKindEncoder{columns: columns},
		Operation: judgment,
		Address:   0,
		Refusal:   refusal,
	})
}

type valueRuntimeKindDecoder struct {
	columns ValueRuntimeKindColumns
}

func (decoder valueRuntimeKindDecoder) Decode(inputs relbindgen.Inputs) (ValueRuntimeKindArgument, bool) {
	candidate, ok := relbindgen.ScalarAt(inputs, 0, decoder.columns.RuntimeKindCandidate)
	if !ok {
		return ValueRuntimeKindArgument{}, false
	}
	dispatched, ok := relbindgen.ScalarAt(inputs, 1, decoder.columns.Call)
	if !ok {
		return ValueRuntimeKindArgument{}, false
	}
	subject, ok := relbindgen.ScalarAt(inputs, 2, decoder.columns.Value)
	if !ok {
		return ValueRuntimeKindArgument{}, false
	}
	comparison, ok := relbindgen.ScalarAt(inputs, 3, decoder.columns.Value)
	if !ok {
		return ValueRuntimeKindArgument{}, false
	}
	return ValueRuntimeKindArgument{Candidate: candidate, Dispatched: dispatched, Subject: subject, Comparison: comparison}, true
}

type valueRuntimeKindEncoder struct {
	columns ValueRuntimeKindColumns
}

func (encoder valueRuntimeKindEncoder) Encode(outputs relbindgen.Outputs, value valuedomain.Value) bool {
	return relbindgen.PutColumn(outputs, 0, encoder.columns.Value, value)
}
