// Code generated by the rule family emitter from the "heap-empty" rule declaration; DO NOT EDIT.
//
// The installer seals every primitive through the plane at the geometry the
// declaration states, the family holds one sealed row per plan row, and the
// worker performs one invocation over lane-owned scratch. The semantic fold
// this file calls, and the relation derivations its joins name, remain the
// owner's own source.

package empty

import (
	"github.com/wippyai/go-lua/analysis/engine/execution"
	"github.com/wippyai/go-lua/analysis/schema/rule/program"
	"github.com/wippyai/go-lua/analysis/schema/structure"
	"github.com/wippyai/go-lua/domain/heap"
)

// familyReducer is the sealed semantic half of one invocation. It holds the
// carriers this row's fold is indexed by, and its type is the family's, so the
// call below is a static direct call rather than an interface dispatch.
type familyReducer struct {
	candidate heap.Key
}

// Reduce answers the fact this row publishes from the one exact cell it read.
// The read declares explicit sparsity, so an unwritten predecessor is delivered
// as absence and settles as this rule's absent candidate: nothing here invents
// a world the Factor never wrote.
func (fold familyReducer) Reduce(cell heap.Value, present bool) (heap.Value, structure.ReductionOutcome) {
	if !present {
		var absent heap.Value
		return absent, structure.NoCandidate
	}
	return heap.EmptyAllocationFact(fold.candidate, cell)
}

// familyRow is the sealed static half of one plan row: the candidate its fold
// is indexed by and every primitive the installer sealed through the plane.
type familyRow struct {
	candidate   heap.Key
	read0       execution.ExactRead[heap.DenseCoordinate, heap.Value]
	read0Policy execution.ReadCellPolicy[heap.Value]
	write       execution.CarryWrite[heap.DenseCoordinate, heap.Value]
}

// sealedFamily is this rule's whole installed family: one row per plan row and
// the sealed state every invocation reads. Nothing here is mutated after the
// installer returns.
type sealedFamily struct {
	rows []familyRow
}

func (sealed *sealedFamily) NewExecutor(run *execution.Run) execution.Executor {
	if sealed == nil || run == nil {
		return nil
	}
	return &familyWorker{family: sealed, run: run}
}

func (*sealedFamily) InputCapacity() int  { return 1 }
func (*sealedFamily) OutputCapacity() int { return 1 }

// familyWorker is one epoch's reusable invocation lane. Every scratch lives for
// the worker's lifetime, so a warm invocation opens its cursors and its write
// transaction without allocating.
type familyWorker struct {
	family *sealedFamily
	run    *execution.Run
	read0  execution.Scratch[heap.DenseCoordinate, heap.Value]
	write  execution.Scratch[heap.DenseCoordinate, heap.Value]
}

// settle submits one non-publishing disposition. Every refusal path in this
// worker ends here, so the ticket is settled exactly once.
func (lane *familyWorker) settle(ticket execution.Ticket, outcome structure.ReductionOutcome) (execution.Result, bool) {
	if !ticket.Submit(outcome) {
		return execution.Result{}, false
	}
	return execution.NewResult(outcome, 0)
}

// Execute performs one carry invocation: the declared exact cell is reduced to
// the fact this row publishes, and every carried coordinate passes through the
// candidate's transition in the same patch.
func (lane *familyWorker) Execute(frame execution.Frame, ticket execution.Ticket) (execution.Result, bool) {
	if lane == nil || lane.family == nil || lane.run == nil || !frame.Valid(ticket) || !lane.run.Owns(ticket) {
		return execution.Result{}, false
	}
	local, localOK := ticket.LocalOrdinal()
	if !localOK || uint64(local) >= uint64(len(lane.family.rows)) {
		return execution.Result{}, false
	}
	row := lane.family.rows[local]
	outcome := execution.FoldCarry(ticket, familyReducer{candidate: row.candidate}, row.read0, &lane.read0, row.write, &lane.write)
	if !ticket.Submit(outcome) {
		return execution.Result{}, false
	}
	written := 0
	if outcome == structure.Concrete {
		written = 1
	}
	return execution.NewResult(outcome, written)
}

// familyInstaller authors this rule's execution family. The axis schemas it
// holds are the ones the declaration names: the candidate directory it resolves
// dense candidates through, and every static axis a declared relation derives
// against. It reaches no owner callback and no runtime capability.
//
// It holds NO rule ordinal. Which rule an installer authors is the claim it
// was installed under, and the family table resolves an installer only for
// that claim; a copy kept here would be a second answer to a question the
// table already answers, and one that goes stale on its own.
type familyInstaller struct {
	heapSchema heap.Schema
}

// NewFamilyInstaller seals this rule's family installer against the axis schemas
// its declaration names. The bind arm that resolves those schemas from its
// composition's authorities is the owner's own, because how an authority
// record is reached is that composition's knowledge and not this rule's.
func NewFamilyInstaller(heapSchema heap.Schema) (execution.RuleFamilyInstaller[heap.DenseCoordinate, heap.Value], bool) {
	install := familyInstaller{heapSchema: heapSchema}
	if !install.available() {
		return nil, false
	}
	return install, true
}

// available proves every schema this installer seals against was supplied.
// Whether a supplied schema is itself admissible is that schema's own answer,
// given below when a candidate or a projection is resolved through it.
func (install familyInstaller) available() bool {
	return true
}

func (install familyInstaller) InstallRuleFamily(plane execution.FormPlane[heap.DenseCoordinate, heap.Value], _ uint32, rows []execution.FormRow) (execution.Family, []execution.FormAddress, bool) {
	if !install.available() || !plane.Valid() || len(rows) == 0 {
		return nil, nil, false
	}
	sealed := &sealedFamily{rows: make([]familyRow, 0, len(rows))}
	addresses := make([]execution.FormAddress, 0, len(rows))
	for _, planRow := range rows {
		if planRow.Form != execution.FormCarry || !planRow.Rule.Available() || planRow.Rule.ReadCount() != 1 || planRow.Rule.OutputCount() != 1 {
			return nil, nil, false
		}
		output, outputOK := planRow.Rule.OutputAt(0)
		if !outputOK || output.Mode != program.ModeExact || output.RouteJoinPresent || output.Slot != 0 {
			return nil, nil, false
		}
		carryMode, carryPresent := planRow.Rule.CarryMode()
		if !carryPresent || carryMode != program.CarryTransform {
			return nil, nil, false
		}
		plan0, plan0OK := planRow.Rule.ReadAt(0)
		if !plan0OK || plan0.Form != program.Exact || plan0.Input != 0 || plan0.PointBound != program.PointBound {
			return nil, nil, false
		}
		candidate, candidateOK := install.heapSchema.EmptyAllocationAt(int(planRow.Candidate))
		if !candidateOK {
			return nil, nil, false
		}
		foreign0, foreign0OK := plane.Foreign(plan0.Factor)
		if !foreign0OK {
			return nil, nil, false
		}
		read0Sealed, read0SealedOK := execution.ForeignRowExactRead[heap.DenseCoordinate, heap.Value](foreign0, planRow, 0)
		read0Policy, read0PolicyOK := execution.ForeignReadCellPolicy[heap.DenseCoordinate, heap.Value](foreign0, plan0.Contract)
		if !read0PolicyOK {
			return nil, nil, false
		}
		writeSealed, writeSealedOK := plane.RowCarry(planRow, candidate.Age)
		if !writeSealedOK || !read0SealedOK {
			return nil, nil, false
		}
		addresses = append(addresses, execution.FormAddress{Member: planRow.Member, Local: uint32(len(sealed.rows))})
		sealed.rows = append(sealed.rows, familyRow{candidate: candidate, read0: read0Sealed, read0Policy: read0Policy, write: writeSealed})
	}
	return sealed, addresses, true
}
