// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.

package relation

import (
	"github.com/wippyai/go-lua/analysis/identity"
	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
	"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"
	heapdomain "github.com/wippyai/go-lua/domain/heap"
)

// PayloadTypes names the owner-issued TypeID each column of this axis
// carries.
type PayloadTypes struct {
	Heap          model.TypeID
	HeapCandidate model.TypeID
	HeapRoute     model.TypeID
}

// Available reports whether every column has an owner-issued type.
func (types PayloadTypes) Available() bool {
	return types.Heap.Available() && types.HeapCandidate.Available() && types.HeapRoute.Available()
}

// PayloadTags names the store fence each column of this axis interns under.
type PayloadTags struct {
	Heap          identity.ContentID
	HeapCandidate identity.ContentID
	HeapRoute     identity.ContentID
}

// Available reports whether every column has a store fence.
func (tags PayloadTags) Available() bool {
	return tags.Heap.Available() && tags.HeapCandidate.Available() && tags.HeapRoute.Available()
}

// Payloads is this axis's thin typed owner-column publisher: one Column per
// payload type the axis declares, each over its own solve-local store, and
// the only place one of its domain values crosses into a value token.
type Payloads struct {
	Heap          *relbindgen.Column[heapdomain.Value]
	HeapCandidate *relbindgen.Column[heapdomain.Key]
	HeapRoute     *relbindgen.Column[RouteFact]
}

// NewPayloads installs one column per declared payload over a store fenced
// by that payload's own tag. Reserve is the interning reservation each store
// starts with; a store grows past it, so it is a caller's sizing and never a
// bound on what an owner may intern.
func NewPayloads(types PayloadTypes, tags PayloadTags, reserve int) (Payloads, bool) {
	if !types.Available() || !tags.Available() || reserve < 0 {
		return Payloads{}, false
	}
	var payloads Payloads
	heapStore, ok := relbindgen.NewStore[heapdomain.Value](tags.Heap, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.Heap, ok = relbindgen.NewColumn(types.Heap, heapStore); !ok {
		return Payloads{}, false
	}
	heapCandidateStore, ok := relbindgen.NewStore[heapdomain.Key](tags.HeapCandidate, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.HeapCandidate, ok = relbindgen.NewColumn(types.HeapCandidate, heapCandidateStore); !ok {
		return Payloads{}, false
	}
	heapRouteStore, ok := relbindgen.NewStore[RouteFact](tags.HeapRoute, reserve)
	if !ok {
		return Payloads{}, false
	}
	if payloads.HeapRoute, ok = relbindgen.NewColumn(types.HeapRoute, heapRouteStore); !ok {
		return Payloads{}, false
	}
	return payloads, true
}

// Available reports whether every column carries live storage.
func (payloads Payloads) Available() bool {
	return payloads.Heap.Available() && payloads.HeapCandidate.Available() && payloads.HeapRoute.Available()
}

// Lattices are this axis's ascent witnesses. Each names the owner's own
// API, so this layer never guesses a method name and never carries a
// function value.
type Lattices struct {
	Heap HeapLattice
}

// Algebras states one ascent authority per TypeID that declares an order.
// The state layer resolves a proposal's order by TypeID alone, never by the
// operation that produced it.
func (payloads Payloads) Algebras(issuer binding.Issuer, lattices Lattices) ([]binding.ValueAlgebra, bool) {
	if !payloads.Available() || !issuer.Available() {
		return nil, false
	}
	algebras := make([]binding.ValueAlgebra, 0, 1)
	heapAlgebra, ok := relbindgen.NewAlgebra[heapdomain.Value, HeapLattice](payloads.Heap, issuer, lattices.Heap)
	if !ok {
		return nil, false
	}
	algebras = append(algebras, heapAlgebra)
	return algebras, true
}
