// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.

package relation

import (
	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
	"github.com/wippyai/go-lua/analysis/relation/semantic/signature"
	"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"
	heapdomain "github.com/wippyai/go-lua/domain/heap"
	indexdomain "github.com/wippyai/go-lua/domain/heap/index"
	valuedomain "github.com/wippyai/go-lua/domain/value"
)

// RawGetPackRoutesColumns are the owner column codecs of the
// heap/index binding.
type RawGetPackRoutesColumns struct {
	Value         *relbindgen.Column[valuedomain.Value]
	Heap          *relbindgen.Column[heapdomain.Value]
	HeapRoute     *relbindgen.Column[HeapRouteFact]
	PackRoute     *relbindgen.Column[PackRouteFact]
	ReadCandidate *relbindgen.Column[indexdomain.Index]
}

// NewRawGetPackRoutesColumns names this family's own owner columns. A column an axis
// other than this one publishes is handed in, never reached for.
func NewRawGetPackRoutesColumns(value *relbindgen.Column[valuedomain.Value], heap *relbindgen.Column[heapdomain.Value], heapRoute *relbindgen.Column[HeapRouteFact], packRoute *relbindgen.Column[PackRouteFact], readCandidate *relbindgen.Column[indexdomain.Index]) (RawGetPackRoutesColumns, bool) {
	columns := RawGetPackRoutesColumns{Value: value, Heap: heap, HeapRoute: heapRoute, PackRoute: packRoute, ReadCandidate: readCandidate}
	if !columns.Available() {
		return RawGetPackRoutesColumns{}, false
	}
	return columns, true
}

// Available reports whether every column this binding needs carries an
// owner-issued type and live storage.
func (columns RawGetPackRoutesColumns) Available() bool {
	return columns.Value.Available() && columns.Heap.Available() && columns.HeapRoute.Available() && columns.PackRoute.Available() && columns.ReadCandidate.Available()
}

// RawGetPackRoutesArgument is the decoded frame of one
// heap/index invocation.
type RawGetPackRoutesArgument struct {
	Route     HeapRouteFact
	Fact      heapdomain.Value
	Candidate indexdomain.Index
	Key       relbindgen.Span[valuedomain.Value]
}

// RawGetPackRoutesJudgment is the owner mathematics this binding carries. The axis
// states it by hand: nothing in this file can name a relation, a cell, a
// buffer or an engine value, so the mathematics stays where its owner wrote
// it and this artifact stays free of it.
type RawGetPackRoutesJudgment interface {
	relbindgen.Operation[RawGetPackRoutesArgument, PackRouteFact]
	Available() bool
}

// The hand-authored judgment answers this family's own contract, and the
// assertion is what makes the two halves one binding.
var _ RawGetPackRoutesJudgment = RawGetPackRoutesOperation{}

// BindRawGetPackRoutes admits the heap/index family
// under its sealed signature.
func BindRawGetPackRoutes(operation signature.Signature, judgment RawGetPackRoutesJudgment, columns RawGetPackRoutesColumns, refusal model.RefusalID) (binding.Factory, bool) {
	if judgment == nil || !judgment.Available() || !columns.Available() {
		return nil, false
	}
	return relbindgen.Bind(relbindgen.Spec[RawGetPackRoutesArgument, PackRouteFact]{
		Signature: operation,
		Decoder:   rawGetPackRoutesDecoder{columns: columns},
		Encoder:   rawGetPackRoutesEncoder{columns: columns},
		Operation: judgment,
		Address:   relbindgen.KeyedDestination,
		Refusal:   refusal,
	})
}

type rawGetPackRoutesDecoder struct {
	columns RawGetPackRoutesColumns
}

func (decoder rawGetPackRoutesDecoder) Decode(inputs relbindgen.Inputs) (RawGetPackRoutesArgument, bool) {
	route, ok := relbindgen.ScalarAt(inputs, 0, decoder.columns.HeapRoute)
	if !ok {
		return RawGetPackRoutesArgument{}, false
	}
	fact, ok := relbindgen.ScalarAt(inputs, 1, decoder.columns.Heap)
	if !ok {
		return RawGetPackRoutesArgument{}, false
	}
	candidate, ok := relbindgen.ScalarAt(inputs, 2, decoder.columns.ReadCandidate)
	if !ok {
		return RawGetPackRoutesArgument{}, false
	}
	key, ok := relbindgen.SpanAt(inputs, 3, decoder.columns.Value)
	if !ok {
		return RawGetPackRoutesArgument{}, false
	}
	return RawGetPackRoutesArgument{Route: route, Fact: fact, Candidate: candidate, Key: key}, true
}

type rawGetPackRoutesEncoder struct {
	columns RawGetPackRoutesColumns
}

func (encoder rawGetPackRoutesEncoder) Encode(outputs relbindgen.Outputs, value PackRouteFact) bool {
	return relbindgen.PutColumn(outputs, 0, encoder.columns.PackRoute, value)
}
