// Code generated by analysis/schema/rule/relbindgen/relbind. DO NOT EDIT.

package relation

import (
	"github.com/wippyai/go-lua/analysis/relation/schema/model"
	"github.com/wippyai/go-lua/analysis/relation/semantic/binding"
	"github.com/wippyai/go-lua/analysis/relation/semantic/signature"
	"github.com/wippyai/go-lua/analysis/schema/rule/relbindgen"
	valuedomain "github.com/wippyai/go-lua/domain/value"
)

// RawGetCallRoutesColumns are the owner column codecs of the
// heap/index binding.
type RawGetCallRoutesColumns struct {
	Value     *relbindgen.Column[valuedomain.Value]
	KeyRoute  *relbindgen.Column[KeyRouteFact]
	CallRoute *relbindgen.Column[CallRouteFact]
}

// NewRawGetCallRoutesColumns names this family's own owner columns. A column an axis
// other than this one publishes is handed in, never reached for.
func NewRawGetCallRoutesColumns(value *relbindgen.Column[valuedomain.Value], keyRoute *relbindgen.Column[KeyRouteFact], callRoute *relbindgen.Column[CallRouteFact]) (RawGetCallRoutesColumns, bool) {
	columns := RawGetCallRoutesColumns{Value: value, KeyRoute: keyRoute, CallRoute: callRoute}
	if !columns.Available() {
		return RawGetCallRoutesColumns{}, false
	}
	return columns, true
}

// Available reports whether every column this binding needs carries an
// owner-issued type and live storage.
func (columns RawGetCallRoutesColumns) Available() bool {
	return columns.Value.Available() && columns.KeyRoute.Available() && columns.CallRoute.Available()
}

// RawGetCallRoutesArgument is the decoded frame of one
// heap/index invocation.
type RawGetCallRoutesArgument struct {
	Key      KeyRouteFact
	Receiver valuedomain.Value
}

// RawGetCallRoutesJudgment is the owner mathematics this binding carries. The axis
// states it by hand: nothing in this file can name a relation, a cell, a
// buffer or an engine value, so the mathematics stays where its owner wrote
// it and this artifact stays free of it.
type RawGetCallRoutesJudgment interface {
	relbindgen.Operation[RawGetCallRoutesArgument, CallRouteFact]
	Available() bool
}

// The hand-authored judgment answers this family's own contract, and the
// assertion is what makes the two halves one binding.
var _ RawGetCallRoutesJudgment = RawGetCallRoutesOperation{}

// BindRawGetCallRoutes admits the heap/index family
// under its sealed signature.
func BindRawGetCallRoutes(operation signature.Signature, judgment RawGetCallRoutesJudgment, columns RawGetCallRoutesColumns, refusal model.RefusalID) (binding.Factory, bool) {
	if judgment == nil || !judgment.Available() || !columns.Available() {
		return nil, false
	}
	return relbindgen.Bind(relbindgen.Spec[RawGetCallRoutesArgument, CallRouteFact]{
		Signature: operation,
		Decoder:   rawGetCallRoutesDecoder{columns: columns},
		Encoder:   rawGetCallRoutesEncoder{columns: columns},
		Operation: judgment,
		Address:   relbindgen.KeyedDestination,
		Refusal:   refusal,
	})
}

type rawGetCallRoutesDecoder struct {
	columns RawGetCallRoutesColumns
}

func (decoder rawGetCallRoutesDecoder) Decode(inputs relbindgen.Inputs) (RawGetCallRoutesArgument, bool) {
	key, ok := relbindgen.ScalarAt(inputs, 0, decoder.columns.KeyRoute)
	if !ok {
		return RawGetCallRoutesArgument{}, false
	}
	receiver, ok := relbindgen.ScalarAt(inputs, 1, decoder.columns.Value)
	if !ok {
		return RawGetCallRoutesArgument{}, false
	}
	return RawGetCallRoutesArgument{Key: key, Receiver: receiver}, true
}

type rawGetCallRoutesEncoder struct {
	columns RawGetCallRoutesColumns
}

func (encoder rawGetCallRoutesEncoder) Encode(outputs relbindgen.Outputs, value CallRouteFact) bool {
	return relbindgen.PutColumn(outputs, 0, encoder.columns.CallRoute, value)
}
